using System;
using System.Collections.Generic;
using Selerant.ApplicationBlocks.Data;
using Selerant.DevEx.BusinessLayer;

namespace Selerant.DevEx.Modules.DIRModule.BackEnd.OutputManagement
{
    [IsDxObject]
    [BoundTable(typeof(BizDsOutputCategory), TableName = "DXDIR_OUTPUT_CATEGORY")]
    public partial class DxOutputCategory : DxObject
    {
        #region Constants

        private const string configElementName = "dxOutputCategory";

        #endregion

        #region Fields

        [BoundColumn("ID", true, 0, DbType = GenericDbType.Decimal)]
        protected decimal id;

        [BoundColumn("TITLE", DbType = GenericDbType.Nvarchar)]
        protected string title;

        [BoundColumn("SORT_ORDER", DbType = GenericDbType.Int)]
        protected decimal sortOrder;

        [BoundColumn("TYPE", DbType = GenericDbType.Varchar)]
        [PhraseMapping(DxPhraseTypeCategory.ListOfValuesStandard, "DXDIR_OUTPUT_CATEGORY.TYPE", PhraseMappingAttribute.ApplyToQueryMode.NotInSelect)]
        protected string type;

        #endregion

        #region Properties

        [BoundProperty(new string[] { nameof(id) })]
        public decimal Id
        {
            get { return id; }
        }

        [BoundProperty(new string[] { nameof(title) })]
        public string Title
        {
            get { return title; }
            set { Change(x => title = x, value); }
        }

        [BoundProperty(new string[] { nameof(sortOrder) })]
        public decimal SortOrder
        {
            get { return sortOrder; }
            set { Change(x => sortOrder = x, value); }
        }

        [BoundProperty(new string[] { nameof(type) })]
        public string Type
        {
            get { return type; }
            set { Change(x => type = x, value); }
        }

        #endregion

        #region Constructor

        public DxOutputCategory() : base()
        {
            AutogeneratedIdentityKey = true;
        }

        public DxOutputCategory(decimal id) : this(id, false)
        {
        }

        public DxOutputCategory(decimal id, bool load) : this()
        {
            this.id = id;

            if (load)
                Load();
        }

        #endregion

        #region Overrides

        protected override bool SetNextIdentityKeyDirect()
        {
            var bizDsObj = new BizDsOutputCategory();
            SetIdentityKeyValues(new object[] { bizDsObj.GetNextId() });
            return true;
        }

        #endregion

        #region Configuration

        protected override void OnConfigure()
        {
            base.OnConfigure();
            Configure();
        }

        private void Configure()
        {
            ReadConfigurationElement(configElementName);
            //Add any specific configuration
        }
    
        #endregion
    }
}