IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_INPUT_PCP_SPREAD$InsertRecord'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_INPUT_PCP_SPREAD$InsertRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_INPUT_PCP_SPREAD$InsertRecord]
	@dcINPUT_ID BIGINT,
	@sDESTINATION_CODE VARCHAR(64)
AS
BEGIN
	INSERT [dbo].[DXDIR_INPUT_PROD_COPROD_SPREAD]
	(
		[INPUT_ID],
		[DESTINATION_CODE]
	)
	VALUES
	(
		@dcINPUT_ID,
		@sDESTINATION_CODE
	)
END
GO


IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_INPUT_PCP_SPREAD$UpdateRecord'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_INPUT_PCP_SPREAD$UpdateRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_INPUT_PCP_SPREAD$UpdateRecord]
	@dcINPUT_ID BIGINT,
	@sDESTINATION_CODE VARCHAR(64)
AS
BEGIN
	UPDATE [dbo].[DXDIR_INPUT_PROD_COPROD_SPREAD]
	SET 
		[INPUT_ID] = @dcINPUT_ID,
		[DESTINATION_CODE] = @sDESTINATION_CODE
	WHERE [INPUT_ID] = @dcINPUT_ID
	AND [DESTINATION_CODE] = @sDESTINATION_CODE;
END
GO


IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_INPUT_PCP_SPREAD$DeleteRecord'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_INPUT_PCP_SPREAD$DeleteRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_INPUT_PCP_SPREAD$DeleteRecord]
	@dcINPUT_ID BIGINT
	,@sDESTINATION_CODE VARCHAR(64)
AS
BEGIN
	DELETE FROM [dbo].[DXDIR_INPUT_PROD_COPROD_SPREAD]
	WHERE INPUT_ID = @dcINPUT_ID
	AND DESTINATION_CODE = @sDESTINATION_CODE;
END
GO


IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_INPUT_PCP_SPREAD$SelectProductCoProductSpread'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_INPUT_PCP_SPREAD$SelectProductCoProductSpread]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_INPUT_PCP_SPREAD$SelectProductCoProductSpread]
	@dcINPUT_IDS DX_NumberTable READONLY
AS
BEGIN
	SELECT INPUT_ID, DESTINATION_CODE
	FROM DXDIR_INPUT_PROD_COPROD_SPREAD
	WHERE INPUT_ID IN (SELECT CONTENT FROM @dcINPUT_IDS)
END
GO