TRUNCATE TABLE DXDIR_INPUT_PROD_COPROD_SPREAD;
GO

WITH productCoProduct AS 
(
	SELECT ID as INPUT_ID, 'PRODUCT' as DESTINATION_CODE
	FROM DXDIR_INPUT
	WHERE PART_OF_PRODUCT_COPRODUCT = 1
	UNION ALL
	SELECT ID as INPUT_ID, 'COPRODUCT' as DESTINATION_CODE
	FROM DXDIR_INPUT
	WHERE PART_OF_PRODUCT_COPRODUCT = 1
)
INSERT INTO DXDIR_INPUT_PROD_COPROD_SPREAD (INPUT_ID, DESTINATION_CODE)
SELECT * FROM productCoProduct;

GO