using System;
using System.Collections.Generic;
using System.Linq;
using Selerant.ApplicationBlocks.Data;
using Selerant.DevEx.BusinessLayer;

namespace Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects
{
	[IsDxObject]
	[BoundTable(typeof(BizDsAssessmentLcStage), TableName = "DXDIR_ASSESSMENT_LC_STAGE")]
	public partial class DxAssessmentLcStage : DxObject
	{
		#region Constants

		private const string configElementName = "dxAssessmentLcStage";

		#endregion

		#region Fields

		[BoundColumn("ID", true, 0, DbType = GenericDbType.Decimal)]
		protected decimal id;

		[BoundColumn("ASSESSMENT_CODE", DbType = GenericDbType.Varchar)]
		protected string assessmentCode;

		[BoundColumn("TITLE", DbType = GenericDbType.Nvarchar)]
		protected string title;

		[BoundColumn("SORT_ORDER", DbType = GenericDbType.Int)]
		protected decimal sortOrder;

		[BoundColumn("VISIBLE", DbType = GenericDbType.Int)]
		protected decimal visible;

		[BoundColumn("SOURCE_ASMT_LC_STAGE_ID", DbType = GenericDbType.Decimal)]
		protected Nullable<decimal> sourceAssessmentLcStageId;

		#endregion

		#region Properties

		[BoundProperty(new string[] { nameof(id) })]
		public decimal Id
		{
			get { return id; }
		}

		[BoundProperty(new string[] { nameof(assessmentCode) })]
		public string AssessmentCode
		{
			get { return assessmentCode; }
			set { Change(x => assessmentCode = x, value); }
		}

		[BoundProperty(new string[] { nameof(title) })]
		public string Title
		{
			get { return title; }
			set { Change(x => title = x, value); }
		}

		[BoundProperty(new string[] { nameof(sortOrder) })]
		public decimal SortOrder
		{
			get { return sortOrder; }
			set { Change(x => sortOrder = x, value); }
		}

		[BoundProperty(new string[] { nameof(visible) })]
		public bool Visible
		{
			get { return visible == 1.0m; }
			set { Change(x => visible = x ? 1.0m : 0.0m, value); }
		}

		[BoundProperty(new string[] { nameof(sourceAssessmentLcStageId) })]
		public decimal? SourceAssessmentLcStageId
		{
			get { return sourceAssessmentLcStageId; }
			set { Change(x => sourceAssessmentLcStageId = x, value); }
		}

		#endregion

		#region Constructor

		public DxAssessmentLcStage() : base()
		{
			AutogeneratedIdentityKey = false;
		}

		public DxAssessmentLcStage(decimal id) : this(id, false)
		{
		}

		public DxAssessmentLcStage(decimal id, bool load) : this()
		{
			this.id = id;

			if (load)
				Load();
		}

		#endregion

		#region Overrides

		protected override bool SetNextIdentityKeyDirect()
		{
			var bizDsObj = new BizDsAssessmentLcStage();
			SetIdentityKeyValues(new object[] { bizDsObj.GetNextId() });
			return true;
		}

		#endregion

		#region Configuration

		protected override void OnConfigure()
		{
			base.OnConfigure();
			Configure();
		}

		private void Configure()
		{
			ReadConfigurationElement(configElementName);
			//Add any specific configuration
		}

		#endregion
	}
}
