CREATE OR REPLACE PACKAGE DXDIR_PK_RESULT AS

	PROCEDURE InsertRecord
	(
		dcID NUMBER,
		sASSESSMENT_CODE VARCHAR2,
		dcASSESSMENT_LC_STAGE_ID NUMBER,
		dcRESULT_ROW_ID NUMBER,
		dcRESULT NUMBER
	);

	PROCEDURE UpdateRecord
	(
		dcID NUMBER,
		sASSESSMENT_CODE VARCHAR2,
		dcASSESSMENT_LC_STAGE_ID NUMBER,
		dcRESULT_ROW_ID NUMBER,
		dcRESULT NUMBER
	);

	PROCEDURE DeleteRecord
	(
		dcID NUMBER
	);

	PROCEDURE GetNextId
	(
        dcNextID OUT NUMBER
    );

END;
/

CREATE OR REPLACE PACKAGE BODY DXDIR_PK_RESULT AS

	PROCEDURE InsertRecord
	(
		dcID NUMBER,
		sASSESSMENT_CODE VARCHAR2,
		dcASSESSMENT_LC_STAGE_ID NUMBER,
		dcRESULT_ROW_ID NUMBER,
		dcRESULT NUMBER
	)
	IS
	BEGIN
		INSERT INTO DXDIR_RESULT
		(
			ID,
			ASSESSMENT_CODE,
			ASSESSMENT_LC_STAGE_ID,
			RESULT_ROW_ID,
			RESULT
		)
		VALUES
		(
			dcID,
			sASSESSMENT_CODE,
			dcASSESSMENT_LC_STAGE_ID,
			dcRESULT_ROW_ID,
			dcRESULT
		);
	END;

	PROCEDURE UpdateRecord
	(
		dcID NUMBER,
		sASSESSMENT_CODE VARCHAR2,
		dcASSESSMENT_LC_STAGE_ID NUMBER,
		dcRESULT_ROW_ID NUMBER,
		dcRESULT NUMBER
	)
	IS
	BEGIN
		UPDATE DXDIR_RESULT
		SET 
			ASSESSMENT_CODE = sASSESSMENT_CODE,
			ASSESSMENT_LC_STAGE_ID = dcASSESSMENT_LC_STAGE_ID,
			RESULT_ROW_ID = dcRESULT_ROW_ID,
			RESULT = dcRESULT
		WHERE
			ID = dcID;
	END;

	PROCEDURE DeleteRecord
	(
		dcID NUMBER
	)
	IS
	BEGIN
		DELETE FROM DXDIR_RESULT
		WHERE
			ID = dcID;
	END;

	PROCEDURE GetNextId
	(
        dcNextID OUT NUMBER
    )
	IS
	BEGIN
		SELECT DXDIR_RESULT_SEQ.NEXTVAL INTO dcNextID FROM DUAL;
	END;

END;
/
