CREATE OR REPLACE PACKAGE DXDIR_PK_ASSESSMENT_DEST AS

	PROCEDURE InsertRecord
	(
		sASSESSMENT_CODE VARCHAR2,
		sDESTINATION_CODE VARCHAR2
	);

	PROCEDURE DeleteRecord
	(
		sASSESSMENT_CODE VARCHAR2,
		sDESTINATION_CODE VARCHAR2
	);

END;
/

CREATE OR REPLACE PACKAGE BODY DXDIR_PK_ASSESSMENT_DEST AS

	PROCEDURE InsertRecord
	(
		sASSESSMENT_CODE VARCHAR2,
		sDESTINATION_CODE VARCHAR2
	)
	IS
	BEGIN
		INSERT INTO DXDIR_ASSESSMENT_DESTINATION
		(
			ASSESSMENT_CODE,
			DESTINATION_CODE
		)
		VALUES
		(
			sASSESSMENT_CODE,
			sDESTINATION_CODE
		);
	END;

	PROCEDURE DeleteRecord
	(
		sASSESSMENT_CODE VARCHAR2,
		sDESTINATION_CODE VARCHAR2
	)
	IS
	BEGIN
		DELETE FROM DXDIR_ASSESSMENT_DESTINATION
		WHERE
			ASSESSMENT_CODE = sASSESSMENT_CODE
			AND DESTINATION_CODE = sDESTINATION_CODE;
	END;

END;
/
