CREATE OR REPLACE PACKAGE DXDIR_PK_ASSESSMENT AS
   
    PROCEDURE InsertRecord
    (
        sCODE VARCHAR2,
		sTYPE_CODE VARCHAR2,
        sDESCRIPTION NVARCHAR2,
		sSTATUS VARCHAR2,
		sCOMPANY_NAME NVARCHAR2,
		dcCOMPLETING_BY NUMBER,
		sPHONE VARCHAR2,
		sEMAIL VARCHAR2,
		dtTIMEFRAME_FROM DATE,
		dtTIMEFRAME_TO DATE,
		dcWASTE_WATER_DISCHARGE_RATIO NUMBER,
		sCURRENCY NVARCHAR2,
		dtCREATE_DATE DATE,
		dcCREATED_BY NUMBER,
		dtMOD_DATE DATE,
		dcMODIFIED_BY NUMBER,
		dcAUTHORIZATION_ROLE NUMBER,
		sORG_STRUCTURE VARCHAR2,
		sLOCATION VARCHAR2,
		sPROD_CLASSIF VARCHAR2
    );

    PROCEDURE UpdateRecord
    (
        sCODE VARCHAR2,
		sTYPE_CODE VARCHAR2,
        sDESCRIPTION NVARCHAR2,
		sSTATUS VARCHAR2,
		sCOMPANY_NAME NVARCHAR2,
		dcCOMPLETING_BY NUMBER,
		sPHONE VARCHAR2,
		sEMAIL VARCHAR2,
		dtTIMEFRAME_FROM DATE,
		dtTIMEFRAME_TO DATE,
		dcWASTE_WATER_DISCHARGE_RATIO NUMBER,
		sCURRENCY NVARCHAR2,
		dtCREATE_DATE DATE,
		dcCREATED_BY NUMBER,
		dtMOD_DATE DATE,
		dcMODIFIED_BY NUMBER,
		dcAUTHORIZATION_ROLE NUMBER,
		sORG_STRUCTURE VARCHAR2,
		sLOCATION VARCHAR2,
		sPROD_CLASSIF VARCHAR2
    );

    PROCEDURE DeleteRecord
    (
        sCODE VARCHAR2
    );

END;
/

CREATE OR REPLACE PACKAGE BODY DXDIR_PK_ASSESSMENT AS

    PROCEDURE InsertRecord
    (
        sCODE VARCHAR2,
		sTYPE_CODE VARCHAR2,
        sDESCRIPTION NVARCHAR2,
		sSTATUS VARCHAR2,
		sCOMPANY_NAME NVARCHAR2,
		dcCOMPLETING_BY NUMBER,
		sPHONE VARCHAR2,
		sEMAIL VARCHAR2,
		dtTIMEFRAME_FROM DATE,
		dtTIMEFRAME_TO DATE,
		dcWASTE_WATER_DISCHARGE_RATIO NUMBER,
		sCURRENCY NVARCHAR2,
		dtCREATE_DATE DATE,
		dcCREATED_BY NUMBER,
		dtMOD_DATE DATE,
		dcMODIFIED_BY NUMBER,
		dcAUTHORIZATION_ROLE NUMBER,
		sORG_STRUCTURE VARCHAR2,
		sLOCATION VARCHAR2,
		sPROD_CLASSIF VARCHAR2
    )
    IS
    BEGIN 
        INSERT INTO DXDIR_ASSESSMENT
        (
			CODE,
			TYPE_CODE,
			DESCRIPTION,
			STATUS,
			COMPANY_NAME,
			COMPLETING_BY,
			PHONE,
			EMAIL,
			TIMEFRAME_FROM,
			TIMEFRAME_TO,
			WASTE_WATER_DISCHARGE_RATIO,
			CURRENCY,
			CREATE_DATE,
			CREATED_BY,
			MOD_DATE,
			MODIFIED_BY,
			AUTHORIZATION_ROLE,
			ORG_STRUCTURE,
			LOCATION,
			PROD_CLASSIF
        )
        VALUES
        (
			sCODE,
			sTYPE_CODE,
			sDESCRIPTION,
			sSTATUS,
			sCOMPANY_NAME,
			dcCOMPLETING_BY,
			sPHONE,
			sEMAIL,
			dtTIMEFRAME_FROM,
			dtTIMEFRAME_TO,
			dcWASTE_WATER_DISCHARGE_RATIO,
			sCURRENCY,
			dtCREATE_DATE,
			dcCREATED_BY,
			dtMOD_DATE,
			dcMODIFIED_BY,
			dcAUTHORIZATION_ROLE,
			sORG_STRUCTURE,
			sLOCATION,
			sPROD_CLASSIF
        );
    END;

    PROCEDURE UpdateRecord
    (
        sCODE VARCHAR2,
		sTYPE_CODE VARCHAR2,
        sDESCRIPTION NVARCHAR2,
		sSTATUS VARCHAR2,
		sCOMPANY_NAME NVARCHAR2,
		dcCOMPLETING_BY NUMBER,
		sPHONE VARCHAR2,
		sEMAIL VARCHAR2,
		dtTIMEFRAME_FROM DATE,
		dtTIMEFRAME_TO DATE,
		dcWASTE_WATER_DISCHARGE_RATIO NUMBER,
		sCURRENCY NVARCHAR2,
		dtCREATE_DATE DATE,
		dcCREATED_BY NUMBER,
		dtMOD_DATE DATE,
		dcMODIFIED_BY NUMBER,
		dcAUTHORIZATION_ROLE NUMBER,
		sORG_STRUCTURE VARCHAR2,
		sLOCATION VARCHAR2,
		sPROD_CLASSIF VARCHAR2
    )
    IS
    BEGIN
        UPDATE DXDIR_ASSESSMENT
        SET 
			TYPE_CODE = sTYPE_CODE,
			DESCRIPTION = sDESCRIPTION,
			STATUS = sSTATUS,
			COMPANY_NAME = sCOMPANY_NAME,
			COMPLETING_BY = dcCOMPLETING_BY,
			PHONE = sPHONE,
			EMAIL = sEMAIL,
			TIMEFRAME_FROM = dtTIMEFRAME_FROM,
			TIMEFRAME_TO = dtTIMEFRAME_TO,
			WASTE_WATER_DISCHARGE_RATIO = dcWASTE_WATER_DISCHARGE_RATIO,
			CURRENCY = sCURRENCY,
			CREATE_DATE = dtCREATE_DATE,
			CREATED_BY = dcCREATED_BY,
			MOD_DATE = dtMOD_DATE,
			MODIFIED_BY = dcMODIFIED_BY,
			AUTHORIZATION_ROLE = dcAUTHORIZATION_ROLE,
			ORG_STRUCTURE = sORG_STRUCTURE,
			LOCATION = sLOCATION,
			PROD_CLASSIF = sPROD_CLASSIF
        WHERE
            CODE = sCODE;
    END;

    PROCEDURE DeleteRecord
    (
        sCODE VARCHAR2
    )
    IS
    BEGIN
        DELETE FROM DXDIR_ASSESSMENT
        WHERE
            CODE = sCODE;
    END;
END;
/