CREATE OR REPLACE PACKAGE DXDIR_PK_INPUT_PCP_SPREAD AS

	TYPE t_cursor IS REF CURSOR;
	
	PROCEDURE InsertRecord
	(
		dcINPUT_ID NUMBER,
		sDESTINATION_CODE VARCHAR
	);

	PROCEDURE UpdateRecord
	(
		dcINPUT_ID NUMBER,
		sDESTINATION_CODE VARCHAR
	);

	PROCEDURE DeleteRecord
	(
		dcINPUT_ID NUMBER,
		sDESTINATION_CODE VARCHAR
	);

	PROCEDURE SelectProductCoProductSpread
	(
		dcINPUT_IDS DX_PK_UTILITY.DX_NumberArray,
		po_cur in OUT t_cursor
	);
    
END;
/

CREATE OR REPLACE PACKAGE BODY DXDIR_PK_INPUT_PCP_SPREAD AS

	PROCEDURE InsertRecord
	(
		dcINPUT_ID NUMBER,
		sDESTINATION_CODE VARCHAR
	)
	IS
	BEGIN
		INSERT INTO DXDIR_INPUT_PROD_COPROD_SPREAD
		(
			INPUT_ID,
			DESTINATION_CODE
		)
		VALUES
		(
			dcINPUT_ID,
			sDESTINATION_CODE
		);
	END;

	PROCEDURE UpdateRecord
	(
		dcINPUT_ID NUMBER,
		sDESTINATION_CODE VARCHAR
	)
	IS
	BEGIN
		UPDATE DXDIR_INPUT_PROD_COPROD_SPREAD
		SET
			INPUT_ID = dcINPUT_ID,
            DESTINATION_CODE = sDESTINATION_CODE
		WHERE
			INPUT_ID = dcINPUT_ID
			AND DESTINATION_CODE = sDESTINATION_CODE;
	END;

	PROCEDURE DeleteRecord
	(
		dcINPUT_ID NUMBER,
		sDESTINATION_CODE VARCHAR
	)
	IS
	BEGIN
		DELETE FROM DXDIR_INPUT_PROD_COPROD_SPREAD
		WHERE
			INPUT_ID = dcINPUT_ID
			AND DESTINATION_CODE = sDESTINATION_CODE;
	END;

	PROCEDURE SelectProductCoProductSpread
	(
		dcINPUT_IDS DX_PK_UTILITY.DX_NumberArray,
		po_cur in OUT t_cursor
	)
	IS
		v_inputIds DX_NumberTable;
	BEGIN
		v_inputIds := DX_PK_Utility.ArrayToTable(dcINPUT_IDS);

		OPEN po_cur FOR
			SELECT INPUT_ID, DESTINATION_CODE
			FROM DXDIR_INPUT_PROD_COPROD_SPREAD
			WHERE INPUT_ID IN (SELECT COLUMN_VALUE FROM THE(SELECT CAST(v_inputIds AS DX_NumberTable) FROM DUAL));
	END;

END;
/
