CREATE OR REPLACE PACKAGE DXDIR_PK_OUTPUT_GRIDITEM AS

	TYPE t_cursor IS REF CURSOR;

	PROCEDURE GetOutputGridItems
	(
		sASSESSMENT_CODE VARCHAR2,
		dcASSESSMENT_LC_STAGE_ID NUMBER,
		po_cur in OUT t_cursor
	);

END;
/

CREATE OR REPLACE PACKAGE BODY DXDIR_PK_OUTPUT_GRIDITEM AS
 
	PROCEDURE GetOutputGridItems
	(
		sASSESSMENT_CODE VARCHAR2,
		dcASSESSMENT_LC_STAGE_ID NUMBER,
		po_cur IN OUT t_cursor
	)
	IS
	BEGIN
		OPEN po_cur FOR
			SELECT
				O.ID,
				O.OUTPUT_CATEGORY_ID,
				OC.TITLE AS OUTPUT_CATEGORY_TITLE,
				OC.TYPE AS OUTPUT_CATEGORY_TYPE,
				O.DESTINATION_CODE,
				D.TITLE AS DESTINATION_TITLE,
				O.OUTPUT_COST,
				O.INCOME
			FROM DXDIR_OUTPUT O
			JOIN DXDIR_OUTPUT_CATEGORY OC
			ON O.OUTPUT_CATEGORY_ID = OC.ID
			LEFT JOIN DXDIR_DESTINATION D
			ON O.DESTINATION_CODE = D.CODE
			WHERE O.ASSESSMENT_CODE = sASSESSMENT_CODE AND
				  O.ASSESSMENT_LC_STAGE_ID = dcASSESSMENT_LC_STAGE_ID AND
				  O.INPUT_ID IS NULL
			ORDER BY OC.SORT_ORDER, O.SORT_ORDER;
	END;

 END;
/
