CREATE OR REPLACE PACKAGE DXDIR_PK_PARTNER_ASMT_TYPE AS

	PROCEDURE InsertRecord
	(
		sASSESSMENT_TYPE_CODE VARCHAR2,
		sPARTNER_ORG_CODE VARCHAR2,
		dcIS_SHARED NUMBER
	);

	PROCEDURE UpdateRecord
	(
		sASSESSMENT_TYPE_CODE VARCHAR2,
		sPARTNER_ORG_CODE VARCHAR2,
		dcIS_SHARED NUMBER
	);

	PROCEDURE DeleteRecord
	(
		sASSESSMENT_TYPE_CODE VARCHAR2,
		sPARTNER_ORG_CODE VARCHAR2
	);

END;
/

CREATE OR REPLACE PACKAGE BODY DXDIR_PK_PARTNER_ASMT_TYPE AS

	PROCEDURE InsertRecord
	(
		sASSESSMENT_TYPE_CODE VARCHAR2,
		sPARTNER_ORG_CODE VARCHAR2,
		dcIS_SHARED NUMBER
	)
	IS
	BEGIN
		INSERT INTO DXDIR_PARTNER_ASSESSMENT_TYPE
		(
			ASSESSMENT_TYPE_CODE,
			PARTNER_ORG_CODE,
			IS_SHARED
		)
		VALUES
		(
			sASSESSMENT_TYPE_CODE,
			sPARTNER_ORG_CODE,
			dcIS_SHARED
		);
	END;

	PROCEDURE UpdateRecord
	(
		sASSESSMENT_TYPE_CODE VARCHAR2,
		sPARTNER_ORG_CODE VARCHAR2,
		dcIS_SHARED NUMBER
	)
	IS
	BEGIN
		UPDATE DXDIR_PARTNER_ASSESSMENT_TYPE
		SET 
			IS_SHARED = dcIS_SHARED
		WHERE
			ASSESSMENT_TYPE_CODE = sASSESSMENT_TYPE_CODE
			AND PARTNER_ORG_CODE = sPARTNER_ORG_CODE;
	END;

	PROCEDURE DeleteRecord
	(
		sASSESSMENT_TYPE_CODE VARCHAR2,
		sPARTNER_ORG_CODE VARCHAR2
	)
	IS
	BEGIN
		DELETE FROM DXDIR_PARTNER_ASSESSMENT_TYPE
		WHERE
			ASSESSMENT_TYPE_CODE = sASSESSMENT_TYPE_CODE
			AND PARTNER_ORG_CODE = sPARTNER_ORG_CODE;
	END;

END;
/
