IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_INPUT_DESTINATION$SelectFoodDestinations'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_INPUT_DESTINATION$SelectFoodDestinations]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_INPUT_DESTINATION$SelectFoodDestinations]
    @sASSESSMENT_CODE VARCHAR(32),
    @dcASSESSMENT_LC_STAGE_ID BIGINT
AS
BEGIN
	WITH cteINPUTS_UNION AS
    (
        SELECT DXDIR_INPUT.ID, 
                DXDIR_INPUT.ASSESSMENT_CODE, 
                4 AS OUTPUT_CATEGORY_ID,
                'FOOD' AS OUTPUT_CATEGORY_TITLE,
                DXDIR_INPUT.MAT_PLANT,
                DXDIR_INPUT.MAT_CODE,
                DXDIR_INPUT.PART_OF_PRODUCT_COPRODUCT,
                DXDIR_INPUT.CATEGORY_SORT_ORDER,
                DXDIR_INPUT.INPUT_SORT_ORDER,
				DXDIR_INPUT.PRODUCT_SOURCE
        FROM DXDIR_INPUT
            INNER JOIN DXDIR_INPUT_CATEGORY
            ON DXDIR_INPUT.INPUT_CATEGORY_ID = DXDIR_INPUT_CATEGORY.ID
        WHERE DXDIR_INPUT.INEDIBLE_PARTS < 1.0 AND DXDIR_INPUT.ASSESSMENT_CODE = @sASSESSMENT_CODE AND DXDIR_INPUT.ASSESSMENT_LC_STAGE_ID = @dcASSESSMENT_LC_STAGE_ID AND DXDIR_INPUT_CATEGORY.TYPE = 'FOOD'
        UNION ALL
        SELECT DXDIR_INPUT.ID,
                DXDIR_INPUT.ASSESSMENT_CODE,
                5 AS OUTPUT_CATEGORY_ID,
                'INEDIBLE_PARTS' AS OUTPUT_CATEGORY_TITLE,
                DXDIR_INPUT.MAT_PLANT,
                DXDIR_INPUT.MAT_CODE,
                0 AS PART_OF_PRODUCT_COPRODUCT,
                DXDIR_INPUT.CATEGORY_SORT_ORDER,
                DXDIR_INPUT.INPUT_SORT_ORDER,
				DXDIR_INPUT.PRODUCT_SOURCE
        FROM DXDIR_INPUT
            INNER JOIN DXDIR_INPUT_CATEGORY
            ON DXDIR_INPUT.INPUT_CATEGORY_ID = DXDIR_INPUT_CATEGORY.ID
        WHERE DXDIR_INPUT.INEDIBLE_PARTS > 0.0 AND DXDIR_INPUT.ASSESSMENT_CODE = @sASSESSMENT_CODE AND DXDIR_INPUT.ASSESSMENT_LC_STAGE_ID = @dcASSESSMENT_LC_STAGE_ID AND DXDIR_INPUT_CATEGORY.TYPE = 'FOOD'
    ),
	cteINPUTS_W_DEST AS
	(
		SELECT cteINPUTS_UNION.ID as INPUT_ID,
				cteINPUTS_UNION.OUTPUT_CATEGORY_ID,
				cteINPUTS_UNION.OUTPUT_CATEGORY_TITLE,
				cteINPUTS_UNION.MAT_PLANT,
				cteINPUTS_UNION.MAT_CODE,
				cteINPUTS_UNION.PART_OF_PRODUCT_COPRODUCT,
				cteINPUTS_UNION.CATEGORY_SORT_ORDER,
                cteINPUTS_UNION.INPUT_SORT_ORDER,
				cteINPUTS_UNION.PRODUCT_SOURCE,
				DXDIR_INPUT_DESTINATION.DESTINATION_CODE,
				DXDIR_INPUT_DESTINATION.PERCENTAGE
		FROM cteINPUTS_UNION
			LEFT JOIN DXDIR_INPUT_DESTINATION
			ON DXDIR_INPUT_DESTINATION.INPUT_ID = cteINPUTS_UNION.ID
			AND DXDIR_INPUT_DESTINATION.OUTPUT_CATEGORY_ID = cteINPUTS_UNION.OUTPUT_CATEGORY_ID
	)
	SELECT INPUT_ID,
		OUTPUT_CATEGORY_ID,
		OUTPUT_CATEGORY_TITLE,
		MAT_PLANT,
		MAT_CODE,
		PART_OF_PRODUCT_COPRODUCT,
		PRODUCT_SOURCE,
		PRODUCT,
		PRODUCT_2,
		PRODUCT_3,
		COPRODUCT,
		COPRODUCT_2,
        FOOD_RESCUE,
		ANIMAL_FEED,
		BIOMASS_MATERIAL,
		CODIGESTION_ANAEROBIC,
		COMPOSTING,
		COMBUSTION,
		LAND_APP,
		LANDFILL,
		NOT_HARVESTED,
		REFUSE_DISCARD,
		SEWER,
		ENVIRONMENT_LOSS,
		OTHER
	FROM cteINPUTS_W_DEST
	PIVOT (
		MIN(PERCENTAGE)
		FOR DESTINATION_CODE
		-- below are all possible values from DXDIR_DESTINATION this can only be dynamic with PIVOT XML or DYNAMIC SQL
		IN (PRODUCT,
			PRODUCT_2,
			PRODUCT_3,
			COPRODUCT,
			COPRODUCT_2,
			FOOD_RESCUE,
			ANIMAL_FEED,
			BIOMASS_MATERIAL,
			CODIGESTION_ANAEROBIC,
			COMPOSTING,
			COMBUSTION,
			LAND_APP,
			LANDFILL,
			NOT_HARVESTED,
			REFUSE_DISCARD,
			SEWER,
			ENVIRONMENT_LOSS,
			OTHER
			)
	) AS pivot_table
    ORDER BY OUTPUT_CATEGORY_ID, CATEGORY_SORT_ORDER, INPUT_SORT_ORDER ASC;
END
GO

IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_INPUT_DESTINATION$SelectNonFoodDestinations'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_INPUT_DESTINATION$SelectNonFoodDestinations]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_INPUT_DESTINATION$SelectNonFoodDestinations]
    @sASSESSMENT_CODE VARCHAR(32),
    @dcASSESSMENT_LC_STAGE_ID BIGINT
AS
BEGIN
        WITH cteINPUTS_W_DEST AS
		(
			SELECT DXDIR_INPUT.ID as INPUT_ID,
					6 AS OUTPUT_CATEGORY_ID,
					'NON_FOOD' AS OUTPUT_CATEGORY_TITLE,
					DXDIR_INPUT.MAT_PLANT,
					DXDIR_INPUT.MAT_CODE,
					DXDIR_INPUT.PART_OF_PRODUCT_COPRODUCT,
					DXDIR_INPUT.CATEGORY_SORT_ORDER,
					DXDIR_INPUT.INPUT_SORT_ORDER,
					DXDIR_INPUT.PRODUCT_SOURCE,
					DXDIR_INPUT_DESTINATION.DESTINATION_CODE,
					DXDIR_INPUT_DESTINATION.PERCENTAGE
			FROM DXDIR_INPUT
				INNER JOIN DXDIR_INPUT_CATEGORY
				ON DXDIR_INPUT.INPUT_CATEGORY_ID = DXDIR_INPUT_CATEGORY.ID
				LEFT JOIN DXDIR_INPUT_DESTINATION
				ON DXDIR_INPUT_DESTINATION.INPUT_ID = DXDIR_INPUT.ID
				AND DXDIR_INPUT_DESTINATION.OUTPUT_CATEGORY_ID = 6
				WHERE DXDIR_INPUT.ASSESSMENT_CODE = @sASSESSMENT_CODE AND DXDIR_INPUT.ASSESSMENT_LC_STAGE_ID = @dcASSESSMENT_LC_STAGE_ID AND ISNULL(DXDIR_INPUT_CATEGORY.TYPE, '') <> 'FOOD'
		)
		SELECT INPUT_ID,
			OUTPUT_CATEGORY_ID,
			OUTPUT_CATEGORY_TITLE,
			MAT_PLANT,
			MAT_CODE,
			PART_OF_PRODUCT_COPRODUCT,
			PRODUCT_SOURCE,
			PRODUCT,
			PRODUCT_2,
			PRODUCT_3,
			COPRODUCT,
			COPRODUCT_2,
			FOOD_RESCUE,
			RECYCLING,
			INCIN_WITH_EN_RECOVER,
			LANDFILL,
			SEWER,
			OTHER
		FROM cteINPUTS_W_DEST
		PIVOT (
			MIN(PERCENTAGE)
			FOR DESTINATION_CODE
			-- below are all possible values from DXDIR_DESTINATION this can only be dynamic with PIVOT XML or DYNAMIC SQL
			IN (PRODUCT,
				PRODUCT_2,
				PRODUCT_3,
				COPRODUCT,
				COPRODUCT_2,
				FOOD_RESCUE,
				RECYCLING,
				INCIN_WITH_EN_RECOVER,
				LANDFILL,
				SEWER,
				OTHER
				)
		) AS pivot_table
		ORDER BY OUTPUT_CATEGORY_ID, CATEGORY_SORT_ORDER, INPUT_SORT_ORDER ASC;
END
GO