using System;
using Selerant.ApplicationBlocks.Data;
using Selerant.DevEx.BusinessLayer;

namespace Selerant.DevEx.Modules.DIRModule.BackEnd.InputManagement
{
	[IsDxObject]
	[BoundTable(typeof(BizDsInputCategory), TableName = "DXDIR_INPUT_CATEGORY")]
	public partial class DxInputCategory : DxObject
	{
		#region Constants

		private const string configElementName = "dxInputCategory";

		#endregion

		#region Fields

		[BoundColumn("ID", true, 0, DbType = GenericDbType.Decimal)]
		protected decimal id;

		[BoundColumn("ASSESSMENT_CODE", DbType = GenericDbType.Varchar)]
		protected string assessmentCode;

		[BoundColumn("TITLE", DbType = GenericDbType.Nvarchar)]
		protected string title;

		[BoundColumn("TYPE", DbType = GenericDbType.Varchar)]
		[PhraseMapping(DxPhraseTypeCategory.ListOfValuesAttributes, "99510", PhraseMappingAttribute.ApplyToQueryMode.NotInSelect)]
		protected string type;

		#endregion

		#region Properties

		[BoundProperty(new string[] { nameof(id) })]
		public decimal Id
		{
			get { return id; }
		}

		[BoundProperty(new string[] { nameof(assessmentCode) })]
		public string AssessmentCode
		{
			get { return assessmentCode; }
			set { Change(x => assessmentCode = x, value); }
		}

		[BoundProperty(new string[] { nameof(title) })]
		public string Title
		{
			get { return title; }
			set { Change(x => title = x, value); }
		}

		[BoundProperty(new string[] { nameof(type) })]
		public string Type
		{
			get { return type; }
			set { Change(x => type = x, value); }
		}

		[BoundProperty(IsValid = false)]
		public decimal SortOrder { get; set; }

		#endregion

		#region Constructor

		public DxInputCategory() : base()
		{
			AutogeneratedIdentityKey = true;
		}

		public DxInputCategory(decimal id) : this(id, false)
		{
		}

		public DxInputCategory(decimal id, bool load) : this()
		{
			this.id = id;

			if (load)
				Load();
		}

		#endregion

		#region Overrides

		protected override bool SetNextIdentityKeyDirect()
		{
			var bizDsObj = new BizDsInputCategory();
			SetIdentityKeyValues(new object[] { bizDsObj.GetNextId() });
			return true;
		}

		#endregion

		#region Configuration

		protected override void OnConfigure()
		{
			base.OnConfigure();
			Configure();
		}

		private void Configure()
		{
			ReadConfigurationElement(configElementName);
			//Add any specific configuration
		}

		#endregion
	}
}
