using Selerant.ApplicationBlocks.Data;
using Selerant.DevEx.BusinessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentTypeManagement.LcStageTemplate
{
    [Serializable]
    [IsDxObject]
    [BoundTable(typeof(BizDsLcStageTemplate), TableName = "DXDIR_LC_STAGE_TMPL")]
    public partial class DxLcStageTemplate : DxObject
    {
        #region Constants

        private const string configElementName = "dxLcStageTemplate";

        #endregion

        #region Fields

        [BoundColumn("ID", true, 0, DbType = GenericDbType.Decimal)]
        protected decimal id;

        [BoundColumn("ASSESSMENT_TYPE_CODE", DbType = GenericDbType.Varchar)]
        protected string assessmentTypeCode;

        [BoundColumn("TITLE", DbType = GenericDbType.Nvarchar)]
        protected string title;

        [BoundColumn("SORT_ORDER", DbType = GenericDbType.Int)]
        protected decimal sortOrder;

        #endregion

        #region Properties

        [BoundProperty(new string[] { nameof(id) })]
        public decimal Id
        {
            get { return id; }
        }

        [BoundProperty(new string[] { nameof(assessmentTypeCode) })]
        public string AssessmentTypeCode
        {
            get { return assessmentTypeCode; }
            set { Change(x => assessmentTypeCode = x, value); }
        }

        [BoundProperty(new string[] { nameof(title) })]
        public string Title
        {
            get { return title; }
            set { Change(x => title = x, value); }
        }

        [BoundProperty(new string[] { nameof(sortOrder) })]
        public decimal SortOrder
        {
            get { return sortOrder; }
            set { Change(x => sortOrder = x, value); }
        }

        #endregion

        #region Constructor

        public DxLcStageTemplate() : base()
        {
            AutogeneratedIdentityKey = true;
        }

        public DxLcStageTemplate(decimal id) : this(id, false)
        {

        }

        public DxLcStageTemplate(decimal id, bool load) : this()
        {
            this.id = id;

            if (load)
                Load();
        }

        #endregion

        #region Overrides

        protected override bool SetNextIdentityKeyDirect()
        {
            var bizDsObj = new BizDsLcStageTemplate();
            SetIdentityKeyValues(new object[] { bizDsObj.GetNextId() });
            return true;
        }

        #endregion

        #region Configuration

        protected override void OnConfigure()
        {
            base.OnConfigure();
            Configure();
        }

        private void Configure()
        {
            ReadConfigurationElement(configElementName);
            //Add any specific configuration
        }

        #endregion
    }
}
