using System;
using System.Collections.Generic;
using System.Linq;
using Selerant.ApplicationBlocks.Data;
using Selerant.DevEx.BusinessLayer;
using Selerant.DevEx.Modules.DIRModule.BackEnd.Common;

namespace Selerant.DevEx.Modules.DIRModule.BackEnd.InputManagement
{
	[IsDxObject]
	[BoundTable(typeof(BizDsInput), TableName = "DXDIR_INPUT")]
	public partial class DxInput : DxCarriedInput
	{
		#region Constants

		private const string configElementName = "dxInput";

		#endregion

		#region Fields

		[BoundColumn("PART_OF_PRODUCT_COPRODUCT", DbType = GenericDbType.Decimal)]
		protected decimal partOfProductCoproduct;

		[BoundColumn("INEDIBLE_PARTS", DbType = GenericDbType.Decimal)]
		protected Nullable<decimal> inedibleParts;

		protected string[] nonWasteDestinationForDeletion;
		protected bool doUpdateDeletePropagation = true;

		#endregion

		#region Properties


		[BoundProperty(new string[] { nameof(partOfProductCoproduct) })]
		public bool PartOfProductCoproduct
		{
			get { return partOfProductCoproduct == 1.0m; }
			set { Change(x => partOfProductCoproduct = x ? 1.0m : 0.0m, value); }
		}

		[BoundProperty(new string[] { nameof(packaging) })]
		public bool? Packaging
		{
			get { return packaging.HasValue ? new bool?(packaging == 1.0m) : null; }
			set { Change(x => packaging = x.HasValue ? (new decimal?(x.Value ? 1.0m : 0.0m)) : null, value); }
		}

		[BoundProperty(new string[] { nameof(inedibleParts) })]
		public decimal? InedibleParts
		{
			get { return inedibleParts; }
			set { Change(x => inedibleParts = x, value); }
		}

		#endregion

		#region Private Propeties

		private BizDsInput bizDsObject;
		private BizDsInput BizDsObject
		{
			get
			{
				if (bizDsObject == null)
					bizDsObject = new BizDsInput();
				return bizDsObject;
			}
		}

		#endregion

		#region Constructor

		public DxInput() : base()
		{
			AutogeneratedIdentityKey = true;
		}

		public DxInput(decimal id) : this(id, false)
		{
		}

		public DxInput(decimal id, bool load) : this()
		{
			this.id = id;
			if (load)
				Load();
		}

		public static DxInput NewFromCarried(DxCarriedInput source)
		{
			return new DxInput(source.Id)
			{
				assessmentCode = source.AssessmentCode,
				inputCategoryId = source.InputCategoryId,
				assessmentLcStageId = source.AssessmentLcStageId,
				materialPlant = source.MaterialPlant,
				materialCode = source.MaterialCode,
				mass = source.Mass,
				cost = source.Cost,
				measurement = (decimal)source.Measurement,
                categorySortOrder = source.CategorySortOrder,
                InputSortOrder =source.InputSortOrder,
				productSource = source.ProductSource
			};
		}

		#endregion

		#region Overrides

		protected override bool SetNextIdentityKeyDirect()
		{
			SetIdentityKeyValues(new object[] { BizDsObject.GetNextId() });
			return true;
		}

		protected override bool CreateDirect()
		{
			(categorySortOrder, inputSortOrder) = BizDsObject.GetNextSortOrder(assessmentCode, inputCategoryId, assessmentLcStageId);
			return base.CreateDirect();
		}

		public override void OnAfterCreate()
		{
			if (materialPlant == DxPlant.NONE && (materialCode == Constants.ResourceMaterial.DIR_FOOD_WATER || materialCode == Constants.ResourceMaterial.DIR_NONFOOD_WATER))
			{
				BizDsObject.ManageWastewaterRow(assessmentCode, assessmentLcStageId);
			}
			base.OnAfterCreate();
		}

		public override void OnAfterUpdate()
		{
			base.OnAfterUpdate();
			if (doUpdateDeletePropagation)
			{
				if (nonWasteDestinationForDeletion.Length > 0)
				{
					var bizDsInputDestination = new BizDsInputDestination();
					bizDsInputDestination.DeleteDestiantionByCodes(Id, nonWasteDestinationForDeletion);
				}

				BizDsObject.UpdateDestinInediblePart(AssessmentCode, AssessmentLcStageId, Id);
				BizDsObject.UpdateCascadeOnOutput(AssessmentCode, AssessmentLcStageId);
				BizDsObject.UpdateOutputAnotherDestination(AssessmentCode, AssessmentLcStageId, Id);
			}
		}

		public override void OnBeforeDelete()
		{
			if (doUpdateDeletePropagation)
			{
				BizDsObject.DeleteCascadeOutputParent(new decimal[] { Id }, AssessmentCode, AssessmentLcStageId);
				base.OnBeforeDelete();
			}
		}

		public override void OnAfterDelete()
		{
			if (doUpdateDeletePropagation)
			{
				base.OnAfterDelete();

				BizDsObject.UpdateCascadeOnOutput(AssessmentCode, AssessmentLcStageId);
				BizDsObject.ManageWastewaterRow(AssessmentCode, AssessmentLcStageId);
			}
		}

		#endregion

		#region Configuration

		protected override void OnConfigure()
		{
			base.OnConfigure();
			Configure();
		}

		private void Configure()
		{
			ReadConfigurationElement(configElementName);
			//Add any specific configuration
		}

		#endregion

		#region Public Methods

		public void ManageOutputWastewater()
		{
			BizDsObject.ManageWastewaterRow(assessmentCode, assessmentLcStageId);
		}

		public DxInput DisableUpdateDeletePropagation()
		{
			doUpdateDeletePropagation = false;
			return this;
		}

		public DxInput SetCurrentNonWasteDestinationCodes(string[] currentNonWasteDestinationCodes, IReadOnlyCollection<string> allNonWasteDestinationCodes, IReadOnlyCollection<string> productCoProductDestionCodes)
		{
			if (currentNonWasteDestinationCodes.Length == 0)
				nonWasteDestinationForDeletion = allNonWasteDestinationCodes.ToArray();
			else
			{
				nonWasteDestinationForDeletion = productCoProductDestionCodes.Except(currentNonWasteDestinationCodes).ToArray();
			}

			return this;
		}

		#endregion
	}
}
