using Newtonsoft.Json;
using Selerant.DevEx.BusinessLayer;
using Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentTypeManagement;
using Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentTypeManagement.PartnerAssessmentType;
using Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models;
using Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.WebApplicationConfiguration.Base;
using Selerant.DevEx.WebMvcModules.Infrastructure.Controls;
using Selerant.DevEx.WebMvcModules.Infrastructure.Controls.Models;
using Selerant.DevEx.WebMvcModules.Infrastructure.ModelMetadataCustomization;
using Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models;
using Selerant.DevEx.WebPages;
using System;

namespace Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.DIRAdminTools.Models
{
    [CustomModelMetadataProviderTypeAttriibute(typeof(CustomModelMetadataProvider))]
    public class EditAssessmentTypeModel : DialogViewIndexModel, INavigatorPanelControllerDataContainer
    {
        public class CreateNewAssessmentTypeDialogFormData : IJsonNetSerialized
        {
            [JsonProperty(PropertyName = "Code")]
            public string Code { get; set; }

            [JsonProperty(PropertyName = "Description")]
            public string Description { get; set; }

            [JsonProperty(PropertyName = "IsAutoGeneratedCode")]
            public bool IsAutoGeneratedCode { get; set; }

            [JsonProperty(PropertyName = "IsNew")]
            public bool IsNew { get; set; }

            [JsonProperty(PropertyName = "IsEditMode")]
            public bool IsEditMode { get; set; }

        }

        #region Constants

        public const string ASSESSMENT_TYPE_EDIT_MODE = "AssessmentType_Edit_Mode";

        #endregion

        #region Properties & Fields

        private TextControlIndexModel _assessmentTypeDescription;
        private TextControlIndexModel _assessmentTypeCode;

        [DisplayNameUsingLocalization(ResourceFile = "DIR_AssessmentManager", ResourceKey = "ATAssessmentTypeDescription")]
        public TextControlIndexModel AssessmentTypeDescription
        {
            get
            {
                if (_assessmentTypeDescription == null)
                {
                    _assessmentTypeDescription = new TextControlIndexModel("AssessmentTypeDescription");
                }

                return _assessmentTypeDescription;
            }
            set
            {
                    _assessmentTypeDescription = value;
            }
        }

        [DisplayNameUsingLocalization(ResourceFile = "DIR_AssessmentManager", ResourceKey = "ATAssessmentTypeCode")]
        public TextControlIndexModel AssessmentTypeCode
        {
            get
            {
                if (_assessmentTypeCode == null)
                {
                    _assessmentTypeCode = new TextControlIndexModel("AssessmentTypeCode");
                }
                return _assessmentTypeCode;
            }
            set
            {
                _assessmentTypeCode = value;
            }
        }
        [DisplayNameUsingLocalization(ResourceFile = "DIR_AssessmentManager", ResourceKey = "ATAssessmentTypeActive")]
        public int AssessmentTypeActive { get; set; }

        public bool IsEditMode { get; set; }

        public bool IsNewAssessmentType { get; set; }

        NavigatorPanelControllerData INavigatorPanelControllerDataContainer.ControllerDataTyped
        {
            get
            {
                return ControllerData as NavigatorPanelControllerData;
            }
        }

        #endregion

        #region Constructors

        public EditAssessmentTypeModel(string controllerUrl, AdminToolControllerData controllerData, bool isEditMode = true)
            : base(controllerUrl, controllerData)
        {
            this.IsEditMode = isEditMode;
            CurrentRequestData.Instance.SelerantSession[ASSESSMENT_TYPE_EDIT_MODE] = this.IsEditMode;            
        }

        #endregion

        #region Lifecycle

        protected override void InitializeForView()
        {
            base.InitializeForView();
        }

        #endregion

        #region Methods

        /// <summary>
        /// Saving Assessment Type 
        /// </summary>
        /// <param name="viewModel"></param>
        /// <param name="message">Outcoming message</param>
        /// <returns>True if updating of existing or saving of new Recipe Type is successful, false if not</returns>
        public bool SaveAssessmentType(CreateNewAssessmentTypeDialogFormData viewModel, out string message)
        {
            bool result = false;
            string assmTypeCode = string.Empty;

            if (viewModel.IsNew)
            {
                // new Assessment Type
                if (!viewModel.IsAutoGeneratedCode)
                {
                    // AT Code not Autogenerated, check if exists
                    if (new DxAssessmentType(viewModel.Code).Exists())
                    {
                        message = Locale.GetString("DIR_AssessmentManager", "ATAssessmentTypeDialogSavedCodeExist");
                        return false;
                    }
                    assmTypeCode = viewModel.Code;
                }
                else
                {
                    //AT Code Autogenerated, simply assign it
                    assmTypeCode = DxAssessmentType.GetAutoNumberingKey(DxUser.CurrentUser);
                }

                message = Locale.GetString("DIR_AssessmentManager", "ATAssessmentTypeDialogSavedSuccess");

                DxAssessmentType assessmentType = new DxAssessmentType(assmTypeCode)
                {
                    Description = viewModel.Description
                };

                result = assessmentType.Create();

                if (DxUser.CurrentUser.IsExternal)
                {
                    DxPartnerAssessmentType partnerAssessmentType = new DxPartnerAssessmentType(assmTypeCode, DxUser.CurrentUser.PartnerOrganizationCode);
                    partnerAssessmentType.Create();
                }
            }
            else
            {
                // Assessment Type edit mode
                DxAssessmentType assessmentType = new DxAssessmentType(viewModel.Code);
                assessmentType.TryLoadCheckPersistenceStatus();
                assessmentType.Description = viewModel.Description;

                message = Locale.GetString("DIR_AssessmentManager", "ATAssessmentTypeDialogEditedSuccess");

                result = assessmentType.Update();
            }

            return result;
        }

        /// <summary>
        /// Activating Assessment Type 
        /// </summary>
        /// <param name="identifiableString"></param>
        /// <param name="message">Outcoming message</param>
        /// <returns>True if activation of existing Assessment Type is successful, false if not</returns>
        public bool ActivateAssessmentType(string identifiableString, out string message)
        {
            DxAssessmentType assessmentType = DxObject.ParseIdentifiableString<DxAssessmentType>(identifiableString);
            assessmentType.TryLoadCheckPersistenceStatus();
            assessmentType.Active = true;
            message = String.Empty;

            if (assessmentType.Update())
            {
                message = Locale.GetString("DIR_AssessmentManager", "ATAssessmentTypeDialogActivateSuccess");
                return true;
            }

            return false;
        }

        /// <summary>
        /// Deleting Assessment Type 
        /// </summary>
        /// <param name="identifiableString"></param>
        /// <param name="message">Outcoming message</param>
        /// <returns>True if activation of existing Assessment Type is successful, false if not</returns>
        public bool DeleteAssessmentType(string identifiableString, out string message)
        {
            DxAssessmentType assessmentType = DxObject.ParseIdentifiableString<DxAssessmentType>(identifiableString);
            assessmentType.TryLoadCheckPersistenceStatus();
            message = String.Empty;

            if (assessmentType.Delete())
            {
                message = Locale.GetString("DIR_AssessmentManager", "ATAssessmentTypeDialogDeleteSuccess");
                return true;
            }

            return false;
        }

        /// <summary>
        /// Preparing data for Assessment Type create/edit dialog
        /// </summary>
        /// <param name="identifiableString">IdentifiableString of current Assessment Type</param>
        public void PrepareData(string identifiableString)
        {
            DxAssessmentType assessmentType = new DxAssessmentType();
            AssessmentTypeCode = new TextControlIndexModel("AssessmentTypeCode");
            AssessmentTypeDescription = new TextControlIndexModel("AssessmentTypeDescription");

            IsNewAssessmentType = String.IsNullOrEmpty(identifiableString);

            if (IsNewAssessmentType == true)
            {
                AssessmentTypeCode.Value = String.Empty;
                AssessmentTypeDescription.Value = String.Empty;
            }
            else
            {
                assessmentType = DxObject.ParseIdentifiableString<DxAssessmentType>(identifiableString);
                assessmentType.TryLoadCheckPersistenceStatus();

                AssessmentTypeCode.Value = assessmentType.Code;
                AssessmentTypeDescription.Value = assessmentType.Description;
                AssessmentTypeCode.ReadOnly = true;
            }
        }

        #endregion
    }
}