IF EXISTS (
		SELECT *
		FROM sys.objects so
		JOIN sys.schemas sc ON so.schema_id = sc.schema_id
		WHERE so.NAME = N'DXDIR_PK_ASSESSMENT$InsertRecord'
			AND sc.NAME = N'dbo'
			AND type IN (N'P')
		)
	DROP PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT$InsertRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT$InsertRecord]
	 @sCODE VARCHAR(32),
	 @sTYPE_CODE VARCHAR(32),
	 @sDESCRIPTION NVARCHAR(512),
	 @sSTATUS VARCHAR(16),
	 @sCOMPANY_NAME NVARCHAR(512),
	 @dcCOMPLETING_BY BIGINT,
	 @sPHONE VARCHAR(64),
	 @sEMAIL VARCHAR(128),
	 @dtTIMEFRAME_FROM DATETIME,
	 @dtTIMEFRAME_TO DATETIME,
	 @dcWASTE_WATER_DISCHARGE_RATIO NUMERIC(3,2),
	 @sCURRENCY NVARCHAR(3),
	 @dtCREATE_DATE DATETIME,
	 @dcCREATED_BY BIGINT,
	 @dtMOD_DATE DATETIME,
	 @dcMODIFIED_BY BIGINT,
	 @dcAUTHORIZATION_ROLE BIGINT,
	 @sORG_STRUCTURE VARCHAR(32),
	 @sLOCATION VARCHAR(3),
	 @sPROD_CLASSIF VARCHAR(40)
AS
BEGIN
	INSERT [dbo].[DXDIR_ASSESSMENT]
	(
		[CODE],
		[TYPE_CODE],
		[DESCRIPTION],
		[STATUS],
		[COMPANY_NAME],
		[COMPLETING_BY],
		[PHONE],
		[EMAIL],
		[TIMEFRAME_FROM],
		[TIMEFRAME_TO],
		[WASTE_WATER_DISCHARGE_RATIO],
		[CURRENCY],
		[CREATE_DATE],
		[CREATED_BY],
		[MOD_DATE],
		[MODIFIED_BY],
		[AUTHORIZATION_ROLE],
		[ORG_STRUCTURE],
		[LOCATION],
		[PROD_CLASSIF]
	)
	VALUES
	(
		@sCODE,
		@sTYPE_CODE,
		@sDESCRIPTION,
		@sSTATUS,
		@sCOMPANY_NAME,
		@dcCOMPLETING_BY,
		@sPHONE,
		@sEMAIL,
		@dtTIMEFRAME_FROM,
		@dtTIMEFRAME_TO,
		@dcWASTE_WATER_DISCHARGE_RATIO,
		@sCURRENCY,
		@dtCREATE_DATE,
		@dcCREATED_BY,
		@dtMOD_DATE,
		@dcMODIFIED_BY,
		@dcAUTHORIZATION_ROLE,
		@sORG_STRUCTURE,
		@sLOCATION,
		@sPROD_CLASSIF
	)
END
GO


IF EXISTS (
		SELECT *
		FROM sys.objects so
		JOIN sys.schemas sc ON so.schema_id = sc.schema_id
		WHERE so.NAME = N'DXDIR_PK_ASSESSMENT$UpdateRecord'
			AND sc.NAME = N'dbo'
			AND type IN (N'P')
		)
	DROP PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT$UpdateRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT$UpdateRecord]
	 @sCODE VARCHAR(32),
	 @sTYPE_CODE VARCHAR(32),
	 @sDESCRIPTION NVARCHAR(512),
	 @sSTATUS VARCHAR(16),
	 @sCOMPANY_NAME NVARCHAR(512),
	 @dcCOMPLETING_BY BIGINT,
	 @sPHONE VARCHAR(64),
	 @sEMAIL VARCHAR(128),
	 @dtTIMEFRAME_FROM DATETIME,
	 @dtTIMEFRAME_TO DATETIME,
	 @dcWASTE_WATER_DISCHARGE_RATIO NUMERIC(3,2),
	 @sCURRENCY NVARCHAR(3),
	 @dtCREATE_DATE DATETIME,
	 @dcCREATED_BY BIGINT,
	 @dtMOD_DATE DATETIME,
	 @dcMODIFIED_BY BIGINT,
	 @dcAUTHORIZATION_ROLE BIGINT,
	 @sORG_STRUCTURE VARCHAR(32),
	 @sLOCATION VARCHAR(3),
	 @sPROD_CLASSIF VARCHAR(40)
AS
BEGIN
	UPDATE [dbo].[DXDIR_ASSESSMENT]
	SET 
		[TYPE_CODE] = @sTYPE_CODE,
		[DESCRIPTION] = @sDESCRIPTION,
		[STATUS] = @sSTATUS,
		[COMPANY_NAME] = @sCOMPANY_NAME,
		[COMPLETING_BY] = @dcCOMPLETING_BY,
		[PHONE] = @sPHONE,
		[EMAIL] = @sEMAIL,
		[TIMEFRAME_FROM] = @dtTIMEFRAME_FROM,
		[TIMEFRAME_TO] = @dtTIMEFRAME_TO,
		[WASTE_WATER_DISCHARGE_RATIO] = @dcWASTE_WATER_DISCHARGE_RATIO,
		[CURRENCY] = @sCURRENCY,
		[CREATE_DATE] = @dtCREATE_DATE,
		[CREATED_BY] = @dcCREATED_BY,
		[MOD_DATE] = @dtMOD_DATE,
		[MODIFIED_BY] = @dcMODIFIED_BY,
		[AUTHORIZATION_ROLE] = @dcAUTHORIZATION_ROLE,
		[ORG_STRUCTURE] = @sORG_STRUCTURE,
		[LOCATION] = @sLOCATION,
		[PROD_CLASSIF] = @sPROD_CLASSIF
	WHERE [CODE] = @sCODE
END
GO


IF EXISTS (
		SELECT *
		FROM sys.objects so
		JOIN sys.schemas sc ON so.schema_id = sc.schema_id
		WHERE so.NAME = N'DXDIR_PK_ASSESSMENT$DeleteRecord'
			AND sc.NAME = N'dbo'
			AND type IN (N'P')
		)
	DROP PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT$DeleteRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT$DeleteRecord]
	 @sCODE VARCHAR(32)
AS
BEGIN
	DELETE [dbo].[DXDIR_ASSESSMENT]
	WHERE [CODE] = @sCODE
END
GO