IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_ASSESSMENT_LC_STAGE$InsertRecord'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT_LC_STAGE$InsertRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT_LC_STAGE$InsertRecord]
	@dcID BIGINT,
	@sASSESSMENT_CODE VARCHAR(32),
	@sTITLE NVARCHAR(256),
	@dcVISIBLE INT,
	@dcSORT_ORDER INT,
	@dcSOURCE_ASMT_LC_STAGE_ID BIGINT
AS
BEGIN
	INSERT [dbo].[DXDIR_ASSESSMENT_LC_STAGE]
	(
		[ID],
		[ASSESSMENT_CODE],
		[TITLE],
		[VISIBLE],
		[SORT_ORDER],
		[SOURCE_ASMT_LC_STAGE_ID]
	)
	VALUES
	(
		@dcID,
		@sASSESSMENT_CODE,
		@sTITLE,
		@dcVISIBLE,
		@dcSORT_ORDER,
		@dcSOURCE_ASMT_LC_STAGE_ID
	)
END
GO


IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_ASSESSMENT_LC_STAGE$UpdateRecord'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT_LC_STAGE$UpdateRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT_LC_STAGE$UpdateRecord]
	@dcID BIGINT,
	@sASSESSMENT_CODE VARCHAR(32),
	@sTITLE NVARCHAR(256),
	@dcVISIBLE INT,
	@dcSORT_ORDER INT,
	@dcSOURCE_ASMT_LC_STAGE_ID BIGINT
AS
BEGIN
	UPDATE [dbo].[DXDIR_ASSESSMENT_LC_STAGE]
	SET 
		[ASSESSMENT_CODE] = @sASSESSMENT_CODE,
		[TITLE] = @sTITLE,
		[VISIBLE] = @dcVISIBLE,
		[SORT_ORDER] = @dcSORT_ORDER,
		[SOURCE_ASMT_LC_STAGE_ID] = @dcSOURCE_ASMT_LC_STAGE_ID
	WHERE [ID] = @dcID
END
GO


IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_ASSESSMENT_LC_STAGE$DeleteRecord'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT_LC_STAGE$DeleteRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT_LC_STAGE$DeleteRecord]
	@dcID BIGINT
AS
BEGIN
	DELETE FROM [dbo].[DXDIR_ASSESSMENT_LC_STAGE]
	WHERE [ID] = @dcID
END
GO


IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_ASSESSMENT_LC_STAGE$GetNextId'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT_LC_STAGE$GetNextId]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT_LC_STAGE$GetNextId]
	@dcNextId BIGINT OUTPUT 
AS
BEGIN
	SET @dcNextId = NULL

	DECLARE @dbname NVARCHAR(128) = db_name()

	EXEC DX_PK_UTILITY_SQLSRV$db_sp_get_next_sequence_value @dbname
		,N'dbo'
		,N'DXDIR_ASSESSMENT_LC_STAGE_SEQ'
		,@dcNextId OUTPUT
END
GO