IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_ASSESSMENT_DEST$InsertRecord'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT_DEST$InsertRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT_DEST$InsertRecord]
	@sASSESSMENT_CODE VARCHAR(32),
	@sDESTINATION_CODE VARCHAR(64)
AS
BEGIN
	INSERT [dbo].[DXDIR_ASSESSMENT_DESTINATION]
	(
		[ASSESSMENT_CODE],
		[DESTINATION_CODE]
	)
	VALUES
	(
		@sASSESSMENT_CODE,
		@sDESTINATION_CODE
	)
END
GO


IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_ASSESSMENT_DEST$DeleteRecord'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT_DEST$DeleteRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_ASSESSMENT_DEST$DeleteRecord]
	@sASSESSMENT_CODE VARCHAR(32),
	@sDESTINATION_CODE VARCHAR(64)
AS
BEGIN
	DELETE FROM [dbo].[DXDIR_ASSESSMENT_DESTINATION]
	WHERE ASSESSMENT_CODE = @sASSESSMENT_CODE
	AND DESTINATION_CODE = @sDESTINATION_CODE
END
GO