IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_RECENT_ASSESSMENT$InsertRecord'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_RECENT_ASSESSMENT$InsertRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_RECENT_ASSESSMENT$InsertRecord]
	@dcUSER_ID BIGINT,
	@sCODE VARCHAR(32),
	@daTIMESTAMP DATETIME
AS
BEGIN
	INSERT [dbo].[DXDIR_RECENT_ASSESSMENT]
	(
		[USER_ID],
		[CODE],
		[TIMESTAMP]
	)
	VALUES
	(
		@dcUSER_ID,
		@sCODE,
		@daTIMESTAMP
	)
END
GO


IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_RECENT_ASSESSMENT$UpdateRecord'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_RECENT_ASSESSMENT$UpdateRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_RECENT_ASSESSMENT$UpdateRecord]
	@dcUSER_ID BIGINT,
	@sCODE VARCHAR(32),
	@daTIMESTAMP DATETIME
AS
BEGIN
	UPDATE [dbo].[DXDIR_RECENT_ASSESSMENT]
	SET 
		[TIMESTAMP] = @daTIMESTAMP
	WHERE [USER_ID] = @dcUSER_ID
AND [CODE] = @sCODE
	
END
GO


IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_RECENT_ASSESSMENT$DeleteRecord'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_RECENT_ASSESSMENT$DeleteRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_RECENT_ASSESSMENT$DeleteRecord]
	@dcUSER_ID BIGINT,
	@sCODE VARCHAR(32)
AS
BEGIN
	DELETE FROM [dbo].[DXDIR_RECENT_ASSESSMENT]
	WHERE [USER_ID] = @dcUSER_ID
		AND [CODE] = @sCODE
END
GO

IF EXISTS (
		SELECT *
		FROM sys.objects so
		JOIN sys.schemas sc ON so.schema_id = sc.schema_id
		WHERE so.NAME = N'DXDIR_PK_RECENT_ASSESSMENT$UpdateList'
			AND sc.NAME = N'dbo'
			AND type IN (N'P')
		)
	DROP PROCEDURE [dbo].[DXDIR_PK_RECENT_ASSESSMENT$UpdateList]

GO


SET ANSI_NULLS ON

GO


SET QUOTED_IDENTIFIER ON

GO


CREATE PROCEDURE [dbo].[DXDIR_PK_RECENT_ASSESSMENT$UpdateList]
	 @dcUSER_ID BIGINT,
	 @dcMAX_COUNT BIGINT
AS
BEGIN
	WITH tList (
		CODE
		)
	AS (
		SELECT CODE
		FROM (
			SELECT 
				ROWNUM, 
				CODE
			FROM (
				SELECT ROW_NUMBER() OVER (
						ORDER BY TIMESTAMP DESC
						) AS ROWNUM
					,CODE
				FROM DXDIR_RECENT_ASSESSMENT
				WHERE USER_ID = @dcUSER_ID
				) A
			) B
		WHERE ROWNUM > @dcMAX_COUNT
		)
	DELETE
	FROM DXDIR_RECENT_ASSESSMENT
	FROM tList
	WHERE DXDIR_RECENT_ASSESSMENT.CODE = tList.CODE
END

GO