using Selerant.DevEx.Modules.DIRModule.ModuleBlocks._ThisProject;
using Selerant.DevEx.WebControls;
using Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models;
using Selerant.DevEx.WebMvcModules.Infrastructure.Controls;

namespace Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.DIRAdminTools.Models
{
    public class AssessmentTypeDialogModel : DialogViewIndexModel
    {
        #region Fields & Properties

        public bool IsEditMode { get; set; }
        public EditAssessmentTypeModel PropertiesModel { get; set; }

        #endregion

        #region Constructors

        public AssessmentTypeDialogModel(string controllerUrl, AdminToolControllerData controllerData)
            : base(controllerUrl, controllerData)
        {
        }

        #endregion

        #region Lifecycle

        protected override void InitializeForView()
        {
            base.InitializeForView();

            Resources.Add(new ControlJsFile(DIRLinks.Areas.DIRAdminTools.Views.AssessmentTypes.EditAssessmentTypeDialog_ts));
            Resources.Add(new ControlJsFile(DIRLinks.Areas.DIRAdminTools.Views.AssessmentTypes.EditAssessmentTypeDialog_css));
            JsType = "DX.DIRModule.DIRAdminTools.AssessmentTypes.EditAssessmentTypeDialog";
        }

        protected override void FillScriptControlDescriptor(GxScriptControlDescriptor scriptControlDescriptor)
        {
            base.FillScriptControlDescriptor(scriptControlDescriptor);
            scriptControlDescriptor.DomData.Add("editMode", IsEditMode);
            scriptControlDescriptor.DomData.Add("autogeneratestr", ResText.Global.GetString("AutoGenerated"));
            scriptControlDescriptor.DomData.Add("canEditCode", PropertiesModel.IsNewAssessmentType);
            scriptControlDescriptor.DomData.Add("isNew", PropertiesModel.IsNewAssessmentType);
        }

        #endregion
    }
}