use [devex_main_dir];
GO

PRINT 'Dropping external triggers...';
IF EXISTS (SELECT 1 FROM sys.objects WHERE type = 'TR' AND name = 'DXDIR_ASSESSMENT_FK2_DELETE_TR')
	DROP TRIGGER [dbo].[DXDIR_ASSESSMENT_FK2_DELETE_TR];
IF EXISTS (SELECT 1 FROM sys.objects WHERE type = 'TR' AND name = 'DXDIR_ASSESSMENT_FK4_DELETE_TR')
	DROP TRIGGER [dbo].[DXDIR_ASSESSMENT_FK4_DELETE_TR];
IF EXISTS (SELECT 1 FROM sys.objects WHERE type = 'TR' AND name = 'DXDIR_ASSESSMENT_FK5_DELETE_TR')
	DROP TRIGGER [dbo].[DXDIR_ASSESSMENT_FK5_DELETE_TR];
IF EXISTS (SELECT 1 FROM sys.objects WHERE type = 'TR' AND name = 'DXDIR_PARTNER_ASSESSMENT_FK2_DELETE_TR')
	DROP TRIGGER [dbo].[DXDIR_PARTNER_ASSESSMENT_FK2_DELETE_TR];
IF EXISTS (SELECT 1 FROM sys.objects WHERE type = 'TR' AND name = 'DX_RECENT_ASSESSMENT_FK1_DELETE_TR')
	DROP TRIGGER [dbo].[DX_RECENT_ASSESSMENT_FK1_DELETE_TR];
IF EXISTS (SELECT 1 FROM sys.objects WHERE type = 'TR' AND name = 'DXDIR_PARTNER_ASMT_TYPE_FK2_DELETE_TR')
	DROP TRIGGER [dbo].[DXDIR_PARTNER_ASMT_TYPE_FK2_DELETE_TR];
IF EXISTS (SELECT 1 FROM sys.objects WHERE type = 'TR' AND name = 'DXDIR_PARTNER_ASSESSMENT_FK2_DELETE_TR')
	DROP TRIGGER [dbo].[DXDIR_PARTNER_ASSESSMENT_FK2_DELETE_TR];
GO


DECLARE @artifactName VARCHAR(256),
		@artifactType CHAR(2),
        @sql NVARCHAR(500);
DECLARE @cursor CURSOR;


PRINT 'Dropping table constraints...';
SET @cursor = CURSOR FAST_FORWARD FOR
	SELECT DISTINCT 'ALTER TABLE [' + tc2.TABLE_SCHEMA + '].[' + tc2.TABLE_NAME + '] DROP [' + rc1.CONSTRAINT_NAME + '];'
	FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc1
	LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc2 ON tc2.CONSTRAINT_NAME = rc1.CONSTRAINT_NAME
	WHERE tc2.TABLE_NAME LIKE 'DXDIR%';

	OPEN @cursor;
	FETCH NEXT FROM @cursor INTO @sql;

	WHILE @@FETCH_STATUS = 0
	BEGIN
	EXEC sp_executesql @sql;
	FETCH NEXT FROM @cursor INTO @sql;
	END

CLOSE @cursor;
DEALLOCATE @cursor


PRINT 'Dropping procedures, scalar functions & tables...';
SET @cursor = CURSOR FAST_FORWARD FOR
	SELECT [name], [type] FROM sys.objects 
	WHERE type in ('U', 'P', 'FN') AND name LIKE 'DXDIR%'
	ORDER BY type ASC;

	OPEN @cursor;
	FETCH NEXT FROM @cursor INTO @artifactName, @artifactType;
	WHILE @@fetch_status = 0
	BEGIN
		IF @artifactType = 'P'
			EXEC ('DROP PROCEDURE [dbo].[' + @artifactName + ']');
		ELSE IF @artifactType = 'FN' -- drop SQL scalar function
			EXEC ('DROP FUNCTION [dbo].[' + @artifactName + ']');
		ELSE -- drop user table
			EXEC ('DROP TABLE [dbo].[' + @artifactName + ']');

		FETCH NEXT FROM @cursor INTO @artifactName, @artifactType;
	END;

CLOSE @cursor;
DEALLOCATE @cursor;


PRINT 'Dropping user defined types...';
SET @artifactName = NULL;
SET @cursor = CURSOR FAST_FORWARD
	FOR SELECT [name] FROM sys.types WHERE is_user_defined = 1 and name like 'DXDIR%';

	OPEN @cursor;
	FETCH next FROM @cursor INTO @artifactName;
	WHILE @@fetch_status = 0
	BEGIN
		EXEC ('DROP TYPE [dbo].[' + @artifactName + ']');
		FETCH next FROM @cursor INTO @artifactName;
	END;

CLOSE @cursor;
DEALLOCATE @cursor;


PRINT 'Dropping sequences...';
SET @artifactName = NULL;
SET @cursor = CURSOR FAST_FORWARD FOR
	SELECT name FROM sys.sequences WHERE name like 'DXDIR%';;

	OPEN @cursor;
	FETCH next FROM @cursor INTO @artifactName;
	WHILE @@fetch_status = 0
	BEGIN
		EXEC ('DROP SEQUENCE  [dbo].[' + @artifactName + ']');
		FETCH next FROM @cursor INTO @artifactName;
	END;

CLOSE @cursor;
DEALLOCATE @cursor;
GO


DELETE FROM DX_COMPONENT_CONTROLLER
WHERE ID in (319,320,321) or PARENT_ID in (319,320,321);

DELETE FROM DX_RECENT_MATERIAL;

-- Unit just in case cleanup
DELETE FROM DX_MATERIAL WHERE PLANT = 'UT_DIR_DUMMY';
DELETE FROM DX_PLANT WHERE CODE = 'UT_DIR_DUMMY';

DELETE FROM DX_ATTVALUE_MATERIAL
WHERE ID = 99510;
GO

-- Dropping created materials for DIR and their types
DELETE FROM DX_MATERIAL
WHERE MAT_TYPE in ('DIR_INPUT', 'DIR_OUTPUT', 'DIR_RESOURCE');
GO

DELETE FROM DX_MATERIAL_TYPE
WHERE CODE in ('DIR_INPUT', 'DIR_OUTPUT', 'DIR_RESOURCE');
GO

-- Dropping material types PHRASEs
-- TEXT: Material type
DELETE FROM DX_PHRASE_TEXT
WHERE TYPE = 11 and SUBTYPE = 'DX_MATERIAL.MAT_TYPE' and CODE in ('DIR_INPUT', 'DIR_OUTPUT', 'DIR_RESOURCE');

-- DEF: Material type
DELETE FROM DX_PHRASE_DEF
WHERE TYPE = 11 and SUBTYPE = 'DX_MATERIAL.MAT_TYPE' and CODE in ('DIR_INPUT', 'DIR_OUTPUT', 'DIR_RESOURCE');
GO



	-- DIR module specific PHRASES (delete all is safe)
	-- Define variable to hold all subtypes
	DECLARE @subtypes TABLE
	(
		[name] VARCHAR(128) COLLATE Latin1_General_CS_AS NOT NULL UNIQUE
	);
	INSERT INTO @subtypes VALUES
	('DXDIR_ASSESSMENT.STATUS'),
	('DXDIR_INPUT_CATEGORY.TYPE'),
	('DXDIR_ASSESSMENT.ORG_STRUCTURE'),
	('DXDIR_ASSESSMENT.PROD_CLASSIF'),
	('DXDIR_BUSINESS_COST.TITLE'),
	('DXDIR_RESULT.TITLE')
	;

	-- Delete all from PHRASE
	DELETE FROM DX_PHRASE_TEXT
	WHERE TYPE = 11 and SUBTYPE in (SELECT * FROM @subtypes);

	DELETE FROM DX_PHRASE_DEF
	WHERE TYPE = 11 and SUBTYPE in (SELECT * FROM @subtypes);

	DELETE FROM DX_PHRASE_TYPE
	WHERE TYPE = 11 and SUBTYPE in (SELECT * FROM @subtypes);
GO

DELETE FROM DX_PHRASE_TEXT
WHERE TYPE = 11 AND SUBTYPE = 'DX_ATTRIBUTE_DEF.SCOPE' AND CODE = 'ASSESSMENT';

DELETE FROM DX_PHRASE_DEF
WHERE TYPE = 11 AND SUBTYPE = 'DX_ATTRIBUTE_DEF.SCOPE' AND CODE = 'ASSESSMENT';

-- Attribute Phrases
DELETE FROM DX_PHRASE_TEXT
WHERE TYPE = 10 AND SUBTYPE = '0' AND CODE = '99510';

DELETE FROM DX_PHRASE_TEXT
WHERE TYPE = 10 AND SUBTYPE = '0' AND CODE = '99511';

DELETE FROM DX_PHRASE_TEXT
WHERE TYPE = 4 AND SUBTYPE = '99510' AND CODE IN ('FOOD', 'NONFOOD');

DELETE FROM DX_PHRASE_TEXT
WHERE TYPE = 4 AND SUBTYPE = '99511' AND CODE IN ('1', '2', '3');

DELETE FROM DX_PHRASE_DEF
WHERE TYPE = 10 AND SUBTYPE = '0' AND CODE = '99510';

DELETE FROM DX_PHRASE_DEF
WHERE TYPE = 10 AND SUBTYPE = '0' AND CODE = '99511';

DELETE FROM DX_PHRASE_DEF
WHERE TYPE = 4 AND SUBTYPE = '99510' AND CODE IN ('FOOD', 'NONFOOD');

DELETE FROM DX_PHRASE_DEF
WHERE TYPE = 4 AND SUBTYPE = '99511' AND CODE IN ('1', '2', '3');

DELETE FROM DX_PHRASE_TYPE
WHERE TYPE = 4 AND SUBTYPE = '99510';

DELETE FROM DX_PHRASE_TYPE
WHERE TYPE = 4 AND SUBTYPE = '99511';

-- DXDIR_ASSESSMENT_COMMENT, DXDIR_RESOURCE_TYPE, DXDIR_DATA_QUALITY
DELETE FROM DX_ATTRIBUTE_DEF
WHERE ID IN (99500, 99510, 99511);
GO

PRINT 'Deleting DIR module info';
DELETE FROM DX_MODULE_INFO
WHERE CODE = 'DIR';
GO