//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.FILES_TO_COPY.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DIR_AdminTools {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DIR_AdminTools() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.FILES_TO_COPY.Resources.DIR_Admin" +
                            "Tools", typeof(DIR_AdminTools).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string ATActivate {
            get {
                return ResourceManager.GetString("ATActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Assessment Type.
        /// </summary>
        internal static string ATActivateTT {
            get {
                return ResourceManager.GetString("ATActivateTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string ATAssessmentTypes_Active {
            get {
                return ResourceManager.GetString("ATAssessmentTypes_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string ATAssessmentTypes_Code {
            get {
                return ResourceManager.GetString("ATAssessmentTypes_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ATAssessmentTypes_Description {
            get {
                return ResourceManager.GetString("ATAssessmentTypes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Types.
        /// </summary>
        internal static string ATAssessmentTypesTitle {
            get {
                return ResourceManager.GetString("ATAssessmentTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Types.
        /// </summary>
        internal static string ATAssessmentTypesTT {
            get {
                return ResourceManager.GetString("ATAssessmentTypesTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string ATDeactivate {
            get {
                return ResourceManager.GetString("ATDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIRECT Tool Management.
        /// </summary>
        internal static string ATDIRToolManagement {
            get {
                return ResourceManager.GetString("ATDIRToolManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string GridActionsColumn {
            get {
                return ResourceManager.GetString("GridActionsColumn", resourceCulture);
            }
        }
    }
}
