IF EXISTS (
		SELECT 1
		FROM dbo.sysobjects
		WHERE id = object_id(N'dbo.DXDIR_PK_RESULTCALCULATIONS$GetSumBusinessCost')
			AND OBJECTPROPERTY(id, N'IsScalarFunction') = 1
		)
	DROP FUNCTION [dbo].[DXDIR_PK_RESULTCALCULATIONS$GetSumBusinessCost]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (
		SELECT 1
		FROM dbo.sysobjects
		WHERE id = object_id(N'dbo.DXDIR_PK_RESULTCALCULATIONS$GetCostElectricity')
			AND OBJECTPROPERTY(id, N'IsScalarFunction') = 1
		)
	DROP FUNCTION [dbo].[DXDIR_PK_RESULTCALCULATIONS$GetCostElectricity]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_RESULTCALCULATIONS$GetTotalAndElectricityCost'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_RESULTCALCULATIONS$GetTotalAndElectricityCost]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/* Total and Electricity cost */
CREATE PROCEDURE [dbo].[DXDIR_PK_RESULTCALCULATIONS$GetTotalAndElectricityCost]
	@sASSESSMENT_CODE			VARCHAR(32),
	@dcASSESSMENT_LC_STAGE_ID	BIGINT,
	@dcTOTAL_COST				NUMERIC(26, 4) OUTPUT,
	@dcELECTRICITY_COST			NUMERIC(26, 4) OUTPUT
AS
BEGIN
	DECLARE @tableBusinessCost TABLE (
			   ID BIGINT NOT NULL,
			   ASSESSMENT_CODE VARCHAR(32) NOT NULL,
			   ASSESSMENT_LC_STAGE_ID BIGINT NOT NULL,
			   TYPE VARCHAR(24),
			   TITLE NVARCHAR(256) COLLATE Latin1_General_CS_AS NOT NULL,
			   SORT_ORDER INT,
			   COST NUMERIC(24, 4),
			   TOTAL_COST NUMERIC(25, 4),
			   CARRIED_COST NUMERIC(25, 4),
			   WASTE_COST NUMERIC(25, 4));

	INSERT INTO @tableBusinessCost EXEC [dbo].[DXDIR_PK_BUSINESS_COST$GetCarriedOverBusinessCosts] @sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID;

	SELECT @dcTOTAL_COST = ISNULL(SUM(TOTAL_COST, 0))
	FROM @tableBusinessCost;

	SELECT @dcELECTRICITY_COST = ISNULL(SUM(TOTAL_COST, 0))
	FROM @tableBusinessCost
	WHERE TITLE IN ('ELECTRICITY', 'GAS');
END
GO

/* Energy spend as % of operating costs*/
IF EXISTS (
		SELECT 1
		FROM dbo.sysobjects
		WHERE id = object_id(N'dbo.DXDIR_PK_RESULTCALCULATIONS$GetEnergyCost')
			AND OBJECTPROPERTY(id, N'IsScalarFunction') = 1
		)
	DROP FUNCTION [dbo].[DXDIR_PK_RESULTCALCULATIONS$GetEnergyCost]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[DXDIR_PK_RESULTCALCULATIONS$GetEnergyCost]
(
	@sASSESSMENT_CODE			VARCHAR(32),
	@dcASSESSMENT_LC_STAGE_ID	BIGINT,
	@dcELECTRICITY_COST			NUMERIC(26, 8),
	@dcTOTAL_COST				NUMERIC(25, 4)
)
RETURNS NUMERIC(26, 12) 
AS
BEGIN
	DECLARE @sumWaste NUMERIC(25, 4) = dbo.DXDIR_PK_RESULTCALCULATIONS$WasteCollectionTreatment(@sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID),
			@sumCostInput NUMERIC(25, 4) = dbo.DXDIR_PK_RESULTCALCULATIONS$GetSumCostInput(@sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID);
				
	IF @dcTOTAL_COST = 0 AND @sumWaste = 0 AND @sumCostInput = 0
	BEGIN
		RETURN 0;
	END

	RETURN @dcELECTRICITY_COST / (@sumWaste + @dcTOTAL_COST + @sumCostInput);
END
GO


/* Material spend as % of operating cost*/
IF EXISTS (
		SELECT 1
		FROM dbo.sysobjects
		WHERE id = object_id(N'dbo.DXDIR_PK_RESULTCALCULATIONS$GetMaterialSpend')
			AND OBJECTPROPERTY(id, N'IsScalarFunction') = 1
		)
	DROP FUNCTION [dbo].[DXDIR_PK_RESULTCALCULATIONS$GetMaterialSpend]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[DXDIR_PK_RESULTCALCULATIONS$GetMaterialSpend]
(
	@dcAssessmentCode	VARCHAR(32),
	@dcLCStage			BIGINT,
	@dcTOTAL_COST		NUMERIC(25, 4)
)
RETURNS NUMERIC(26, 12) 
AS
BEGIN
	DECLARE @sumCostInput NUMERIC(25, 4) = dbo.DXDIR_PK_RESULTCALCULATIONS$GetSumCostInput(@dcAssessmentCode, @dcLCStage),
			@sumWaste NUMERIC(25, 4) = dbo.DXDIR_PK_RESULTCALCULATIONS$WasteCollectionTreatment(@dcAssessmentCode, @dcLCStage);

	IF @sumWaste = 0 AND @dcTOTAL_COST = 0 AND @sumCostInput = 0
	BEGIN
		RETURN 0;
	END

	RETURN @sumCostInput / (@sumWaste + @dcTOTAL_COST + @sumCostInput);
END
GO

/*Results grid*/
IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_RESULTCALCULATIONS$GetResultsTable'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_RESULTCALCULATIONS$GetResultsTable]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_RESULTCALCULATIONS$GetResultsTable]
	@sASSESSMENT_CODE VARCHAR(32),
	@dcASSESSMENT_LC_STAGE_ID BIGINT
AS
BEGIN
	DECLARE	@sumTotalCost NUMERIC(26, 4) = 0,
			@sumElectricityTotalCost NUMERIC(26, 4) = 0;

	DECLARE @resultsTable TABLE (
			   ROW_ID BIGINT NOT NULL PRIMARY KEY,
			   RESULT NUMERIC(26, 12)
			 );

	DECLARE @estimatedTrueCostOfWaste NUMERIC(26, 12);

	EXEC [dbo].[DXDIR_PK_RESULTCALCULATIONS$EstimatedCostOfWaste] @sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID, @estimatedTrueCostOfWaste OUTPUT;
	EXEC [dbo].[DXDIR_PK_RESULTCALCULATIONS$GetTotalAndElectricityCost] @sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID, @sumTotalCost OUTPUT, @sumElectricityTotalCost OUTPUT;

	INSERT INTO @resultsTable (ROW_ID, RESULT)
	SELECT  1,
			dbo.DXDIR_PK_RESULTCALCULATIONS$GetUtilisedInput(@sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID) * 100
	UNION ALL
	SELECT 2,
			dbo.DXDIR_PK_RESULTCALCULATIONS$GetStockHolding(@sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID) * 100
	UNION ALL
	SELECT 3,
			dbo.DXDIR_PK_RESULTCALCULATIONS$GetFoodMaterialLoss(@sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID) * 100
	UNION ALL
	SELECT 4,
			dbo.DXDIR_PK_RESULTCALCULATIONS$GetEdibleFoodMatLoss(@sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID) * 100
	UNION ALL
	SELECT 5,
			dbo.DXDIR_PK_RESULTCALCULATIONS$GetEdibleMatLossToMatLoss(@sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID) * 100
	UNION ALL
	SELECT 6,
			dbo.DXDIR_PK_RESULTCALCULATIONS$GetMatLossToInputExWater(@sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID) * 100
	UNION ALL
	SELECT 7,
			dbo.DXDIR_PK_RESULTCALCULATIONS$GetPackgLossToFoodInput(@sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID) * 100
	UNION ALL
	SELECT 8,
			dbo.DXDIR_PK_RESULTCALCULATIONS$GetPackToGrossProduct(@sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID) * 100
	UNION ALL
	SELECT 9,
			@estimatedTrueCostOfWaste	
	UNION ALL
	SELECT 10,
			dbo.DXDIR_PK_RESULTCALCULATIONS$WasteCollectionTreatment(@sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID)
	UNION ALL
	SELECT 11,
			dbo.DXDIR_PK_RESULTCALCULATIONS$GetEnergyCost(@sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID, @sumElectricityTotalCost, @sumTotalCost) * 100
	UNION ALL
	SELECT 12,
			dbo.DXDIR_PK_RESULTCALCULATIONS$GetMaterialSpend(@sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID, @sumTotalCost) * 100
	UNION ALL
	SELECT 13,
			dbo.DXDIR_PK_RESULTCALCULATIONS$DisposalToPurchase(@sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID) * 100
	UNION ALL 
	SELECT 14,
			dbo.DXDIR_PK_RESULTCALCULATIONS$EstimatedWasteToPurchase(@sASSESSMENT_CODE, @dcASSESSMENT_LC_STAGE_ID, @estimatedTrueCostOfWaste) * 100;

	SELECT DXDIR_RESULT_ROW.ID,
		   DXDIR_RESULT_ROW.TITLE,
		   DXDIR_RESULT_ROW.RESULT_UOM,
		   DXDIR_RESULT_ROW.RESULT_TYPE,
		   DXDIR_RESULT_ROW.SORT_ORDER,
		   RESULT 
	FROM @resultsTable AS RESULT_TAB
		 INNER JOIN DXDIR_RESULT_ROW 
		 ON RESULT_TAB.ROW_ID = DXDIR_RESULT_ROW.ID;
END
GO

IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_RESULTCALCULATIONS$GetFoodLossesNotIncIndblParts'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_RESULTCALCULATIONS$GetFoodLossesNotIncIndblParts]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_RESULTCALCULATIONS$GetFoodLossesNotIncIndblParts]
	@sASSESSMENT_CODE		  VARCHAR(32),
	@dcASSESSMENT_LC_STAGE_ID BIGINT
AS
BEGIN
	SELECT ISNULL(WEIGHT, 0) AS WEIGHT,
		   D.CODE AS CODE,
		   0 AS WASTE,
		   0 AS SORT_ORDER,
		   0 AS USED_ON,
		   D.TITLE
	FROM DXDIR_OUTPUT O
		 JOIN DXDIR_OUTPUT_CATEGORY OC
		 ON OC.ID = O.OUTPUT_CATEGORY_ID
		 JOIN DXDIR_DESTINATION D
		 ON O.DESTINATION_CODE	 = D.CODE
	WHERE ASSESSMENT_CODE				 = @sASSESSMENT_CODE AND 
		  ASSESSMENT_LC_STAGE_ID		 = @dcASSESSMENT_LC_STAGE_ID AND 
		  OUTPUT_CATEGORY_ID			 IN (2, 3)
	UNION 
	SELECT ISNULL(SUM(WEIGHT), 0) AS WEIGHT,
		   D.CODE AS CODE,
		   0 AS WASTE,
		   0 AS SORT_ORDER,
		   0 AS USED_ON,
		   D.TITLE
	FROM DXDIR_OUTPUT O
		 JOIN DXDIR_DESTINATION D
		 ON O.DESTINATION_CODE	 = D.CODE
		 JOIN DXDIR_OUTPUT_CATEGORY OC
		 ON OC.ID				 = O.OUTPUT_CATEGORY_ID
	WHERE ASSESSMENT_CODE			 = @sASSESSMENT_CODE AND
		  ASSESSMENT_LC_STAGE_ID	 = @dcASSESSMENT_LC_STAGE_ID AND 
		  OC.TYPE					 = 'FOOD'
	GROUP BY D.CODE, D.TITLE;
END
GO

IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_RESULTCALCULATIONS$GetFoodLossesInediblePartsOnly'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_RESULTCALCULATIONS$GetFoodLossesInediblePartsOnly]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_RESULTCALCULATIONS$GetFoodLossesInediblePartsOnly]
	@sASSESSMENT_CODE		  VARCHAR(32),
	@dcASSESSMENT_LC_STAGE_ID BIGINT
AS
BEGIN
	SELECT ISNULL(SUM(WEIGHT), 0) AS WEIGHT,
		   D.CODE AS CODE,
		   0 AS WASTE,
		   0 AS SORT_ORDER,
		   0 AS USED_ON,
		   D.TITLE
	FROM DXDIR_OUTPUT O
		 JOIN DXDIR_DESTINATION D
			ON O.DESTINATION_CODE = D.CODE
		 JOIN DXDIR_OUTPUT_CATEGORY OC
			ON OC.ID = O.OUTPUT_CATEGORY_ID
	WHERE O.ASSESSMENT_CODE			 = @sASSESSMENT_CODE				AND
		  O.ASSESSMENT_LC_STAGE_ID	 = @dcASSESSMENT_LC_STAGE_ID		AND 
		  O.OUTPUT_CATEGORY_ID		 = 5
	GROUP BY D.CODE, D.TITLE;
END
GO