IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_OUTPUT_GRIDITEM$GetOutputGridItems'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_OUTPUT_GRIDITEM$GetOutputGridItems]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_OUTPUT_GRIDITEM$GetOutputGridItems]
	@sASSESSMENT_CODE VARCHAR(32),
	@dcASSESSMENT_LC_STAGE_ID BIGINT
AS
BEGIN
	SELECT 
		O.ID, 
		O.OUTPUT_CATEGORY_ID,
		OC.TITLE AS OUTPUT_CATEGORY_TITLE,
		OC.TYPE AS OUTPUT_CATEGORY_TYPE,
		O.DESTINATION_CODE,
		D.TITLE AS DESTINATION_TITLE,
		O.OUTPUT_COST, 
		O.INCOME
	FROM DXDIR_OUTPUT O 
	JOIN DXDIR_OUTPUT_CATEGORY OC
	ON O.OUTPUT_CATEGORY_ID = OC.ID
	LEFT JOIN DXDIR_DESTINATION D
	ON O.DESTINATION_CODE = D.CODE
	WHERE O.ASSESSMENT_CODE = @sASSESSMENT_CODE AND
		  O.ASSESSMENT_LC_STAGE_ID = @dcASSESSMENT_LC_STAGE_ID AND
		  O.INPUT_ID IS NULL
	ORDER BY OC.SORT_ORDER, O.SORT_ORDER;
END
GO