IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_PARTNER_ASMT_TYPE$InsertRecord'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_PARTNER_ASMT_TYPE$InsertRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_PARTNER_ASMT_TYPE$InsertRecord]
	@sASSESSMENT_TYPE_CODE VARCHAR(32),
	@sPARTNER_ORG_CODE VARCHAR(20),
	@dcIS_SHARED NUMERIC(1,0)
AS
BEGIN
	INSERT [dbo].[DXDIR_PARTNER_ASSESSMENT_TYPE]
	(
		[ASSESSMENT_TYPE_CODE],
		[PARTNER_ORG_CODE],
		[IS_SHARED]
	)
	VALUES
	(
		@sASSESSMENT_TYPE_CODE,
		@sPARTNER_ORG_CODE,
		@dcIS_SHARED
	)
END
GO


IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_PARTNER_ASMT_TYPE$UpdateRecord'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_PARTNER_ASMT_TYPE$UpdateRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_PARTNER_ASMT_TYPE$UpdateRecord]
	@sASSESSMENT_TYPE_CODE VARCHAR(32),
	@sPARTNER_ORG_CODE VARCHAR(20),
	@dcIS_SHARED NUMERIC(1,0)
AS
BEGIN
	UPDATE [dbo].[DXDIR_PARTNER_ASSESSMENT_TYPE]
	SET 
		[IS_SHARED] = @dcIS_SHARED
	WHERE [ASSESSMENT_TYPE_CODE] = @sASSESSMENT_TYPE_CODE
AND [PARTNER_ORG_CODE] = @sPARTNER_ORG_CODE
	
END
GO


IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_PARTNER_ASMT_TYPE$DeleteRecord'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_PARTNER_ASMT_TYPE$DeleteRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_PARTNER_ASMT_TYPE$DeleteRecord]
	@sASSESSMENT_TYPE_CODE VARCHAR(32),
	@sPARTNER_ORG_CODE VARCHAR(20)
AS
BEGIN
	DELETE FROM [dbo].[DXDIR_PARTNER_ASSESSMENT_TYPE]
	WHERE [ASSESSMENT_TYPE_CODE] = @sASSESSMENT_TYPE_CODE
		AND [PARTNER_ORG_CODE] = @sPARTNER_ORG_CODE
END
GO

