IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_RESOURCE_NOTE$InsertRecord'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_RESOURCE_NOTE$InsertRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_RESOURCE_NOTE$InsertRecord]
	@sASSESSMENT_CODE VARCHAR(32),
	@dcLC_STAGE_ID NUMERIC(11),
	@sTYPE VARCHAR(32),
	@sNOTE VARCHAR(2000)
AS
BEGIN
	INSERT [dbo].[DXDIR_RESOURCE_NOTE]
	(
		[ASSESSMENT_CODE],
		[LC_STAGE_ID],
		[TYPE],
		[NOTE]
	)
	VALUES
	(
		@sASSESSMENT_CODE,
		@dcLC_STAGE_ID,
		@sTYPE,
		@sNOTE
	)
END
GO

IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_RESOURCE_NOTE$UpdateRecord'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_RESOURCE_NOTE$UpdateRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_RESOURCE_NOTE$UpdateRecord]
	@sASSESSMENT_CODE VARCHAR(32),
	@dcLC_STAGE_ID NUMERIC(11),
	@sTYPE VARCHAR(32),
	@sNOTE VARCHAR(2000)
AS
BEGIN
	UPDATE [dbo].[DXDIR_RESOURCE_NOTE]
	SET 
		[NOTE] = @sNOTE
	WHERE [ASSESSMENT_CODE] = @sASSESSMENT_CODE
	AND [LC_STAGE_ID] = @dcLC_STAGE_ID
	AND [TYPE] = @sTYPE
END
GO


IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_RESOURCE_NOTE$DeleteRecord'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_RESOURCE_NOTE$DeleteRecord]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_RESOURCE_NOTE$DeleteRecord]
	@sASSESSMENT_CODE VARCHAR(32)
	,@dcLC_STAGE_ID NUMERIC
	,@sTYPE VARCHAR(32)
AS
BEGIN
	DELETE FROM [dbo].[DXDIR_RESOURCE_NOTE]
	WHERE ASSESSMENT_CODE = @sASSESSMENT_CODE
	AND LC_STAGE_ID = @dcLC_STAGE_ID
	AND TYPE = @sTYPE
END
GO
