// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using Autofac;
using Selerant.DevEx.Infrastructure;
using Selerant.Infrastructure.DependencyContainer;
using T4MVC_DIR;
using Selerant.DevEx.Modules.DIRModule.ModuleBlocks._ThisProject;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd._ThisProject;
using Selerant.DevEx.Infrastructure.Modules;
namespace Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult Index()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult IndexEdit()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.IndexEdit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult ManageAssessmentRaiseDialog()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.ManageAssessmentRaiseDialog);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetIndexEditDialog()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIndexEditDialog);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetIndexInitialDialog()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIndexInitialDialog);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult LoadOnDemandPanel()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.LoadOnDemandPanel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult _OnHeaderMenuItemClick()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._OnHeaderMenuItemClick);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.AjaxResult ChangePanelIsOpenSettings()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult(Area, Name, ActionNames.ChangePanelIsOpenSettings);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.AjaxResult ReorderPanel()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult(Area, Name, ActionNames.ReorderPanel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.AjaxResult ReorderPanels()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult(Area, Name, ActionNames.ReorderPanels);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.AjaxResult CollapseExpandBookmarks()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult(Area, Name, ActionNames.CollapseExpandBookmarks);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DefaultExecuteMenuButtonCheckPhrasesConsistencyDialog()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DefaultExecuteMenuButtonCheckPhrasesConsistencyDialog);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ExecuteCustomEventHandler()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExecuteCustomEventHandler);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult AddTag()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.AddTag);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult RemoveTag()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.RemoveTag);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult<Selerant.DevEx.WebPages.OpenDialogSettings.Data> GetOpenDialogSettings()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data(Area, Name, ActionNames.GetOpenDialogSettings);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC_DIR.AssessmentNavigator.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "AssessmentNavigator";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string IndexEdit = "IndexEdit";
            public readonly string ManageAssessmentRaiseDialog = "ManageAssessmentRaiseDialog";
            public readonly string GetIndexEditDialog = "GetIndexEditDialog";
            public readonly string GetIndexInitialDialog = "GetIndexInitialDialog";
            public readonly string LoadOnDemandPanel = "LoadOnDemandPanel";
            public readonly string _OnHeaderMenuItemClick = "_OnHeaderMenuItemClick";
            public readonly string ChangePanelIsOpenSettings = "ChangePanelIsOpenSettings";
            public readonly string ReorderPanel = "ReorderPanel";
            public readonly string ReorderPanels = "ReorderPanels";
            public readonly string CollapseExpandBookmarks = "CollapseExpandBookmarks";
            public readonly string DefaultExecuteMenuButtonCheckPhrasesConsistencyDialog = "DefaultExecuteMenuButtonCheckPhrasesConsistencyDialog";
            public readonly string ExecuteCustomEventHandler = "ExecuteCustomEventHandler";
            public readonly string AddTag = "AddTag";
            public readonly string RemoveTag = "RemoveTag";
            public readonly string GetOpenDialogSettings = "GetOpenDialogSettings";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string IndexEdit = "IndexEdit";
            public const string ManageAssessmentRaiseDialog = "ManageAssessmentRaiseDialog";
            public const string GetIndexEditDialog = "GetIndexEditDialog";
            public const string GetIndexInitialDialog = "GetIndexInitialDialog";
            public const string LoadOnDemandPanel = "LoadOnDemandPanel";
            public const string _OnHeaderMenuItemClick = "_OnHeaderMenuItemClick";
            public const string ChangePanelIsOpenSettings = "ChangePanelIsOpenSettings";
            public const string ReorderPanel = "ReorderPanel";
            public const string ReorderPanels = "ReorderPanels";
            public const string CollapseExpandBookmarks = "CollapseExpandBookmarks";
            public const string DefaultExecuteMenuButtonCheckPhrasesConsistencyDialog = "DefaultExecuteMenuButtonCheckPhrasesConsistencyDialog";
            public const string ExecuteCustomEventHandler = "ExecuteCustomEventHandler";
            public const string AddTag = "AddTag";
            public const string RemoveTag = "RemoveTag";
            public const string GetOpenDialogSettings = "GetOpenDialogSettings";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string code = "code";
            public readonly string layout = "layout";
        }
        static readonly ActionParamsClass_IndexEdit s_params_IndexEdit = new ActionParamsClass_IndexEdit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IndexEdit IndexEditParams { get { return s_params_IndexEdit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IndexEdit
        {
            public readonly string id = "id";
            public readonly string panelID = "panelID";
            public readonly string customParams = "customParams";
            public readonly string isCreating = "isCreating";
            public readonly string saveOnCancel = "saveOnCancel";
        }
        static readonly ActionParamsClass_ManageAssessmentRaiseDialog s_params_ManageAssessmentRaiseDialog = new ActionParamsClass_ManageAssessmentRaiseDialog();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ManageAssessmentRaiseDialog ManageAssessmentRaiseDialogParams { get { return s_params_ManageAssessmentRaiseDialog; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ManageAssessmentRaiseDialog
        {
            public readonly string controllerData = "controllerData";
            public readonly string entityType = "entityType";
        }
        static readonly ActionParamsClass_GetIndexEditDialog s_params_GetIndexEditDialog = new ActionParamsClass_GetIndexEditDialog();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetIndexEditDialog GetIndexEditDialogParams { get { return s_params_GetIndexEditDialog; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetIndexEditDialog
        {
            public readonly string controllerData = "controllerData";
            public readonly string panelID = "panelID";
            public readonly string customParams = "customParams";
        }
        static readonly ActionParamsClass_GetIndexInitialDialog s_params_GetIndexInitialDialog = new ActionParamsClass_GetIndexInitialDialog();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetIndexInitialDialog GetIndexInitialDialogParams { get { return s_params_GetIndexInitialDialog; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetIndexInitialDialog
        {
            public readonly string controllerData = "controllerData";
            public readonly string panelID = "panelID";
        }
        static readonly ActionParamsClass_LoadOnDemandPanel s_params_LoadOnDemandPanel = new ActionParamsClass_LoadOnDemandPanel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LoadOnDemandPanel LoadOnDemandPanelParams { get { return s_params_LoadOnDemandPanel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LoadOnDemandPanel
        {
            public readonly string controllerData = "controllerData";
            public readonly string nodeId = "nodeId";
            public readonly string customParams = "customParams";
        }
        static readonly ActionParamsClass__OnHeaderMenuItemClick s_params__OnHeaderMenuItemClick = new ActionParamsClass__OnHeaderMenuItemClick();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass__OnHeaderMenuItemClick _OnHeaderMenuItemClickParams { get { return s_params__OnHeaderMenuItemClick; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass__OnHeaderMenuItemClick
        {
            public readonly string controllerData = "controllerData";
            public readonly string param = "param";
        }
        static readonly ActionParamsClass_ChangePanelIsOpenSettings s_params_ChangePanelIsOpenSettings = new ActionParamsClass_ChangePanelIsOpenSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangePanelIsOpenSettings ChangePanelIsOpenSettingsParams { get { return s_params_ChangePanelIsOpenSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangePanelIsOpenSettings
        {
            public readonly string controllerData = "controllerData";
            public readonly string nodeId = "nodeId";
            public readonly string isOpen = "isOpen";
        }
        static readonly ActionParamsClass_ReorderPanel s_params_ReorderPanel = new ActionParamsClass_ReorderPanel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReorderPanel ReorderPanelParams { get { return s_params_ReorderPanel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReorderPanel
        {
            public readonly string controllerData = "controllerData";
            public readonly string newIndex = "newIndex";
            public readonly string nodeId = "nodeId";
        }
        static readonly ActionParamsClass_ReorderPanels s_params_ReorderPanels = new ActionParamsClass_ReorderPanels();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReorderPanels ReorderPanelsParams { get { return s_params_ReorderPanels; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReorderPanels
        {
            public readonly string controllerData = "controllerData";
            public readonly string nodeIds = "nodeIds";
        }
        static readonly ActionParamsClass_CollapseExpandBookmarks s_params_CollapseExpandBookmarks = new ActionParamsClass_CollapseExpandBookmarks();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CollapseExpandBookmarks CollapseExpandBookmarksParams { get { return s_params_CollapseExpandBookmarks; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CollapseExpandBookmarks
        {
            public readonly string controllerData = "controllerData";
            public readonly string isCollapsed = "isCollapsed";
        }
        static readonly ActionParamsClass_DefaultExecuteMenuButtonCheckPhrasesConsistencyDialog s_params_DefaultExecuteMenuButtonCheckPhrasesConsistencyDialog = new ActionParamsClass_DefaultExecuteMenuButtonCheckPhrasesConsistencyDialog();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DefaultExecuteMenuButtonCheckPhrasesConsistencyDialog DefaultExecuteMenuButtonCheckPhrasesConsistencyDialogParams { get { return s_params_DefaultExecuteMenuButtonCheckPhrasesConsistencyDialog; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DefaultExecuteMenuButtonCheckPhrasesConsistencyDialog
        {
            public readonly string controllerData = "controllerData";
        }
        static readonly ActionParamsClass_ExecuteCustomEventHandler s_params_ExecuteCustomEventHandler = new ActionParamsClass_ExecuteCustomEventHandler();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExecuteCustomEventHandler ExecuteCustomEventHandlerParams { get { return s_params_ExecuteCustomEventHandler; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExecuteCustomEventHandler
        {
            public readonly string controllerData = "controllerData";
            public readonly string transactionId = "transactionId";
            public readonly string buttonId = "buttonId";
        }
        static readonly ActionParamsClass_AddTag s_params_AddTag = new ActionParamsClass_AddTag();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddTag AddTagParams { get { return s_params_AddTag; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddTag
        {
            public readonly string controllerData = "controllerData";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_RemoveTag s_params_RemoveTag = new ActionParamsClass_RemoveTag();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoveTag RemoveTagParams { get { return s_params_RemoveTag; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoveTag
        {
            public readonly string controllerData = "controllerData";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetOpenDialogSettings s_params_GetOpenDialogSettings = new ActionParamsClass_GetOpenDialogSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOpenDialogSettings GetOpenDialogSettingsParams { get { return s_params_GetOpenDialogSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOpenDialogSettings
        {
            public readonly string originalActionName = "originalActionName";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Header = "Header";
                public readonly string Index = "Index";
                public readonly string Index_ts = "Index_ts";
                public readonly string IndexEdit = "IndexEdit";
                public readonly string IndexEdit_ts = "IndexEdit_ts";
            }
            public readonly string Header = "~/Areas/AssessmentNavigator/Views/Home/Header.cshtml";
            public readonly string Index = "~/Areas/AssessmentNavigator/Views/Home/Index.cshtml";
            public readonly string Index_ts = "~/Areas/AssessmentNavigator/Views/Home/Index.ts";
            public readonly string IndexEdit = "~/Areas/AssessmentNavigator/Views/Home/IndexEdit.cshtml";
            public readonly string IndexEdit_ts = "~/Areas/AssessmentNavigator/Views/Home/IndexEdit.ts";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HomeController : Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.HomeController
    {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, string code, string layout);

        [NonAction]
        public override System.Web.Mvc.ViewResult Index(string code, string layout)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "code", code);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "layout", layout);
            IndexOverride(callInfo, code, layout);
            return callInfo;
        }

        [NonAction]
        partial void IndexEditOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, string id, string panelID, string customParams, bool isCreating, bool saveOnCancel);

        [NonAction]
        public override System.Web.Mvc.ViewResult IndexEdit(string id, string panelID, string customParams, bool isCreating, bool saveOnCancel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.IndexEdit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "panelID", panelID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "customParams", customParams);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isCreating", isCreating);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "saveOnCancel", saveOnCancel);
            IndexEditOverride(callInfo, id, panelID, customParams, isCreating, saveOnCancel);
            return callInfo;
        }

        [NonAction]
        partial void ManageAssessmentRaiseDialogOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Models.Dialogs.ManageAssessment.EntityType entityType);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult ManageAssessmentRaiseDialog(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Models.Dialogs.ManageAssessment.EntityType entityType)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.ManageAssessmentRaiseDialog);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "entityType", entityType);
            ManageAssessmentRaiseDialogOverride(callInfo, controllerData, entityType);
            return callInfo;
        }

        [NonAction]
        partial void GetIndexEditDialogOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string panelID, string customParams);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetIndexEditDialog(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string panelID, string customParams)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIndexEditDialog);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "panelID", panelID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "customParams", customParams);
            GetIndexEditDialogOverride(callInfo, controllerData, panelID, customParams);
            return callInfo;
        }

        [NonAction]
        partial void GetIndexInitialDialogOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string panelID);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetIndexInitialDialog(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string panelID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIndexInitialDialog);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "panelID", panelID);
            GetIndexInitialDialogOverride(callInfo, controllerData, panelID);
            return callInfo;
        }

        [NonAction]
        partial void LoadOnDemandPanelOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string nodeId, string customParams);

        [NonAction]
        public override System.Web.Mvc.ViewResult LoadOnDemandPanel(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string nodeId, string customParams)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.LoadOnDemandPanel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nodeId", nodeId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "customParams", customParams);
            LoadOnDemandPanelOverride(callInfo, controllerData, nodeId, customParams);
            return callInfo;
        }

        [NonAction]
        partial void _OnHeaderMenuItemClickOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, Selerant.DevEx.WebMvcModules.Helpers.HtmlMenuItemClickEventArgs param);

        [NonAction]
        public override System.Web.Mvc.ActionResult _OnHeaderMenuItemClick(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, Selerant.DevEx.WebMvcModules.Helpers.HtmlMenuItemClickEventArgs param)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames._OnHeaderMenuItemClick);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "param", param);
            _OnHeaderMenuItemClickOverride(callInfo, controllerData, param);
            return callInfo;
        }

        [NonAction]
        partial void ChangePanelIsOpenSettingsOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string nodeId, bool isOpen);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.AjaxResult ChangePanelIsOpenSettings(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string nodeId, bool isOpen)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult(Area, Name, ActionNames.ChangePanelIsOpenSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nodeId", nodeId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isOpen", isOpen);
            ChangePanelIsOpenSettingsOverride(callInfo, controllerData, nodeId, isOpen);
            return callInfo;
        }

        [NonAction]
        partial void ReorderPanelOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, int newIndex, string nodeId);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.AjaxResult ReorderPanel(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, int newIndex, string nodeId)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult(Area, Name, ActionNames.ReorderPanel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "newIndex", newIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nodeId", nodeId);
            ReorderPanelOverride(callInfo, controllerData, newIndex, nodeId);
            return callInfo;
        }

        [NonAction]
        partial void ReorderPanelsOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string[] nodeIds);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.AjaxResult ReorderPanels(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string[] nodeIds)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult(Area, Name, ActionNames.ReorderPanels);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nodeIds", nodeIds);
            ReorderPanelsOverride(callInfo, controllerData, nodeIds);
            return callInfo;
        }

        [NonAction]
        partial void CollapseExpandBookmarksOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, bool isCollapsed);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.AjaxResult CollapseExpandBookmarks(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, bool isCollapsed)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult(Area, Name, ActionNames.CollapseExpandBookmarks);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isCollapsed", isCollapsed);
            CollapseExpandBookmarksOverride(callInfo, controllerData, isCollapsed);
            return callInfo;
        }

        [NonAction]
        partial void DefaultExecuteMenuButtonCheckPhrasesConsistencyDialogOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.BusinessLayer.DxSpecification> controllerData);

        [NonAction]
        public override System.Web.Mvc.ActionResult DefaultExecuteMenuButtonCheckPhrasesConsistencyDialog(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.BusinessLayer.DxSpecification> controllerData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DefaultExecuteMenuButtonCheckPhrasesConsistencyDialog);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            DefaultExecuteMenuButtonCheckPhrasesConsistencyDialogOverride(callInfo, controllerData);
            return callInfo;
        }

        [NonAction]
        partial void ExecuteCustomEventHandlerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string transactionId, string buttonId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExecuteCustomEventHandler(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string transactionId, string buttonId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExecuteCustomEventHandler);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "transactionId", transactionId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "buttonId", buttonId);
            ExecuteCustomEventHandlerOverride(callInfo, controllerData, transactionId, buttonId);
            return callInfo;
        }

        [NonAction]
        partial void AddTagOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal id);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult AddTag(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal id)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.AddTag);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AddTagOverride(callInfo, controllerData, id);
            return callInfo;
        }

        [NonAction]
        partial void RemoveTagOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal id);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult RemoveTag(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal id)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.RemoveTag);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            RemoveTagOverride(callInfo, controllerData, id);
            return callInfo;
        }

        [NonAction]
        partial void GetOpenDialogSettingsOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data callInfo, string originalActionName);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult<Selerant.DevEx.WebPages.OpenDialogSettings.Data> GetOpenDialogSettings(string originalActionName)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data(Area, Name, ActionNames.GetOpenDialogSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "originalActionName", originalActionName);
            GetOpenDialogSettingsOverride(callInfo, originalActionName);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
