// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using Autofac;
using Selerant.DevEx.Infrastructure;
using Selerant.Infrastructure.DependencyContainer;
using T4MVC_DIR;
using Selerant.DevEx.Modules.DIRModule.ModuleBlocks._ThisProject;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd._ThisProject;
using Selerant.DevEx.Infrastructure.Modules;
namespace Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers
{
    public partial class GeneralPanelController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public GeneralPanelController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected GeneralPanelController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult EditGeneralPanelDialogActivity()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.EditGeneralPanelDialogActivity);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult EditGeneralPanelDialog()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.EditGeneralPanelDialog);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult Update()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.Update);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult Export()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.Export);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult IndexDirect()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.IndexDirect);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult Index()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult ExcuteReport()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.ExcuteReport);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetPanelGridData()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetPanelGridData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult GetPanelExportData()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.GetPanelExportData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SecuritySettingsOnPanelEntity()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SecuritySettingsOnPanelEntity);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult<Selerant.DevEx.WebPages.OpenDialogSettings.Data> GetOpenDialogSettings()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data(Area, Name, ActionNames.GetOpenDialogSettings);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public GeneralPanelController Actions { get { return MVC_DIR.AssessmentNavigator.GeneralPanel; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "AssessmentNavigator";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "GeneralPanel";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "GeneralPanel";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string EditGeneralPanelDialogActivity = "EditGeneralPanelDialogActivity";
            public readonly string EditGeneralPanelDialog = "EditGeneralPanelDialog";
            public readonly string Update = "Update";
            public readonly string Export = "Export";
            public readonly string IndexDirect = "IndexDirect";
            public readonly string Index = "Index";
            public readonly string ExcuteReport = "ExcuteReport";
            public readonly string GetPanelGridData = "GetPanelGridData";
            public readonly string GetPanelExportData = "GetPanelExportData";
            public readonly string SecuritySettingsOnPanelEntity = "SecuritySettingsOnPanelEntity";
            public readonly string GetOpenDialogSettings = "GetOpenDialogSettings";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string EditGeneralPanelDialogActivity = "EditGeneralPanelDialogActivity";
            public const string EditGeneralPanelDialog = "EditGeneralPanelDialog";
            public const string Update = "Update";
            public const string Export = "Export";
            public const string IndexDirect = "IndexDirect";
            public const string Index = "Index";
            public const string ExcuteReport = "ExcuteReport";
            public const string GetPanelGridData = "GetPanelGridData";
            public const string GetPanelExportData = "GetPanelExportData";
            public const string SecuritySettingsOnPanelEntity = "SecuritySettingsOnPanelEntity";
            public const string GetOpenDialogSettings = "GetOpenDialogSettings";
        }


        static readonly ActionParamsClass_EditGeneralPanelDialogActivity s_params_EditGeneralPanelDialogActivity = new ActionParamsClass_EditGeneralPanelDialogActivity();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditGeneralPanelDialogActivity EditGeneralPanelDialogActivityParams { get { return s_params_EditGeneralPanelDialogActivity; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditGeneralPanelDialogActivity
        {
            public readonly string controllerData = "controllerData";
        }
        static readonly ActionParamsClass_EditGeneralPanelDialog s_params_EditGeneralPanelDialog = new ActionParamsClass_EditGeneralPanelDialog();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditGeneralPanelDialog EditGeneralPanelDialogParams { get { return s_params_EditGeneralPanelDialog; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditGeneralPanelDialog
        {
            public readonly string assessmentIdentifiableString = "assessmentIdentifiableString";
        }
        static readonly ActionParamsClass_Update s_params_Update = new ActionParamsClass_Update();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Update UpdateParams { get { return s_params_Update; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Update
        {
            public readonly string generalModelPartialJson = "generalModelPartialJson";
        }
        static readonly ActionParamsClass_Export s_params_Export = new ActionParamsClass_Export();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Export ExportParams { get { return s_params_Export; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Export
        {
            public readonly string controllerData = "controllerData";
        }
        static readonly ActionParamsClass_IndexDirect s_params_IndexDirect = new ActionParamsClass_IndexDirect();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IndexDirect IndexDirectParams { get { return s_params_IndexDirect; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IndexDirect
        {
            public readonly string identifiableString = "identifiableString";
            public readonly string tabId = "tabId";
            public readonly string mode = "mode";
        }
        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string data = "data";
        }
        static readonly ActionParamsClass_ExcuteReport s_params_ExcuteReport = new ActionParamsClass_ExcuteReport();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExcuteReport ExcuteReportParams { get { return s_params_ExcuteReport; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExcuteReport
        {
            public readonly string controllerData = "controllerData";
            public readonly string rowEntityIdentifiableString = "rowEntityIdentifiableString";
        }
        static readonly ActionParamsClass_GetPanelGridData s_params_GetPanelGridData = new ActionParamsClass_GetPanelGridData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPanelGridData GetPanelGridDataParams { get { return s_params_GetPanelGridData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPanelGridData
        {
            public readonly string controllerData = "controllerData";
            public readonly string clientGridRequest = "clientGridRequest";
        }
        static readonly ActionParamsClass_GetPanelExportData s_params_GetPanelExportData = new ActionParamsClass_GetPanelExportData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPanelExportData GetPanelExportDataParams { get { return s_params_GetPanelExportData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPanelExportData
        {
            public readonly string controllerData = "controllerData";
            public readonly string exportSettings = "exportSettings";
        }
        static readonly ActionParamsClass_SecuritySettingsOnPanelEntity s_params_SecuritySettingsOnPanelEntity = new ActionParamsClass_SecuritySettingsOnPanelEntity();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SecuritySettingsOnPanelEntity SecuritySettingsOnPanelEntityParams { get { return s_params_SecuritySettingsOnPanelEntity; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SecuritySettingsOnPanelEntity
        {
            public readonly string requestData = "requestData";
            public readonly string identifiableString = "identifiableString";
        }
        static readonly ActionParamsClass_GetOpenDialogSettings s_params_GetOpenDialogSettings = new ActionParamsClass_GetOpenDialogSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOpenDialogSettings GetOpenDialogSettingsParams { get { return s_params_GetOpenDialogSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOpenDialogSettings
        {
            public readonly string originalActionName = "originalActionName";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string EditGeneralPanelDialog = "EditGeneralPanelDialog";
                public readonly string EditGeneralPanelDialog_ts = "EditGeneralPanelDialog_ts";
                public readonly string GeneralPanel = "GeneralPanel";
                public readonly string GeneralPanelPartial = "GeneralPanelPartial";
                public readonly string GeneralPanelPartial_ts = "GeneralPanelPartial_ts";
                public readonly string Index = "Index";
            }
            public readonly string EditGeneralPanelDialog = "~/Areas/AssessmentNavigator/Views/GeneralPanel/EditGeneralPanelDialog.cshtml";
            public readonly string EditGeneralPanelDialog_ts = "~/Areas/AssessmentNavigator/Views/GeneralPanel/EditGeneralPanelDialog.ts";
            public readonly string GeneralPanel = "~/Areas/AssessmentNavigator/Views/GeneralPanel/GeneralPanel.ts";
            public readonly string GeneralPanelPartial = "~/Areas/AssessmentNavigator/Views/GeneralPanel/GeneralPanelPartial.cshtml";
            public readonly string GeneralPanelPartial_ts = "~/Areas/AssessmentNavigator/Views/GeneralPanel/GeneralPanelPartial.ts";
            public readonly string Index = "~/Areas/AssessmentNavigator/Views/GeneralPanel/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_GeneralPanelController : Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.GeneralPanelController
    {
        public T4MVC_GeneralPanelController() : base(Dummy.Instance) { }

        [NonAction]
        partial void EditGeneralPanelDialogActivityOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult EditGeneralPanelDialogActivity(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.EditGeneralPanelDialogActivity);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            EditGeneralPanelDialogActivityOverride(callInfo, controllerData);
            return callInfo;
        }

        [NonAction]
        partial void EditGeneralPanelDialogOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, string assessmentIdentifiableString);

        [NonAction]
        public override System.Web.Mvc.ViewResult EditGeneralPanelDialog(string assessmentIdentifiableString)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.EditGeneralPanelDialog);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "assessmentIdentifiableString", assessmentIdentifiableString);
            EditGeneralPanelDialogOverride(callInfo, assessmentIdentifiableString);
            return callInfo;
        }

        [NonAction]
        partial void UpdateOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Models.Panels.GeneralPanel.GeneralModelPartial.GeneralModelPartialJson generalModelPartialJson);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult Update(Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Models.Panels.GeneralPanel.GeneralModelPartial.GeneralModelPartialJson generalModelPartialJson)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.Update);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "generalModelPartialJson", generalModelPartialJson);
            UpdateOverride(callInfo, generalModelPartialJson);
            return callInfo;
        }

        [NonAction]
        partial void ExportOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult Export(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.Export);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ExportOverride(callInfo, controllerData);
            return callInfo;
        }

        [NonAction]
        partial void IndexDirectOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, string identifiableString, string tabId, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorModel.Modes mode);

        [NonAction]
        public override System.Web.Mvc.ViewResult IndexDirect(string identifiableString, string tabId, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorModel.Modes mode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.IndexDirect);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tabId", tabId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mode", mode);
            IndexDirectOverride(callInfo, identifiableString, tabId, mode);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Controllers.DevExNavigatorPanelController.IndexActionNavigatorPanelControllerData data);

        [NonAction]
        public override System.Web.Mvc.ViewResult Index(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Controllers.DevExNavigatorPanelController.IndexActionNavigatorPanelControllerData data)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            IndexOverride(callInfo, data);
            return callInfo;
        }

        [NonAction]
        partial void ExcuteReportOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string rowEntityIdentifiableString);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult ExcuteReport(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string rowEntityIdentifiableString)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.ExcuteReport);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rowEntityIdentifiableString", rowEntityIdentifiableString);
            ExcuteReportOverride(callInfo, controllerData, rowEntityIdentifiableString);
            return callInfo;
        }

        [NonAction]
        partial void GetPanelGridDataOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, Selerant.DevEx.WebMvcModules.Helpers.jqGrid.GridSettings clientGridRequest);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetPanelGridData(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, Selerant.DevEx.WebMvcModules.Helpers.jqGrid.GridSettings clientGridRequest)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetPanelGridData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "clientGridRequest", clientGridRequest);
            GetPanelGridDataOverride(callInfo, controllerData, clientGridRequest);
            return callInfo;
        }

        [NonAction]
        partial void GetPanelExportDataOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, Selerant.DevEx.WebMvcModules.Infrastructure.Controls.Menu.MenuHelper.GridExportSettings exportSettings);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult GetPanelExportData(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, Selerant.DevEx.WebMvcModules.Infrastructure.Controls.Menu.MenuHelper.GridExportSettings exportSettings)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.GetPanelExportData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "exportSettings", exportSettings);
            GetPanelExportDataOverride(callInfo, controllerData, exportSettings);
            return callInfo;
        }

        [NonAction]
        partial void SecuritySettingsOnPanelEntityOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> requestData, string identifiableString);

        [NonAction]
        public override System.Web.Mvc.ActionResult SecuritySettingsOnPanelEntity(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> requestData, string identifiableString)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SecuritySettingsOnPanelEntity);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestData", requestData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            SecuritySettingsOnPanelEntityOverride(callInfo, requestData, identifiableString);
            return callInfo;
        }

        [NonAction]
        partial void GetOpenDialogSettingsOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data callInfo, string originalActionName);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult<Selerant.DevEx.WebPages.OpenDialogSettings.Data> GetOpenDialogSettings(string originalActionName)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data(Area, Name, ActionNames.GetOpenDialogSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "originalActionName", originalActionName);
            GetOpenDialogSettingsOverride(callInfo, originalActionName);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
