// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using Autofac;
using Selerant.DevEx.Infrastructure;
using Selerant.Infrastructure.DependencyContainer;
using T4MVC_DIR;
using Selerant.DevEx.Modules.DIRModule.ModuleBlocks._ThisProject;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd._ThisProject;
using Selerant.DevEx.Infrastructure.Modules;
namespace Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.DIRAdminTools.Controllers
{
    public partial class AssessmentTypesController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AssessmentTypesController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AssessmentTypesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult AddAssessmentTypeClick()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.AddAssessmentTypeClick);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddAssessmentTypeDialogIndex()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAssessmentTypeDialogIndex);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult OpenEditAssessmentTypeDialogIndex()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OpenEditAssessmentTypeDialogIndex);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult SaveAssessmentType()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.SaveAssessmentType);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult ActivateAssessmentType()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.ActivateAssessmentType);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult EditAssessmentType()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.EditAssessmentType);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult DeleteAssessmentType()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.DeleteAssessmentType);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetAdminToolGridData()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetAdminToolGridData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult GetAdminToolExportData()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.GetAdminToolExportData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult<Selerant.DevEx.WebPages.OpenDialogSettings.Data> GetOpenDialogSettings()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data(Area, Name, ActionNames.GetOpenDialogSettings);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AssessmentTypesController Actions { get { return MVC_DIR.DIRAdminTools.AssessmentTypes; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "DIRAdminTools";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "AssessmentTypes";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "AssessmentTypes";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string AddAssessmentTypeClick = "AddAssessmentTypeClick";
            public readonly string AddAssessmentTypeDialogIndex = "AddAssessmentTypeDialogIndex";
            public readonly string OpenEditAssessmentTypeDialogIndex = "OpenEditAssessmentTypeDialogIndex";
            public readonly string SaveAssessmentType = "SaveAssessmentType";
            public readonly string ActivateAssessmentType = "ActivateAssessmentType";
            public readonly string EditAssessmentType = "EditAssessmentType";
            public readonly string DeleteAssessmentType = "DeleteAssessmentType";
            public readonly string GetAdminToolGridData = "GetAdminToolGridData";
            public readonly string GetAdminToolExportData = "GetAdminToolExportData";
            public readonly string GetOpenDialogSettings = "GetOpenDialogSettings";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string AddAssessmentTypeClick = "AddAssessmentTypeClick";
            public const string AddAssessmentTypeDialogIndex = "AddAssessmentTypeDialogIndex";
            public const string OpenEditAssessmentTypeDialogIndex = "OpenEditAssessmentTypeDialogIndex";
            public const string SaveAssessmentType = "SaveAssessmentType";
            public const string ActivateAssessmentType = "ActivateAssessmentType";
            public const string EditAssessmentType = "EditAssessmentType";
            public const string DeleteAssessmentType = "DeleteAssessmentType";
            public const string GetAdminToolGridData = "GetAdminToolGridData";
            public const string GetAdminToolExportData = "GetAdminToolExportData";
            public const string GetOpenDialogSettings = "GetOpenDialogSettings";
        }


        static readonly ActionParamsClass_AddAssessmentTypeClick s_params_AddAssessmentTypeClick = new ActionParamsClass_AddAssessmentTypeClick();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddAssessmentTypeClick AddAssessmentTypeClickParams { get { return s_params_AddAssessmentTypeClick; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddAssessmentTypeClick
        {
            public readonly string controllerData = "controllerData";
            public readonly string identifiableString = "identifiableString";
        }
        static readonly ActionParamsClass_AddAssessmentTypeDialogIndex s_params_AddAssessmentTypeDialogIndex = new ActionParamsClass_AddAssessmentTypeDialogIndex();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddAssessmentTypeDialogIndex AddAssessmentTypeDialogIndexParams { get { return s_params_AddAssessmentTypeDialogIndex; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddAssessmentTypeDialogIndex
        {
            public readonly string controllerData = "controllerData";
        }
        static readonly ActionParamsClass_OpenEditAssessmentTypeDialogIndex s_params_OpenEditAssessmentTypeDialogIndex = new ActionParamsClass_OpenEditAssessmentTypeDialogIndex();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_OpenEditAssessmentTypeDialogIndex OpenEditAssessmentTypeDialogIndexParams { get { return s_params_OpenEditAssessmentTypeDialogIndex; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_OpenEditAssessmentTypeDialogIndex
        {
            public readonly string controllerData = "controllerData";
            public readonly string identifiableString = "identifiableString";
            public readonly string isEditMode = "isEditMode";
        }
        static readonly ActionParamsClass_SaveAssessmentType s_params_SaveAssessmentType = new ActionParamsClass_SaveAssessmentType();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveAssessmentType SaveAssessmentTypeParams { get { return s_params_SaveAssessmentType; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveAssessmentType
        {
            public readonly string controllerData = "controllerData";
            public readonly string formData = "formData";
        }
        static readonly ActionParamsClass_ActivateAssessmentType s_params_ActivateAssessmentType = new ActionParamsClass_ActivateAssessmentType();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ActivateAssessmentType ActivateAssessmentTypeParams { get { return s_params_ActivateAssessmentType; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ActivateAssessmentType
        {
            public readonly string controllerData = "controllerData";
            public readonly string identifiableString = "identifiableString";
        }
        static readonly ActionParamsClass_EditAssessmentType s_params_EditAssessmentType = new ActionParamsClass_EditAssessmentType();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditAssessmentType EditAssessmentTypeParams { get { return s_params_EditAssessmentType; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditAssessmentType
        {
            public readonly string controllerData = "controllerData";
            public readonly string identifiableString = "identifiableString";
        }
        static readonly ActionParamsClass_DeleteAssessmentType s_params_DeleteAssessmentType = new ActionParamsClass_DeleteAssessmentType();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteAssessmentType DeleteAssessmentTypeParams { get { return s_params_DeleteAssessmentType; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteAssessmentType
        {
            public readonly string controllerData = "controllerData";
            public readonly string identifiableString = "identifiableString";
        }
        static readonly ActionParamsClass_GetAdminToolGridData s_params_GetAdminToolGridData = new ActionParamsClass_GetAdminToolGridData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAdminToolGridData GetAdminToolGridDataParams { get { return s_params_GetAdminToolGridData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAdminToolGridData
        {
            public readonly string controllerData = "controllerData";
            public readonly string clientGridRequest = "clientGridRequest";
            public readonly string nodeId = "nodeId";
        }
        static readonly ActionParamsClass_GetAdminToolExportData s_params_GetAdminToolExportData = new ActionParamsClass_GetAdminToolExportData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAdminToolExportData GetAdminToolExportDataParams { get { return s_params_GetAdminToolExportData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAdminToolExportData
        {
            public readonly string controllerData = "controllerData";
            public readonly string exportSettings = "exportSettings";
        }
        static readonly ActionParamsClass_GetOpenDialogSettings s_params_GetOpenDialogSettings = new ActionParamsClass_GetOpenDialogSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOpenDialogSettings GetOpenDialogSettingsParams { get { return s_params_GetOpenDialogSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOpenDialogSettings
        {
            public readonly string originalActionName = "originalActionName";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string EditAssessmentTypeDialog = "EditAssessmentTypeDialog";
                public readonly string EditAssessmentTypeDialog_ts = "EditAssessmentTypeDialog_ts";
                public readonly string EditAssessmentTypeDialogIndex = "EditAssessmentTypeDialogIndex";
                public readonly string Index = "Index";
                public readonly string Index_ts = "Index_ts";
            }
            public readonly string EditAssessmentTypeDialog = "~/Areas/DIRAdminTools/Views/AssessmentTypes/EditAssessmentTypeDialog.cshtml";
            public readonly string EditAssessmentTypeDialog_ts = "~/Areas/DIRAdminTools/Views/AssessmentTypes/EditAssessmentTypeDialog.ts";
            public readonly string EditAssessmentTypeDialogIndex = "~/Areas/DIRAdminTools/Views/AssessmentTypes/EditAssessmentTypeDialogIndex.cshtml";
            public readonly string Index = "~/Areas/DIRAdminTools/Views/AssessmentTypes/Index.cshtml";
            public readonly string Index_ts = "~/Areas/DIRAdminTools/Views/AssessmentTypes/Index.ts";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AssessmentTypesController : Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.DIRAdminTools.Controllers.AssessmentTypesController
    {
        public T4MVC_AssessmentTypesController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AddAssessmentTypeClickOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData, string identifiableString);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult AddAssessmentTypeClick(Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData, string identifiableString)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.AddAssessmentTypeClick);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            AddAssessmentTypeClickOverride(callInfo, controllerData, identifiableString);
            return callInfo;
        }

        [NonAction]
        partial void AddAssessmentTypeDialogIndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddAssessmentTypeDialogIndex(Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddAssessmentTypeDialogIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            AddAssessmentTypeDialogIndexOverride(callInfo, controllerData);
            return callInfo;
        }

        [NonAction]
        partial void OpenEditAssessmentTypeDialogIndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData, string identifiableString, bool isEditMode);

        [NonAction]
        public override System.Web.Mvc.ActionResult OpenEditAssessmentTypeDialogIndex(Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData, string identifiableString, bool isEditMode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OpenEditAssessmentTypeDialogIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isEditMode", isEditMode);
            OpenEditAssessmentTypeDialogIndexOverride(callInfo, controllerData, identifiableString, isEditMode);
            return callInfo;
        }

        [NonAction]
        partial void SaveAssessmentTypeOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData, Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.DIRAdminTools.Models.EditAssessmentTypeModel.CreateNewAssessmentTypeDialogFormData formData);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult SaveAssessmentType(Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData, Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.DIRAdminTools.Models.EditAssessmentTypeModel.CreateNewAssessmentTypeDialogFormData formData)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.SaveAssessmentType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formData", formData);
            SaveAssessmentTypeOverride(callInfo, controllerData, formData);
            return callInfo;
        }

        [NonAction]
        partial void ActivateAssessmentTypeOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData, string identifiableString);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult ActivateAssessmentType(Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData, string identifiableString)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.ActivateAssessmentType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            ActivateAssessmentTypeOverride(callInfo, controllerData, identifiableString);
            return callInfo;
        }

        [NonAction]
        partial void EditAssessmentTypeOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData, string identifiableString);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult EditAssessmentType(Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData, string identifiableString)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.EditAssessmentType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            EditAssessmentTypeOverride(callInfo, controllerData, identifiableString);
            return callInfo;
        }

        [NonAction]
        partial void DeleteAssessmentTypeOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData, string identifiableString);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult DeleteAssessmentType(Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData, string identifiableString)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.DeleteAssessmentType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            DeleteAssessmentTypeOverride(callInfo, controllerData, identifiableString);
            return callInfo;
        }

        [NonAction]
        partial void GetAdminToolGridDataOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData, Selerant.DevEx.WebMvcModules.Helpers.jqGrid.GridSettings clientGridRequest, string nodeId);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetAdminToolGridData(Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData, Selerant.DevEx.WebMvcModules.Helpers.jqGrid.GridSettings clientGridRequest, string nodeId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetAdminToolGridData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "clientGridRequest", clientGridRequest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nodeId", nodeId);
            GetAdminToolGridDataOverride(callInfo, controllerData, clientGridRequest, nodeId);
            return callInfo;
        }

        [NonAction]
        partial void GetAdminToolExportDataOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData, Selerant.DevEx.WebMvcModules.Infrastructure.Controls.Menu.MenuHelper.GridExportSettings exportSettings);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult GetAdminToolExportData(Selerant.DevEx.WebMvcModules.Areas.AdminTools.Models.AdminToolControllerData controllerData, Selerant.DevEx.WebMvcModules.Infrastructure.Controls.Menu.MenuHelper.GridExportSettings exportSettings)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.GetAdminToolExportData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "exportSettings", exportSettings);
            GetAdminToolExportDataOverride(callInfo, controllerData, exportSettings);
            return callInfo;
        }

        [NonAction]
        partial void GetOpenDialogSettingsOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data callInfo, string originalActionName);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult<Selerant.DevEx.WebPages.OpenDialogSettings.Data> GetOpenDialogSettings(string originalActionName)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data(Area, Name, ActionNames.GetOpenDialogSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "originalActionName", originalActionName);
            GetOpenDialogSettingsOverride(callInfo, originalActionName);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
