// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using Autofac;
using Selerant.DevEx.Infrastructure;
using Selerant.Infrastructure.DependencyContainer;
using T4MVC_DIR;
using Selerant.DevEx.Modules.DIRModule.ModuleBlocks._ThisProject;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd._ThisProject;
using Selerant.DevEx.Infrastructure.Modules;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC_DIR
{
    static readonly AssessmentNavigatorClass s_AssessmentNavigator = new AssessmentNavigatorClass();
    public static AssessmentNavigatorClass AssessmentNavigator { get { return s_AssessmentNavigator; } }
    static readonly AssessmentSearchClass s_AssessmentSearch = new AssessmentSearchClass();
    public static AssessmentSearchClass AssessmentSearch { get { return s_AssessmentSearch; } }
    static readonly DIRAdminToolsClass s_DIRAdminTools = new DIRAdminToolsClass();
    public static DIRAdminToolsClass DIRAdminTools { get { return s_DIRAdminTools; } }
}

namespace T4MVC_DIR
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class AssessmentNavigatorClass
    {
        public readonly string Name = "AssessmentNavigator";
        public Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.AssessmentDashboardDialogController AssessmentDashboardDialog = new Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.T4MVC_AssessmentDashboardDialogController();
        public Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.AssessmentResultsController AssessmentResults = new Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.T4MVC_AssessmentResultsController();
        public Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.CopyAssessmentController CopyAssessment = new Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.T4MVC_CopyAssessmentController();
        public Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.CreateAssessmentDialogController CreateAssessmentDialog = new Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.T4MVC_CreateAssessmentDialogController();
        public Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.GeneralPanelController GeneralPanel = new Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.T4MVC_GeneralPanelController();
        public Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.HomeController Home = new Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.T4MVC_HomeController();
        public Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.ManageAssessmentDialogController ManageAssessmentDialog = new Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.T4MVC_ManageAssessmentDialogController();
        public Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.ResourceManagementController ResourceManagement = new Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.T4MVC_ResourceManagementController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class AssessmentSearchClass
    {
        public readonly string Name = "AssessmentSearch";
        public Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.AssessmentCustomQueryPanelController AssessmentCustomQueryPanel = new Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.T4MVC_AssessmentCustomQueryPanelController();
        public Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.AssessmentCustomQueryPanelCreateController AssessmentCustomQueryPanelCreate = new Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.T4MVC_AssessmentCustomQueryPanelCreateController();
        public Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.CustomQueryPanelEditController CustomQueryPanelEdit = new Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.T4MVC_CustomQueryPanelEditController();
        public Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.AssessmentCustomQueryPanelRunController AssessmentCustomQueryPanelRun = new Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.T4MVC_AssessmentCustomQueryPanelRunController();
        public Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.AssessmentRecentSearchPanelController AssessmentRecentSearchPanel = new Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.T4MVC_AssessmentRecentSearchPanelController();
        public Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.CompositePanelController CompositePanel = new Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.T4MVC_CompositePanelController();
        public Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.HomeController Home = new Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.T4MVC_HomeController();
        public Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.SearchResultPanelController SearchResultPanel = new Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.T4MVC_SearchResultPanelController();
        public T4MVC_DIR.AssessmentSearch.BasicSearchController BasicSearch = new T4MVC_DIR.AssessmentSearch.BasicSearchController();
        public T4MVC_DIR.AssessmentSearch.RecentPanelController RecentPanel = new T4MVC_DIR.AssessmentSearch.RecentPanelController();
        public T4MVC_DIR.AssessmentSearch.ResultPanelController ResultPanel = new T4MVC_DIR.AssessmentSearch.ResultPanelController();
    }
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class DIRAdminToolsClass
    {
        public readonly string Name = "DIRAdminTools";
        public Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.DIRAdminTools.Controllers.AssessmentTypesController AssessmentTypes = new Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.DIRAdminTools.Controllers.T4MVC_AssessmentTypesController();
    }
}

#pragma warning disable 0436
namespace T4MVC_DIR
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}
#pragma warning restore 0436

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public partial class T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult : Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult, IT4MVCActionResult
{
    public T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public partial class T4MVC_System_Web_Mvc_JsonResult : System.Web.Mvc.JsonResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_JsonResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public partial class T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data : Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult<Selerant.DevEx.WebPages.OpenDialogSettings.Data>, IT4MVCActionResult
{
    public T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public partial class T4MVC_System_Web_Mvc_ViewResult : System.Web.Mvc.ViewResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ViewResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public partial class T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult : Selerant.DevEx.WebMvcModules.Infrastructure.Base.AjaxResult, IT4MVCActionResult
{
    public T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public partial class T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_JSActivityAjaxResult : Selerant.DevEx.WebMvcModules.Infrastructure.Base.JSActivityAjaxResult, IT4MVCActionResult
{
    public T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_JSActivityAjaxResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace DIRLinks
{

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Areas {
        public const string UrlPath = "~/Areas";
        public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class AssessmentNavigator {
            public const string UrlPath = "~/Areas/AssessmentNavigator";
            public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Views {
                public const string UrlPath = "~/Areas/AssessmentNavigator/Views";
        		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class AssessmentDashboardDialog {
                    public const string UrlPath = "~/Areas/AssessmentNavigator/Views/AssessmentDashboardDialog";
            		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                    public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                    public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                    public static readonly string AssessmentDashboardDialog_css = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/AssessmentDashboardDialog.min.css") ? Url("AssessmentDashboardDialog.min.css") : Url("AssessmentDashboardDialog.css");
                    public static readonly string AssessmentDashboardDialog_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/AssessmentDashboardDialog.min.js") ? Url("AssessmentDashboardDialog.min.js") : Url("AssessmentDashboardDialog.js");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class FoodLosses {
                        public const string UrlPath = "~/Areas/AssessmentNavigator/Views/AssessmentDashboardDialog/FoodLosses";
                		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                        public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                        public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                        public static readonly string FoodLoss_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/FoodLoss.min.js") ? Url("FoodLoss.min.js") : Url("FoodLoss.js");
                        public static readonly string FoodLossesContainer_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/FoodLossesContainer.min.js") ? Url("FoodLossesContainer.min.js") : Url("FoodLossesContainer.js");
                    }
                
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class AssessmentResults {
                    public const string UrlPath = "~/Areas/AssessmentNavigator/Views/AssessmentResults";
            		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                    public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                    public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                    public static readonly string AssessmentResults_css = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/AssessmentResults.min.css") ? Url("AssessmentResults.min.css") : Url("AssessmentResults.css");
                    public static readonly string AssessmentResults_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/AssessmentResults.min.js") ? Url("AssessmentResults.min.js") : Url("AssessmentResults.js");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class CopyAssessment {
                    public const string UrlPath = "~/Areas/AssessmentNavigator/Views/CopyAssessment";
            		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                    public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                    public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                    public static readonly string CopyAssessment_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/CopyAssessment.min.js") ? Url("CopyAssessment.min.js") : Url("CopyAssessment.js");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class CreateAssessmentDialog {
                    public const string UrlPath = "~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog";
            		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                    public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                    public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                    public static readonly string BusinessDataDialog_css = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/BusinessDataDialog.min.css") ? Url("BusinessDataDialog.min.css") : Url("BusinessDataDialog.css");
                    public static readonly string BusinessDataDialog_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/BusinessDataDialog.min.js") ? Url("BusinessDataDialog.min.js") : Url("BusinessDataDialog.js");
                    public static readonly string CreateAssessmentDialog_css = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/CreateAssessmentDialog.min.css") ? Url("CreateAssessmentDialog.min.css") : Url("CreateAssessmentDialog.css");
                    public static readonly string CreateAssessmentDialog_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/CreateAssessmentDialog.min.js") ? Url("CreateAssessmentDialog.min.js") : Url("CreateAssessmentDialog.js");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class MergeInputs {
                        public const string UrlPath = "~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/MergeInputs";
                		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                        public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                        public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                        public static readonly string MergeInputsDialog_css = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/MergeInputsDialog.min.css") ? Url("MergeInputsDialog.min.css") : Url("MergeInputsDialog.css");
                        public static readonly string MergeInputsDialog_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/MergeInputsDialog.min.js") ? Url("MergeInputsDialog.min.js") : Url("MergeInputsDialog.js");
                    }
                
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class Shared {
                        public const string UrlPath = "~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/Shared";
                		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                        public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                        public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                        public static readonly string LCStageSteps_css = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/LCStageSteps.min.css") ? Url("LCStageSteps.min.css") : Url("LCStageSteps.css");
                        public static readonly string LCStageSteps_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/LCStageSteps.min.js") ? Url("LCStageSteps.min.js") : Url("LCStageSteps.js");
                    }
                
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class GeneralPanel {
                    public const string UrlPath = "~/Areas/AssessmentNavigator/Views/GeneralPanel";
            		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                    public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                    public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                    public static readonly string EditGeneralPanelDialog_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/EditGeneralPanelDialog.min.js") ? Url("EditGeneralPanelDialog.min.js") : Url("EditGeneralPanelDialog.js");
                    public static readonly string GeneralPanel_css = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/GeneralPanel.min.css") ? Url("GeneralPanel.min.css") : Url("GeneralPanel.css");
                    public static readonly string GeneralPanel_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/GeneralPanel.min.js") ? Url("GeneralPanel.min.js") : Url("GeneralPanel.js");
                    public static readonly string GeneralPanelPartial_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/GeneralPanelPartial.min.js") ? Url("GeneralPanelPartial.min.js") : Url("GeneralPanelPartial.js");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Home {
                    public const string UrlPath = "~/Areas/AssessmentNavigator/Views/Home";
            		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                    public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                    public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                    public static readonly string Index_css = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Index.min.css") ? Url("Index.min.css") : Url("Index.css");
                    public static readonly string Index_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Index.min.js") ? Url("Index.min.js") : Url("Index.js");
                    public static readonly string IndexEdit_css = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/IndexEdit.min.css") ? Url("IndexEdit.min.css") : Url("IndexEdit.css");
                    public static readonly string IndexEdit_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/IndexEdit.min.js") ? Url("IndexEdit.min.js") : Url("IndexEdit.js");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class ManageAssessmentDialog {
                    public const string UrlPath = "~/Areas/AssessmentNavigator/Views/ManageAssessmentDialog";
            		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                    public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                    public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                    public static readonly string ManageAssessmentDialog_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/ManageAssessmentDialog.min.js") ? Url("ManageAssessmentDialog.min.js") : Url("ManageAssessmentDialog.js");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class ResourceManagement {
                    public const string UrlPath = "~/Areas/AssessmentNavigator/Views/ResourceManagement";
            		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                    public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                    public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                    public static readonly string Index_css = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Index.min.css") ? Url("Index.min.css") : Url("Index.css");
                    public static readonly string Index_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Index.min.js") ? Url("Index.min.js") : Url("Index.js");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class Shared {
                        public const string UrlPath = "~/Areas/AssessmentNavigator/Views/ResourceManagement/Shared";
                		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                        public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                        public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                        public static readonly string BusinessCostGridTab_css = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/BusinessCostGridTab.min.css") ? Url("BusinessCostGridTab.min.css") : Url("BusinessCostGridTab.css");
                        public static readonly string BusinessCostGridTab_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/BusinessCostGridTab.min.js") ? Url("BusinessCostGridTab.min.js") : Url("BusinessCostGridTab.js");
                        public static readonly string DestinationsGridTab_css = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/DestinationsGridTab.min.css") ? Url("DestinationsGridTab.min.css") : Url("DestinationsGridTab.css");
                        public static readonly string DestinationsGridTab_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/DestinationsGridTab.min.js") ? Url("DestinationsGridTab.min.js") : Url("DestinationsGridTab.js");
                        public static readonly string GridTab_css = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/GridTab.min.css") ? Url("GridTab.min.css") : Url("GridTab.css");
                        public static readonly string GridTab_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/GridTab.min.js") ? Url("GridTab.min.js") : Url("GridTab.js");
                        public static readonly string InputsGridTab_css = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/InputsGridTab.min.css") ? Url("InputsGridTab.min.css") : Url("InputsGridTab.css");
                        public static readonly string InputsGridTab_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/InputsGridTab.min.js") ? Url("InputsGridTab.min.js") : Url("InputsGridTab.js");
                        public static readonly string OutputsGridTab_css = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/OutputsGridTab.min.css") ? Url("OutputsGridTab.min.css") : Url("OutputsGridTab.css");
                        public static readonly string OutputsGridTab_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/OutputsGridTab.min.js") ? Url("OutputsGridTab.min.js") : Url("OutputsGridTab.js");
                        public static readonly string ResourceNote_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/ResourceNote.min.js") ? Url("ResourceNote.min.js") : Url("ResourceNote.js");
                    }
                
                }
            
                public static readonly string web_config = Url("web.config");
            }
        
        }
    }

    public static partial class Areas {
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class AssessmentSearch {
            public const string UrlPath = "~/Areas/AssessmentSearch";
            public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Views {
                public const string UrlPath = "~/Areas/AssessmentSearch/Views";
        		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class BasicSearch {
                    public const string UrlPath = "~/Areas/AssessmentSearch/Views/BasicSearch";
            		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                    public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                    public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class CompositePanel {
                    public const string UrlPath = "~/Areas/AssessmentSearch/Views/CompositePanel";
            		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                    public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                    public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                    public static readonly string IndexModel_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/IndexModel.min.js") ? Url("IndexModel.min.js") : Url("IndexModel.js");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Home {
                    public const string UrlPath = "~/Areas/AssessmentSearch/Views/Home";
            		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                    public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                    public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                    public static readonly string AssessmentIndexModel_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/AssessmentIndexModel.min.js") ? Url("AssessmentIndexModel.min.js") : Url("AssessmentIndexModel.js");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class RecentPanel {
                    public const string UrlPath = "~/Areas/AssessmentSearch/Views/RecentPanel";
            		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                    public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                    public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                    public static readonly string AssessmentRecentPanel_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/AssessmentRecentPanel.min.js") ? Url("AssessmentRecentPanel.min.js") : Url("AssessmentRecentPanel.js");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class ResultPanel {
                    public const string UrlPath = "~/Areas/AssessmentSearch/Views/ResultPanel";
            		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                    public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                    public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                    public static readonly string AssessmentSearchResultPanel_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/AssessmentSearchResultPanel.min.js") ? Url("AssessmentSearchResultPanel.min.js") : Url("AssessmentSearchResultPanel.js");
                }
            
            }
        
        }
    }

    public static partial class Areas {
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class DIRAdminTools {
            public const string UrlPath = "~/Areas/DIRAdminTools";
            public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Views {
                public const string UrlPath = "~/Areas/DIRAdminTools/Views";
        		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class AssessmentTypes {
                    public const string UrlPath = "~/Areas/DIRAdminTools/Views/AssessmentTypes";
            		private static readonly string ModuleUrlPath = ModuleInfoHelper.ToModulePath(DIRModuleInfo.Instance, UrlPath);
                    public static string Url() { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath); }
                    public static string Url(string fileName) { return DIRT4MVCHelpers.ProcessVirtualPath(ModuleUrlPath + "/" + fileName); }
                    public static readonly string EditAssessmentTypeDialog_css = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/EditAssessmentTypeDialog.min.css") ? Url("EditAssessmentTypeDialog.min.css") : Url("EditAssessmentTypeDialog.css");
                    public static readonly string EditAssessmentTypeDialog_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/EditAssessmentTypeDialog.min.js") ? Url("EditAssessmentTypeDialog.min.js") : Url("EditAssessmentTypeDialog.js");
                    public static readonly string Index_css = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Index.min.css") ? Url("Index.min.css") : Url("Index.css");
                    public static readonly string Index_ts = DIRT4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Index.min.js") ? Url("Index.min.js") : Url("Index.js");
                }
            
                public static readonly string web_config = Url("web.config");
            }
        
        }
    }
    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Areas 
        {
            public static partial class AssessmentNavigator 
            {
                public static partial class Views 
                {
                    public static partial class AssessmentDashboardDialog 
                    {
                        public static partial class FoodLosses 
                        {
                            public static class Assets
                            {
                                public static readonly string FoodLoss_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/AssessmentDashboardDialog/FoodLosses/FoodLoss.js"); 
                                public static readonly string FoodLossesContainer_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/AssessmentDashboardDialog/FoodLosses/FoodLossesContainer.js"); 
                            }
                        }
                        public static class Assets
                        {
                            public static readonly string AssessmentDashboardDialog_css = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/AssessmentDashboardDialog/AssessmentDashboardDialog.css");
                            public static readonly string AssessmentDashboardDialog_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/AssessmentDashboardDialog/AssessmentDashboardDialog.js"); 
                        }
                    }
                    public static partial class AssessmentResults 
                    {
                        public static class Assets
                        {
                            public static readonly string AssessmentResults_css = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/AssessmentResults/AssessmentResults.css");
                            public static readonly string AssessmentResults_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/AssessmentResults/AssessmentResults.js"); 
                        }
                    }
                    public static partial class CopyAssessment 
                    {
                        public static class Assets
                        {
                            public static readonly string CopyAssessment_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/CopyAssessment/CopyAssessment.js"); 
                        }
                    }
                    public static partial class CreateAssessmentDialog 
                    {
                        public static partial class MergeInputs 
                        {
                            public static class Assets
                            {
                                public static readonly string MergeInputsDialog_css = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/MergeInputs/MergeInputsDialog.css");
                                public static readonly string MergeInputsDialog_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/MergeInputs/MergeInputsDialog.js"); 
                            }
                        }
                        public static partial class Shared 
                        {
                            public static class Assets
                            {
                                public static readonly string LCStageSteps_css = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/Shared/LCStageSteps.css");
                                public static readonly string LCStageSteps_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/Shared/LCStageSteps.js"); 
                            }
                        }
                        public static class Assets
                        {
                            public static readonly string BusinessDataDialog_css = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/BusinessDataDialog.css");
                            public static readonly string BusinessDataDialog_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/BusinessDataDialog.js"); 
                            public static readonly string CreateAssessmentDialog_css = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/CreateAssessmentDialog.css");
                            public static readonly string CreateAssessmentDialog_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/CreateAssessmentDialog.js"); 
                        }
                    }
                    public static partial class GeneralPanel 
                    {
                        public static class Assets
                        {
                            public static readonly string EditGeneralPanelDialog_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/GeneralPanel/EditGeneralPanelDialog.js"); 
                            public static readonly string GeneralPanel_css = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/GeneralPanel/GeneralPanel.css");
                            public static readonly string GeneralPanel_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/GeneralPanel/GeneralPanel.js"); 
                            public static readonly string GeneralPanelPartial_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/GeneralPanel/GeneralPanelPartial.js"); 
                        }
                    }
                    public static partial class Home 
                    {
                        public static class Assets
                        {
                            public static readonly string Index_css = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/Home/Index.css");
                            public static readonly string Index_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/Home/Index.js"); 
                            public static readonly string IndexEdit_css = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/Home/IndexEdit.css");
                            public static readonly string IndexEdit_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/Home/IndexEdit.js"); 
                        }
                    }
                    public static partial class ManageAssessmentDialog 
                    {
                        public static class Assets
                        {
                            public static readonly string ManageAssessmentDialog_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/ManageAssessmentDialog/ManageAssessmentDialog.js"); 
                        }
                    }
                    public static partial class ResourceManagement 
                    {
                        public static partial class Shared 
                        {
                            public static class Assets
                            {
                                public static readonly string BusinessCostGridTab_css = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/ResourceManagement/Shared/BusinessCostGridTab.css");
                                public static readonly string BusinessCostGridTab_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/ResourceManagement/Shared/BusinessCostGridTab.js"); 
                                public static readonly string DestinationsGridTab_css = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/ResourceManagement/Shared/DestinationsGridTab.css");
                                public static readonly string DestinationsGridTab_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/ResourceManagement/Shared/DestinationsGridTab.js"); 
                                public static readonly string GridTab_css = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/ResourceManagement/Shared/GridTab.css");
                                public static readonly string GridTab_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/ResourceManagement/Shared/GridTab.js"); 
                                public static readonly string InputsGridTab_css = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/ResourceManagement/Shared/InputsGridTab.css");
                                public static readonly string InputsGridTab_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/ResourceManagement/Shared/InputsGridTab.js"); 
                                public static readonly string OutputsGridTab_css = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/ResourceManagement/Shared/OutputsGridTab.css");
                                public static readonly string OutputsGridTab_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/ResourceManagement/Shared/OutputsGridTab.js"); 
                                public static readonly string ResourceNote_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/ResourceManagement/Shared/ResourceNote.js"); 
                            }
                        }
                        public static class Assets
                        {
                            public static readonly string Index_css = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/ResourceManagement/Index.css");
                            public static readonly string Index_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentNavigator/Views/ResourceManagement/Index.js"); 
                        }
                    }
                    public static class Assets
                    {
                    }
                }
            }
        }
        public static partial class Areas 
        {
            public static partial class AssessmentSearch 
            {
                public static partial class Views 
                {
                    public static partial class BasicSearch 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class CompositePanel 
                    {
                        public static class Assets
                        {
                            public static readonly string IndexModel_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentSearch/Views/CompositePanel/IndexModel.js"); 
                        }
                    }
                    public static partial class Home 
                    {
                        public static class Assets
                        {
                            public static readonly string AssessmentIndexModel_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentSearch/Views/Home/AssessmentIndexModel.js"); 
                        }
                    }
                    public static partial class RecentPanel 
                    {
                        public static class Assets
                        {
                            public static readonly string AssessmentRecentPanel_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentSearch/Views/RecentPanel/AssessmentRecentPanel.js"); 
                        }
                    }
                    public static partial class ResultPanel 
                    {
                        public static class Assets
                        {
                            public static readonly string AssessmentSearchResultPanel_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/AssessmentSearch/Views/ResultPanel/AssessmentSearchResultPanel.js"); 
                        }
                    }
                    public static class Assets
                    {
                    }
                }
            }
        }
        public static partial class Areas 
        {
            public static partial class DIRAdminTools 
            {
                public static partial class Views 
                {
                    public static partial class AssessmentTypes 
                    {
                        public static class Assets
                        {
                            public static readonly string EditAssessmentTypeDialog_css = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/DIRAdminTools/Views/AssessmentTypes/EditAssessmentTypeDialog.css");
                            public static readonly string EditAssessmentTypeDialog_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/DIRAdminTools/Views/AssessmentTypes/EditAssessmentTypeDialog.js"); 
                            public static readonly string Index_css = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/DIRAdminTools/Views/AssessmentTypes/Index.css");
                            public static readonly string Index_ts = DIRT4MVCHelpers.ProcessAssetPath("~/Areas/DIRAdminTools/Views/AssessmentTypes/Index.js"); 
                        }
                    }
                    public static class Assets
                    {
                    }
                }
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class DIRT4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        
		var virtualPathResolverUtility = IoC.Container.Resolve<IVirtualPathResolverUtility>();
        string path = virtualPathResolverUtility.ProcessVirtualPathDefault(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    private static string ProcessAssetPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and should retain this prefix
        return virtualPath;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;
    public static Func<string, string> ProcessAssetPath = ProcessAssetPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


