CREATE OR REPLACE PACKAGE DXDIR_PK_ASSESSMENT_LC_STAGE AS

	PROCEDURE InsertRecord
	(
		dcID NUMBER,
		sASSESSMENT_CODE VARCHAR2,
		sTITLE NVARCHAR2,
		dcVISIBLE NUMBER,
		dcSORT_ORDER NUMBER,
		dcSOURCE_ASMT_LC_STAGE_ID NUMBER
	);

	PROCEDURE UpdateRecord
	(
		dcID NUMBER,
		sASSESSMENT_CODE VARCHAR2,
		sTITLE NVARCHAR2,
		dcVISIBLE NUMBER,
		dcSORT_ORDER NUMBER,
		dcSOURCE_ASMT_LC_STAGE_ID NUMBER
	);

	PROCEDURE DeleteRecord
	(
		dcID NUMBER
	);

	PROCEDURE GetNextId
	(
        dcNextID OUT NUMBER
    );

END;
/

CREATE OR REPLACE PACKAGE BODY DXDIR_PK_ASSESSMENT_LC_STAGE AS
	PROCEDURE InsertRecord
	(
		dcID NUMBER,
		sASSESSMENT_CODE VARCHAR2,
		sTITLE NVARCHAR2,
		dcVISIBLE NUMBER,
		dcSORT_ORDER NUMBER,
		dcSOURCE_ASMT_LC_STAGE_ID NUMBER
	)
	IS
	BEGIN
		INSERT INTO DXDIR_ASSESSMENT_LC_STAGE
		(
			ID,
			ASSESSMENT_CODE,
			TITLE,
			VISIBLE,
			SORT_ORDER,
			SOURCE_ASMT_LC_STAGE_ID
		)
		VALUES
		(
			dcID,
			sASSESSMENT_CODE,
			sTITLE,
			dcVISIBLE,
			dcSORT_ORDER,
			dcSOURCE_ASMT_LC_STAGE_ID
		);
	END;

	PROCEDURE UpdateRecord
	(
		dcID NUMBER,
		sASSESSMENT_CODE VARCHAR2,
		sTITLE NVARCHAR2,
		dcVISIBLE NUMBER,
		dcSORT_ORDER NUMBER,
		dcSOURCE_ASMT_LC_STAGE_ID NUMBER
	)
	IS
	BEGIN
		UPDATE DXDIR_ASSESSMENT_LC_STAGE
		SET 
			ASSESSMENT_CODE = sASSESSMENT_CODE,
			TITLE = sTITLE,
			VISIBLE = dcVISIBLE,
			SORT_ORDER = dcSORT_ORDER,
			SOURCE_ASMT_LC_STAGE_ID = dcSOURCE_ASMT_LC_STAGE_ID
		WHERE
			ID = dcID;
	END;

	PROCEDURE DeleteRecord
	(
		dcID NUMBER
	)
	IS
	BEGIN
		DELETE FROM DXDIR_ASSESSMENT_LC_STAGE
		WHERE
			ID = dcID;
	END;

	PROCEDURE GetNextId
	(
        dcNextID OUT NUMBER
    )
	IS
	BEGIN
		SELECT DXDIR_ASSESSMENT_LC_STAGE_SEQ.NEXTVAL INTO dcNextID FROM DUAL;
    END;

END;
/
