CREATE OR REPLACE PACKAGE DXDIR_PK_DESTINATION AS

	TYPE t_cursor IS REF CURSOR;

	PROCEDURE InsertRecord
	(
		sCODE VARCHAR2,
		dcWASTE NUMBER,
		dcUSED_ON NUMBER,
		dcSORT_ORDER NUMBER,
		sTITLE NVARCHAR2
	);

	PROCEDURE UpdateRecord
	(
		sCODE VARCHAR2,
		dcWASTE NUMBER,
		dcUSED_ON NUMBER,
		dcSORT_ORDER NUMBER,
		sTITLE NVARCHAR2
	);

	PROCEDURE DeleteRecord
	(
		sCODE VARCHAR2
	);

	PROCEDURE SelectDestinationSort
	(
		sDESTINATION_CODES DX_PK_UTILITY.DX_Varchar2Array,
		po_cur in OUT t_cursor
	);

END;
/

CREATE OR REPLACE PACKAGE BODY DXDIR_PK_DESTINATION AS

	PROCEDURE InsertRecord
	(
		sCODE VARCHAR2,
		dcWASTE NUMBER,
		dcUSED_ON NUMBER,
		dcSORT_ORDER NUMBER,
		sTITLE NVARCHAR2
	)
	IS
	BEGIN
		INSERT INTO DXDIR_DESTINATION
		(
			CODE,
			WASTE,
			USED_ON,
			SORT_ORDER,
			TITLE
		)
		VALUES
		(
			sCODE,
			dcWASTE,
			dcUSED_ON,
			dcSORT_ORDER,
			sTITLE
		);
	END;

	PROCEDURE UpdateRecord
	(
		sCODE VARCHAR2,
		dcWASTE NUMBER,
		dcUSED_ON NUMBER,
		dcSORT_ORDER NUMBER,
		sTITLE NVARCHAR2
	)
	IS
	BEGIN
		UPDATE DXDIR_DESTINATION
		SET 
			WASTE = dcWASTE,
			USED_ON = dcUSED_ON,
			SORT_ORDER = dcSORT_ORDER,
			TITLE = sTITLE
		WHERE
			CODE = sCODE;
	END;

	PROCEDURE DeleteRecord
	(
		sCODE VARCHAR2
	)
	IS
	BEGIN
		DELETE FROM DXDIR_DESTINATION
		WHERE
			CODE = sCODE;
	END;

	PROCEDURE SelectDestinationSort
	(
		sDESTINATION_CODES DX_PK_UTILITY.DX_Varchar2Array,
		po_cur in OUT t_cursor
	)
    IS
		v_destinationCodes DX_Varchar2Table;
	BEGIN
		v_destinationCodes := DX_PK_Utility.ArrayToTable(sDESTINATION_CODES);

		OPEN po_cur FOR
			SELECT CODE, SORT_ORDER
			FROM DXDIR_DESTINATION
			WHERE CODE IN (SELECT COLUMN_VALUE FROM THE(SELECT CAST(v_destinationCodes AS DX_Varchar2Table) FROM DUAL));
	END;

END;
/
