CREATE OR REPLACE PACKAGE DXDIR_PK_PARTNERASSESSMENT AS

	TYPE t_cursor IS REF CURSOR;

	PROCEDURE InsertRecord(
		sCODE VARCHAR2,
		sPARTNER_ORG_CODE VARCHAR2,
		dcIS_SHARED NUMBER
	);

	PROCEDURE UpdateRecord(
		sCODE VARCHAR2,
		sPARTNER_ORG_CODE VARCHAR2,
		dcIS_SHARED NUMBER
	);

	PROCEDURE DeleteRecord(
		sCODE VARCHAR2,
		sPARTNER_ORG_CODE VARCHAR2
	);
		
END;
/

CREATE OR REPLACE PACKAGE BODY DXDIR_PK_PARTNERASSESSMENT AS

	PROCEDURE InsertRecord(
		sCODE VARCHAR2,
		sPARTNER_ORG_CODE VARCHAR2,
		dcIS_SHARED NUMBER
	) 
	IS
	BEGIN
		/* INSERT a new row in the table.*/
		INSERT INTO DXDIR_PARTNER_ASSESSMENT
		(
			ASSESSMENT_CODE,
			PARTNER_ORG_CODE,
			IS_SHARED
		)
		VALUES
		(
			sCODE,
			sPARTNER_ORG_CODE,
			dcIS_SHARED
		);
	END;

	PROCEDURE UpdateRecord(
		sCODE VARCHAR2,
		sPARTNER_ORG_CODE VARCHAR2,
		dcIS_SHARED NUMBER
	)
	IS
	BEGIN
		/* UPDATE an existing row in the table.*/
		UPDATE DXDIR_PARTNER_ASSESSMENT
		SET 
			IS_SHARED = dcIS_SHARED
		WHERE
			ASSESSMENT_CODE = sCODE AND
			PARTNER_ORG_CODE = sPARTNER_ORG_CODE;
		END;

	PROCEDURE DeleteRecord(
		sCODE VARCHAR2,
		sPARTNER_ORG_CODE VARCHAR2
	)
	IS
	BEGIN
		/* DELETE an existing row from the table.*/
		DELETE FROM DXDIR_PARTNER_ASSESSMENT
		WHERE
			ASSESSMENT_CODE = sCODE AND
			PARTNER_ORG_CODE = sPARTNER_ORG_CODE;
	END;
		
END;
/
