CREATE OR REPLACE PACKAGE DXDIR_PK_RESOURCE_NOTE AS

	PROCEDURE InsertRecord
	(
		sASSESSMENT_CODE VARCHAR,
		dcLC_STAGE_ID NUMBER,
		sTYPE VARCHAR,
		sNOTE VARCHAR
	);

	PROCEDURE UpdateRecord
	(
		sASSESSMENT_CODE VARCHAR,
		dcLC_STAGE_ID NUMBER,
		sTYPE VARCHAR,
		sNOTE VARCHAR
	);

	PROCEDURE DeleteRecord
	(
		sASSESSMENT_CODE VARCHAR,
		dcLC_STAGE_ID NUMBER,
		sTYPE VARCHAR
	);

END;
/

CREATE OR REPLACE PACKAGE BODY DXDIR_PK_RESOURCE_NOTE AS
	PROCEDURE InsertRecord
	(
		sASSESSMENT_CODE VARCHAR,
		dcLC_STAGE_ID NUMBER,
		sTYPE VARCHAR,
		sNOTE VARCHAR
	)
	IS
	BEGIN
		INSERT INTO DXDIR_RESOURCE_NOTE
		(
			ASSESSMENT_CODE,
			LC_STAGE_ID,
			TYPE,
			NOTE
		)
		VALUES
		(
			sASSESSMENT_CODE,
			dcLC_STAGE_ID,
			sTYPE,
			sNOTE
		);
	END;

	PROCEDURE UpdateRecord
	(
		sASSESSMENT_CODE VARCHAR,
		dcLC_STAGE_ID NUMBER,
		sTYPE VARCHAR,
		sNOTE VARCHAR
	)
	IS
	BEGIN
		UPDATE DXDIR_RESOURCE_NOTE
		SET
			NOTE = sNOTE
		WHERE
			ASSESSMENT_CODE = sASSESSMENT_CODE
			AND LC_STAGE_ID = dcLC_STAGE_ID
			AND TYPE = sTYPE;
	END;

	PROCEDURE DeleteRecord
	(
		sASSESSMENT_CODE VARCHAR,
		dcLC_STAGE_ID NUMBER,
		sTYPE VARCHAR
	)
	IS
	BEGIN
		DELETE FROM DXDIR_RESOURCE_NOTE
		WHERE
			ASSESSMENT_CODE = sASSESSMENT_CODE
			AND LC_STAGE_ID = dcLC_STAGE_ID
			AND TYPE = sTYPE;
	END;

END;
/