using Selerant.ApplicationBlocks.Data;
using Selerant.DevEx.BusinessLayer;
using System;
using System.Collections.Generic;

namespace Selerant.DevEx.Modules.DIRModule.BackEnd.BusinessCostManagement
{
	[IsDxObject]
	[BoundTable(typeof(BizDsBusinessCost), TableName = "DXDIR_BUSINESS_COST")]
	public partial class DxBusinessCost : DxObject
	{
		private const string configElementName = "dxBusinessCost";

		#region Fields

		[BoundColumn("ID", true, 0, DbType = GenericDbType.Decimal)]
		protected decimal id;

		[BoundColumn("ASSESSMENT_CODE", DbType = GenericDbType.Varchar)]
		protected string assessmentCode;

		[BoundColumn("ASSESSMENT_LC_STAGE_ID", DbType = GenericDbType.Decimal)]
		protected decimal assessmentLcStageId;

		[BoundColumn("TYPE", DbType = GenericDbType.Varchar)]
		protected string type;

		[BoundColumn("TITLE", DbType = GenericDbType.Nvarchar)]
        [PhraseMapping(DxPhraseTypeCategory.ListOfValuesStandard, "DXDIR_BUSINESS_COST.TITLE", PhraseMappingAttribute.ApplyToQueryMode.NotInSelect)]
		protected string title;

		[BoundColumn("SORT_ORDER", DbType = GenericDbType.Int)]
		protected decimal sortOrder;

		[BoundColumn("COST", DbType = GenericDbType.Decimal)]
		protected NullableDecimal cost;

		#endregion

		#region Properties

		[BoundProperty(new string[] { nameof(id) })]
		public decimal Id
		{
			get { return id; }
		}

		[BoundProperty(new string[] { nameof(assessmentCode) })]
		public string AssessmentCode
		{
			get { return assessmentCode; }
			set { Change(x => assessmentCode = x, value); }
		}

		[BoundProperty(new string[] { nameof(assessmentLcStageId) })]
		public decimal AssessmentLcStageId
		{
			get { return assessmentLcStageId; }
			set { Change(x => assessmentLcStageId = x, value); }
		}

		[BoundProperty(new string[] { nameof(title) })]
		public string Title
		{
			get { return title; }
			set { Change(x => title = x, value); }
		}

		[BoundProperty(new string[] { nameof(sortOrder) })]
		public decimal SortOrder
		{
			get { return sortOrder; }
			set { Change(x => sortOrder = x, value); }
		}

        [BoundProperty(new string[] { nameof(cost) })]
        public NullableDecimal Cost
        {
            get { return cost; }
            set { Change(x => cost = x, value); }
        }

        public string TitleDescription
        {
            get
            {
                DxPhraseText phraseText;

                if (DxUser.CurrentUser != null)
                    phraseText = DxPhraseText.GetBest(DxPhraseTypeCategory.ListOfValuesStandard, "DXDIR_BUSINESS_COST.TITLE", Title, DxUser.CurrentUser.ProgramCulture);
                else
                    phraseText = DxPhraseText.GetBest(DxPhraseTypeCategory.ListOfValuesStandard, "DXDIR_BUSINESS_COST.TITLE", Title, (DxCulture)null);

                return phraseText.Text;
            }
        }

        #endregion

        #region Constructors

        public DxBusinessCost() : base()
		{
			AutogeneratedIdentityKey = true;
		}

		public DxBusinessCost(decimal id) : this(id, false)
		{

		}

		public DxBusinessCost(decimal id, bool load) : this()
		{
			this.id = id;

			if (load)
				Load();
		}

		#endregion

		#region Overrides

		protected override bool SetNextIdentityKeyDirect()
		{
			var bizDsObj = new BizDsBusinessCost();
			SetIdentityKeyValues(new object[] { bizDsObj.GetNextId() });

			return true;
		}

		#endregion

		#region Configuration

		protected override void OnConfigure()
		{
			base.OnConfigure();
			Configure();
		}

		private void Configure()
		{
			ReadConfigurationElement(configElementName);
		}

		#endregion

		#region Static methods

		public static decimal WasteCollectionTreatment(string assessmentCode, decimal assessmentLcStageId)
		{
			BizDsBusinessCost bizDs = new BizDsBusinessCost();
			return bizDs.WasteCollectionTreatment(assessmentCode, assessmentLcStageId);
		}

		#endregion Static methods
	}
}
