using Selerant.ApplicationBlocks.Data;
using Selerant.DevEx.BusinessLayer;
using System;
using System.Collections.Generic;
using System.Xml.Serialization;

namespace Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentResults
{
    [Serializable]
    [IsDxObject]
    [BoundTable(typeof(BizDsAssessmentResult), TableName = "DXDIR_RESULT")]
    public partial class DxAssessmentResult : DxObject
    {
        #region Constants

        private const string configElementName = "dxAssessmentResult";

        #endregion

        #region Fields

        [BoundColumn("ID", true, 0, DbType = GenericDbType.Decimal)]
        protected decimal id;

        [BoundColumn("ASSESSMENT_CODE", DbType = GenericDbType.Varchar)]
        protected string assessmentCode;

        [BoundColumn("ASSESSMENT_LC_STAGE_ID", DbType = GenericDbType.Decimal)]
        protected decimal assessmentLcStageId;

        [BoundColumn("RESULT_ROW_ID", DbType = GenericDbType.Decimal)]
        protected decimal resultRowId;

        [BoundColumn("RESULT", DbType = GenericDbType.Decimal)]
        protected decimal result;

        [XmlIgnore]
        protected DxAssessmentResultRow resultRow;

        #endregion

        #region Properties

        [BoundProperty(new string[] { nameof(id) })]
        public decimal Id
        {
            get { return id; }
        }

        [BoundProperty(new string[] { nameof(assessmentCode) })]
        public string AssessmentCode
        {
            get { return assessmentCode; }
            set { Change(x => assessmentCode = x, value); }
        }

        [BoundProperty(new string[] { nameof(assessmentLcStageId) })]
        public decimal AssessmentLcStageId
        {
            get { return assessmentLcStageId; }
            set { Change(x => assessmentLcStageId = x, value); }
        }

        [BoundProperty(new string[] { nameof(resultRowId) })]
        public decimal ResultRowId
        {
            get { return resultRowId; }
            set { Change(x => resultRowId = x, value); }
        }

        [BoundProperty(new string[] { nameof(result) })]
        public decimal Result
        {
            get { return result; }
            set { Change(x => result = x, value); }
        }

        [BoundRelation(new string[] { nameof(resultRowId) }, new string[] { "id" })]
        [IncludeInDeepOperations]
        public DxAssessmentResultRow ResultRow
        {
            get
            {
                if (resultRow == null && resultRowId > 0)
                    resultRow = new DxAssessmentResultRow(resultRowId);

                return resultRow;
            }
            set
            {
                Change(x => resultRow = x, value);
                resultRowId = (value == null) ? decimal.MinusOne : value.Id;
            }
        }

        #endregion

        #region Constructor

        public DxAssessmentResult() : base()
        {
            AutogeneratedIdentityKey = true;
        }

        public DxAssessmentResult(decimal id): this(id, false)
        {

        }

        public DxAssessmentResult(decimal id, bool load)
        {
            this.id = id;

            if (load)
                Load();
        }

        #endregion

        #region Overrides

        protected override bool SetNextIdentityKeyDirect()
        {
            var bizDsObj = new BizDsAssessmentResult();
            SetIdentityKeyValues(new object[] { bizDsObj.GetNextId() });

            return true;
        }

        protected override void OnConfigure()
        {
            base.OnConfigure();
            Configure();
        }

        private void Configure()
        {
            ReadConfigurationElement(configElementName);
        }

        #endregion
    }
}
