CREATE OR REPLACE PACKAGE DXDIR_PK_BUSINESS_COST AS

	TYPE t_cursor IS REF CURSOR;

	PROCEDURE InsertRecord
	(
		dcID NUMBER,
		sASSESSMENT_CODE VARCHAR2,
		dcASSESSMENT_LC_STAGE_ID NUMBER,
		sTYPE VARCHAR2,
		sTITLE NVARCHAR2,
		dcSORT_ORDER NUMBER,
		dcCOST NUMBER
	);

	PROCEDURE UpdateRecord
	(
		dcID NUMBER,
		sASSESSMENT_CODE VARCHAR2,
		dcASSESSMENT_LC_STAGE_ID NUMBER,
		sTYPE VARCHAR2,
		sTITLE NVARCHAR2,
		dcSORT_ORDER NUMBER,
		dcCOST NUMBER
	);

	PROCEDURE DeleteRecord
	(
		dcID NUMBER
	);

	PROCEDURE GetNextId
	(
        dcNextID OUT NUMBER
    );

	PROCEDURE GetBusinessCostGridItems
	(
		sASSESSMENT_CODE VARCHAR2,
		dcASSESSMENT_LC_STAGE_ID NUMBER,
		po_cur IN OUT t_cursor
	);

END;
/

CREATE OR REPLACE PACKAGE BODY DXDIR_PK_BUSINESS_COST AS

	PROCEDURE InsertRecord
	(
		dcID NUMBER,
		sASSESSMENT_CODE VARCHAR2,
		dcASSESSMENT_LC_STAGE_ID NUMBER,
		sTYPE VARCHAR2,
		sTITLE NVARCHAR2,
		dcSORT_ORDER NUMBER,
		dcCOST NUMBER
	)
	IS
	BEGIN
		INSERT INTO DXDIR_BUSINESS_COST
		(
			ID,
			ASSESSMENT_CODE,
			ASSESSMENT_LC_STAGE_ID,
			TYPE,
			TITLE,
			SORT_ORDER,
			COST
		)
		VALUES
		(
			dcID,
			sASSESSMENT_CODE,
			dcASSESSMENT_LC_STAGE_ID,
			sTYPE,
			sTITLE,
			dcSORT_ORDER,
			dcCOST
		);
	END;

	PROCEDURE UpdateRecord
	(
		dcID NUMBER,
		sASSESSMENT_CODE VARCHAR2,
		dcASSESSMENT_LC_STAGE_ID NUMBER,
		sTYPE VARCHAR2,
		sTITLE NVARCHAR2,
		dcSORT_ORDER NUMBER,
		dcCOST NUMBER
	)
	IS
	BEGIN
		UPDATE DXDIR_BUSINESS_COST
		SET 
			ASSESSMENT_CODE = sASSESSMENT_CODE,
			ASSESSMENT_LC_STAGE_ID = dcASSESSMENT_LC_STAGE_ID,
			TYPE = sTYPE,
			TITLE = sTITLE,
			SORT_ORDER = dcSORT_ORDER,
			COST = dcCOST
		WHERE 
			ID = dcID;
	END;

	PROCEDURE DeleteRecord
	(
		dcID NUMBER
	)
	IS
	BEGIN
		DELETE FROM DXDIR_BUSINESS_COST
		WHERE 
			ID = dcID;
	END;

	PROCEDURE GetNextId
	(
        dcNextID OUT NUMBER
    )
	IS
	BEGIN
		SELECT DXDIR_BUSINESS_COST_SEQ.NEXTVAL INTO dcNextID FROM DUAL;
	END;

	PROCEDURE GetBusinessCostGridItems
	(
		sASSESSMENT_CODE VARCHAR2,
		dcASSESSMENT_LC_STAGE_ID NUMBER,
		po_cur IN OUT t_cursor
	)
	IS
		totalMass NUMBER(25, 3);
		factor NUMBER(25, 12);
		coProductMargin NUMBER(25, 12);
		coProductWeight	NUMBER(25, 3);
		foodRescueMargin NUMBER(25, 12);
		foodRescueWeight NUMBER(25, 3);
        outputRevenueFactor NUMBER(25, 14);

		COPRODUCT_OUTPUT_CATEGORY_ID NUMBER := 2;
		FOOD_RESCUE_OUTPUT_CATEGORY_ID NUMBER := 3;
	BEGIN
		DXDIR_PK_CALCULATIONS.GetTotalMass(sASSESSMENT_CODE, dcASSESSMENT_LC_STAGE_ID, totalMass);

		IF (totalMass = 0)
		THEN
			factor := 0;
            outputRevenueFactor := 0;
		ELSE
			-- massOfWaste / totalInputMass
			SELECT ROUND((NVL(SUM(WEIGHT), 0) / totalMass), 12)
			INTO factor
			FROM DXDIR_OUTPUT
			WHERE ASSESSMENT_CODE = sASSESSMENT_CODE
			  AND ASSESSMENT_LC_STAGE_ID = dcASSESSMENT_LC_STAGE_ID
			  AND OUTPUT_CATEGORY_ID <> 1;
              
            outputRevenueFactor := DXDIR_PK_CALCULATIONS.GetOutputRevenueFactor(sASSESSMENT_CODE, dcASSESSMENT_LC_STAGE_ID, totalMass);
		END IF;

		DXDIR_PK_CALCULATIONS.GetMargin(sASSESSMENT_CODE, dcASSESSMENT_LC_STAGE_ID, COPRODUCT_OUTPUT_CATEGORY_ID, coProductMargin);
		DXDIR_PK_CALCULATIONS.GetMargin(sASSESSMENT_CODE, dcASSESSMENT_LC_STAGE_ID, FOOD_RESCUE_OUTPUT_CATEGORY_ID, foodRescueMargin);
        
		BEGIN
			SELECT SUM(NVL(WEIGHT, 0))
			INTO coProductWeight
			FROM DXDIR_OUTPUT
			WHERE ASSESSMENT_CODE		 = sASSESSMENT_CODE			AND
				  ASSESSMENT_LC_STAGE_ID = dcASSESSMENT_LC_STAGE_ID	AND
				  OUTPUT_CATEGORY_ID	 = COPRODUCT_OUTPUT_CATEGORY_ID;
		EXCEPTION
			WHEN NO_DATA_FOUND THEN
				coProductWeight := 0;
		END;

		BEGIN
			SELECT NVL(WEIGHT, 0)
			INTO foodRescueWeight
			FROM DXDIR_OUTPUT
			WHERE ASSESSMENT_CODE		 = sASSESSMENT_CODE			AND
				  ASSESSMENT_LC_STAGE_ID = dcASSESSMENT_LC_STAGE_ID	AND
				  OUTPUT_CATEGORY_ID	 = FOOD_RESCUE_OUTPUT_CATEGORY_ID;
		EXCEPTION
			WHEN NO_DATA_FOUND THEN
				foodRescueWeight := 0;
		END;

		BEGIN
			OPEN po_cur FOR
				SELECT 
				   ID,
				   ASSESSMENT_CODE,
				   ASSESSMENT_LC_STAGE_ID,
				   TYPE,
				   TITLE,
				   SORT_ORDER,
				   COST,
				   DXDIR_PK_CALCULATIONS.GetWasteRelatedCost(totalMass, factor, COST, coProductMargin, coProductWeight, foodRescueMargin, foodRescueWeight, outputRevenueFactor) AS WASTE_COST
			  FROM DXDIR_BUSINESS_COST 
			  WHERE ASSESSMENT_CODE		   = sASSESSMENT_CODE	AND
					ASSESSMENT_LC_STAGE_ID = dcASSESSMENT_LC_STAGE_ID;
		EXCEPTION
			WHEN NO_DATA_FOUND THEN
            RETURN;
		END;
	END;
END;
/
