// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using Autofac;
using Selerant.DevEx.Infrastructure;
using Selerant.Infrastructure.DependencyContainer;
using T4MVC_DIR;
using Selerant.DevEx.Modules.DIRModule.ModuleBlocks._ThisProject;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd._ThisProject;
using Selerant.DevEx.Infrastructure.Modules;
namespace Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers
{
    public partial class AssessmentResultsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AssessmentResultsController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AssessmentResultsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetAssessmentResults()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetAssessmentResults);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetFoodWasteDestinationData()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetFoodWasteDestinationData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetCostOfWasteData()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCostOfWasteData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult AssessmentDashboard()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.AssessmentDashboard);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult ExportResults()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.ExportResults);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult RefreshResultsGrid()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.RefreshResultsGrid);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult RefreshFoodWastePerDestinationGrid()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.RefreshFoodWastePerDestinationGrid);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult RefreshCostOfWasteGrid()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.RefreshCostOfWasteGrid);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult RefreshCharts()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.RefreshCharts);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult IndexDirect()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.IndexDirect);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult Index()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult ExcuteReport()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.ExcuteReport);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetPanelGridData()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetPanelGridData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult GetPanelExportData()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.GetPanelExportData);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SecuritySettingsOnPanelEntity()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SecuritySettingsOnPanelEntity);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult<Selerant.DevEx.WebPages.OpenDialogSettings.Data> GetOpenDialogSettings()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data(Area, Name, ActionNames.GetOpenDialogSettings);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AssessmentResultsController Actions { get { return MVC_DIR.AssessmentNavigator.AssessmentResults; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "AssessmentNavigator";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "AssessmentResults";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "AssessmentResults";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string GetAssessmentResults = "GetAssessmentResults";
            public readonly string GetFoodWasteDestinationData = "GetFoodWasteDestinationData";
            public readonly string GetCostOfWasteData = "GetCostOfWasteData";
            public readonly string AssessmentDashboard = "AssessmentDashboard";
            public readonly string ExportResults = "ExportResults";
            public readonly string RefreshResultsGrid = "RefreshResultsGrid";
            public readonly string RefreshFoodWastePerDestinationGrid = "RefreshFoodWastePerDestinationGrid";
            public readonly string RefreshCostOfWasteGrid = "RefreshCostOfWasteGrid";
            public readonly string RefreshCharts = "RefreshCharts";
            public readonly string IndexDirect = "IndexDirect";
            public readonly string Index = "Index";
            public readonly string ExcuteReport = "ExcuteReport";
            public readonly string GetPanelGridData = "GetPanelGridData";
            public readonly string GetPanelExportData = "GetPanelExportData";
            public readonly string SecuritySettingsOnPanelEntity = "SecuritySettingsOnPanelEntity";
            public readonly string GetOpenDialogSettings = "GetOpenDialogSettings";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string GetAssessmentResults = "GetAssessmentResults";
            public const string GetFoodWasteDestinationData = "GetFoodWasteDestinationData";
            public const string GetCostOfWasteData = "GetCostOfWasteData";
            public const string AssessmentDashboard = "AssessmentDashboard";
            public const string ExportResults = "ExportResults";
            public const string RefreshResultsGrid = "RefreshResultsGrid";
            public const string RefreshFoodWastePerDestinationGrid = "RefreshFoodWastePerDestinationGrid";
            public const string RefreshCostOfWasteGrid = "RefreshCostOfWasteGrid";
            public const string RefreshCharts = "RefreshCharts";
            public const string IndexDirect = "IndexDirect";
            public const string Index = "Index";
            public const string ExcuteReport = "ExcuteReport";
            public const string GetPanelGridData = "GetPanelGridData";
            public const string GetPanelExportData = "GetPanelExportData";
            public const string SecuritySettingsOnPanelEntity = "SecuritySettingsOnPanelEntity";
            public const string GetOpenDialogSettings = "GetOpenDialogSettings";
        }


        static readonly ActionParamsClass_GetAssessmentResults s_params_GetAssessmentResults = new ActionParamsClass_GetAssessmentResults();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAssessmentResults GetAssessmentResultsParams { get { return s_params_GetAssessmentResults; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAssessmentResults
        {
            public readonly string controllerData = "controllerData";
            public readonly string lcStage = "lcStage";
            public readonly string resultType = "resultType";
            public readonly string loadData = "loadData";
        }
        static readonly ActionParamsClass_GetFoodWasteDestinationData s_params_GetFoodWasteDestinationData = new ActionParamsClass_GetFoodWasteDestinationData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetFoodWasteDestinationData GetFoodWasteDestinationDataParams { get { return s_params_GetFoodWasteDestinationData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetFoodWasteDestinationData
        {
            public readonly string controllerData = "controllerData";
            public readonly string lcStage = "lcStage";
            public readonly string loadData = "loadData";
        }
        static readonly ActionParamsClass_GetCostOfWasteData s_params_GetCostOfWasteData = new ActionParamsClass_GetCostOfWasteData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCostOfWasteData GetCostOfWasteDataParams { get { return s_params_GetCostOfWasteData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCostOfWasteData
        {
            public readonly string controllerData = "controllerData";
            public readonly string lcStage = "lcStage";
            public readonly string loadData = "loadData";
        }
        static readonly ActionParamsClass_AssessmentDashboard s_params_AssessmentDashboard = new ActionParamsClass_AssessmentDashboard();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AssessmentDashboard AssessmentDashboardParams { get { return s_params_AssessmentDashboard; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AssessmentDashboard
        {
            public readonly string controllerData = "controllerData";
            public readonly string objectIdentifiableString = "objectIdentifiableString";
        }
        static readonly ActionParamsClass_ExportResults s_params_ExportResults = new ActionParamsClass_ExportResults();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExportResults ExportResultsParams { get { return s_params_ExportResults; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExportResults
        {
            public readonly string controllerData = "controllerData";
            public readonly string lcStage = "lcStage";
        }
        static readonly ActionParamsClass_RefreshResultsGrid s_params_RefreshResultsGrid = new ActionParamsClass_RefreshResultsGrid();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RefreshResultsGrid RefreshResultsGridParams { get { return s_params_RefreshResultsGrid; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RefreshResultsGrid
        {
            public readonly string controllerData = "controllerData";
            public readonly string lcStage = "lcStage";
            public readonly string resultType = "resultType";
        }
        static readonly ActionParamsClass_RefreshFoodWastePerDestinationGrid s_params_RefreshFoodWastePerDestinationGrid = new ActionParamsClass_RefreshFoodWastePerDestinationGrid();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RefreshFoodWastePerDestinationGrid RefreshFoodWastePerDestinationGridParams { get { return s_params_RefreshFoodWastePerDestinationGrid; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RefreshFoodWastePerDestinationGrid
        {
            public readonly string controllerData = "controllerData";
            public readonly string lcStage = "lcStage";
        }
        static readonly ActionParamsClass_RefreshCostOfWasteGrid s_params_RefreshCostOfWasteGrid = new ActionParamsClass_RefreshCostOfWasteGrid();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RefreshCostOfWasteGrid RefreshCostOfWasteGridParams { get { return s_params_RefreshCostOfWasteGrid; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RefreshCostOfWasteGrid
        {
            public readonly string controllerData = "controllerData";
            public readonly string lcStage = "lcStage";
        }
        static readonly ActionParamsClass_RefreshCharts s_params_RefreshCharts = new ActionParamsClass_RefreshCharts();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RefreshCharts RefreshChartsParams { get { return s_params_RefreshCharts; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RefreshCharts
        {
            public readonly string controllerData = "controllerData";
            public readonly string lcStage = "lcStage";
        }
        static readonly ActionParamsClass_IndexDirect s_params_IndexDirect = new ActionParamsClass_IndexDirect();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IndexDirect IndexDirectParams { get { return s_params_IndexDirect; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IndexDirect
        {
            public readonly string identifiableString = "identifiableString";
            public readonly string tabId = "tabId";
            public readonly string mode = "mode";
        }
        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string data = "data";
        }
        static readonly ActionParamsClass_ExcuteReport s_params_ExcuteReport = new ActionParamsClass_ExcuteReport();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExcuteReport ExcuteReportParams { get { return s_params_ExcuteReport; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExcuteReport
        {
            public readonly string controllerData = "controllerData";
            public readonly string rowEntityIdentifiableString = "rowEntityIdentifiableString";
        }
        static readonly ActionParamsClass_GetPanelGridData s_params_GetPanelGridData = new ActionParamsClass_GetPanelGridData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPanelGridData GetPanelGridDataParams { get { return s_params_GetPanelGridData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPanelGridData
        {
            public readonly string controllerData = "controllerData";
            public readonly string clientGridRequest = "clientGridRequest";
        }
        static readonly ActionParamsClass_GetPanelExportData s_params_GetPanelExportData = new ActionParamsClass_GetPanelExportData();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPanelExportData GetPanelExportDataParams { get { return s_params_GetPanelExportData; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPanelExportData
        {
            public readonly string controllerData = "controllerData";
            public readonly string exportSettings = "exportSettings";
        }
        static readonly ActionParamsClass_SecuritySettingsOnPanelEntity s_params_SecuritySettingsOnPanelEntity = new ActionParamsClass_SecuritySettingsOnPanelEntity();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SecuritySettingsOnPanelEntity SecuritySettingsOnPanelEntityParams { get { return s_params_SecuritySettingsOnPanelEntity; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SecuritySettingsOnPanelEntity
        {
            public readonly string requestData = "requestData";
            public readonly string identifiableString = "identifiableString";
        }
        static readonly ActionParamsClass_GetOpenDialogSettings s_params_GetOpenDialogSettings = new ActionParamsClass_GetOpenDialogSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOpenDialogSettings GetOpenDialogSettingsParams { get { return s_params_GetOpenDialogSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOpenDialogSettings
        {
            public readonly string originalActionName = "originalActionName";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AssessmentResults = "AssessmentResults";
                public readonly string Index = "Index";
            }
            public readonly string AssessmentResults = "~/Areas/AssessmentNavigator/Views/AssessmentResults/AssessmentResults.ts";
            public readonly string Index = "~/Areas/AssessmentNavigator/Views/AssessmentResults/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AssessmentResultsController : Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.AssessmentResultsController
    {
        public T4MVC_AssessmentResultsController() : base(Dummy.Instance) { }

        [NonAction]
        partial void GetAssessmentResultsOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal lcStage, string resultType, bool loadData);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetAssessmentResults(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal lcStage, string resultType, bool loadData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetAssessmentResults);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lcStage", lcStage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "resultType", resultType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "loadData", loadData);
            GetAssessmentResultsOverride(callInfo, controllerData, lcStage, resultType, loadData);
            return callInfo;
        }

        [NonAction]
        partial void GetFoodWasteDestinationDataOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal lcStage, bool loadData);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetFoodWasteDestinationData(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal lcStage, bool loadData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetFoodWasteDestinationData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lcStage", lcStage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "loadData", loadData);
            GetFoodWasteDestinationDataOverride(callInfo, controllerData, lcStage, loadData);
            return callInfo;
        }

        [NonAction]
        partial void GetCostOfWasteDataOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal lcStage, bool loadData);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetCostOfWasteData(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal lcStage, bool loadData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCostOfWasteData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lcStage", lcStage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "loadData", loadData);
            GetCostOfWasteDataOverride(callInfo, controllerData, lcStage, loadData);
            return callInfo;
        }

        [NonAction]
        partial void AssessmentDashboardOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string objectIdentifiableString);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult AssessmentDashboard(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string objectIdentifiableString)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.AssessmentDashboard);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "objectIdentifiableString", objectIdentifiableString);
            AssessmentDashboardOverride(callInfo, controllerData, objectIdentifiableString);
            return callInfo;
        }

        [NonAction]
        partial void ExportResultsOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal lcStage);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult ExportResults(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal lcStage)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.ExportResults);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lcStage", lcStage);
            ExportResultsOverride(callInfo, controllerData, lcStage);
            return callInfo;
        }

        [NonAction]
        partial void RefreshResultsGridOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal lcStage, string resultType);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult RefreshResultsGrid(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal lcStage, string resultType)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.RefreshResultsGrid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lcStage", lcStage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "resultType", resultType);
            RefreshResultsGridOverride(callInfo, controllerData, lcStage, resultType);
            return callInfo;
        }

        [NonAction]
        partial void RefreshFoodWastePerDestinationGridOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal lcStage);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult RefreshFoodWastePerDestinationGrid(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal lcStage)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.RefreshFoodWastePerDestinationGrid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lcStage", lcStage);
            RefreshFoodWastePerDestinationGridOverride(callInfo, controllerData, lcStage);
            return callInfo;
        }

        [NonAction]
        partial void RefreshCostOfWasteGridOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal lcStage);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult RefreshCostOfWasteGrid(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal lcStage)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.RefreshCostOfWasteGrid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lcStage", lcStage);
            RefreshCostOfWasteGridOverride(callInfo, controllerData, lcStage);
            return callInfo;
        }

        [NonAction]
        partial void RefreshChartsOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal lcStage);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult RefreshCharts(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, decimal lcStage)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.RefreshCharts);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lcStage", lcStage);
            RefreshChartsOverride(callInfo, controllerData, lcStage);
            return callInfo;
        }

        [NonAction]
        partial void IndexDirectOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, string identifiableString, string tabId, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorModel.Modes mode);

        [NonAction]
        public override System.Web.Mvc.ViewResult IndexDirect(string identifiableString, string tabId, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorModel.Modes mode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.IndexDirect);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tabId", tabId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mode", mode);
            IndexDirectOverride(callInfo, identifiableString, tabId, mode);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Controllers.DevExNavigatorPanelController.IndexActionNavigatorPanelControllerData data);

        [NonAction]
        public override System.Web.Mvc.ViewResult Index(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Controllers.DevExNavigatorPanelController.IndexActionNavigatorPanelControllerData data)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            IndexOverride(callInfo, data);
            return callInfo;
        }

        [NonAction]
        partial void ExcuteReportOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string rowEntityIdentifiableString);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult ExcuteReport(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, string rowEntityIdentifiableString)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.ExcuteReport);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "rowEntityIdentifiableString", rowEntityIdentifiableString);
            ExcuteReportOverride(callInfo, controllerData, rowEntityIdentifiableString);
            return callInfo;
        }

        [NonAction]
        partial void GetPanelGridDataOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, Selerant.DevEx.WebMvcModules.Helpers.jqGrid.GridSettings clientGridRequest);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetPanelGridData(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, Selerant.DevEx.WebMvcModules.Helpers.jqGrid.GridSettings clientGridRequest)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetPanelGridData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "clientGridRequest", clientGridRequest);
            GetPanelGridDataOverride(callInfo, controllerData, clientGridRequest);
            return callInfo;
        }

        [NonAction]
        partial void GetPanelExportDataOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, Selerant.DevEx.WebMvcModules.Infrastructure.Controls.Menu.MenuHelper.GridExportSettings exportSettings);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult GetPanelExportData(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> controllerData, Selerant.DevEx.WebMvcModules.Infrastructure.Controls.Menu.MenuHelper.GridExportSettings exportSettings)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.GetPanelExportData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "exportSettings", exportSettings);
            GetPanelExportDataOverride(callInfo, controllerData, exportSettings);
            return callInfo;
        }

        [NonAction]
        partial void SecuritySettingsOnPanelEntityOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> requestData, string identifiableString);

        [NonAction]
        public override System.Web.Mvc.ActionResult SecuritySettingsOnPanelEntity(Selerant.DevEx.WebMvcModules.Infrastructure.Navigators.Models.NavigatorPanelControllerData<Selerant.DevEx.Modules.DIRModule.BackEnd.AssessmentManagement.BusinessObjects.DxAssessment> requestData, string identifiableString)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SecuritySettingsOnPanelEntity);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "requestData", requestData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            SecuritySettingsOnPanelEntityOverride(callInfo, requestData, identifiableString);
            return callInfo;
        }

        [NonAction]
        partial void GetOpenDialogSettingsOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data callInfo, string originalActionName);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult<Selerant.DevEx.WebPages.OpenDialogSettings.Data> GetOpenDialogSettings(string originalActionName)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data(Area, Name, ActionNames.GetOpenDialogSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "originalActionName", originalActionName);
            GetOpenDialogSettingsOverride(callInfo, originalActionName);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
