// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using Autofac;
using Selerant.DevEx.Infrastructure;
using Selerant.Infrastructure.DependencyContainer;
using T4MVC_DIR;
using Selerant.DevEx.Modules.DIRModule.ModuleBlocks._ThisProject;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd._ThisProject;
using Selerant.DevEx.Infrastructure.Modules;
namespace Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers
{
    public partial class AssessmentRecentSearchPanelController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AssessmentRecentSearchPanelController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AssessmentRecentSearchPanelController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetItemsList()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetItemsList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult GetPanelDirect()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetPanelDirect);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult Index()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult GetPanel()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetPanel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult GetPanelModelInclude()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetPanelModelInclude);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult LoadOnDemandPanel()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.LoadOnDemandPanel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult BeforeClosingSearchDialog()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.BeforeClosingSearchDialog);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult<Selerant.DevEx.WebPages.OpenDialogSettings.Data> GetOpenDialogSettings()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data(Area, Name, ActionNames.GetOpenDialogSettings);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AssessmentRecentSearchPanelController Actions { get { return MVC_DIR.AssessmentSearch.AssessmentRecentSearchPanel; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "AssessmentSearch";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "AssessmentRecentSearchPanel";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "AssessmentRecentSearchPanel";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string GetItemsList = "GetItemsList";
            public readonly string GetPanelDirect = "GetPanelDirect";
            public readonly string Index = "Index";
            public readonly string GetPanel = "GetPanel";
            public readonly string GetPanelModelInclude = "GetPanelModelInclude";
            public readonly string LoadOnDemandPanel = "LoadOnDemandPanel";
            public readonly string BeforeClosingSearchDialog = "BeforeClosingSearchDialog";
            public readonly string GetOpenDialogSettings = "GetOpenDialogSettings";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string GetItemsList = "GetItemsList";
            public const string GetPanelDirect = "GetPanelDirect";
            public const string Index = "Index";
            public const string GetPanel = "GetPanel";
            public const string GetPanelModelInclude = "GetPanelModelInclude";
            public const string LoadOnDemandPanel = "LoadOnDemandPanel";
            public const string BeforeClosingSearchDialog = "BeforeClosingSearchDialog";
            public const string GetOpenDialogSettings = "GetOpenDialogSettings";
        }


        static readonly ActionParamsClass_GetItemsList s_params_GetItemsList = new ActionParamsClass_GetItemsList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetItemsList GetItemsListParams { get { return s_params_GetItemsList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetItemsList
        {
            public readonly string data = "data";
            public readonly string clientGridRequest = "clientGridRequest";
            public readonly string navigationNodeId = "navigationNodeId";
            public readonly string isDialog = "isDialog";
            public readonly string nodeId = "nodeId";
        }
        static readonly ActionParamsClass_GetPanelDirect s_params_GetPanelDirect = new ActionParamsClass_GetPanelDirect();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPanelDirect GetPanelDirectParams { get { return s_params_GetPanelDirect; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPanelDirect
        {
            public readonly string data = "data";
            public readonly string tab = "tab";
            public readonly string id = "id";
            public readonly string isDialog = "isDialog";
            public readonly string filters = "filters";
        }
        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string data = "data";
            public readonly string searchController = "searchController";
            public readonly string nodeId = "nodeId";
        }
        static readonly ActionParamsClass_GetPanel s_params_GetPanel = new ActionParamsClass_GetPanel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPanel GetPanelParams { get { return s_params_GetPanel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPanel
        {
            public readonly string data = "data";
            public readonly string searchController = "searchController";
            public readonly string nodeId = "nodeId";
        }
        static readonly ActionParamsClass_GetPanelModelInclude s_params_GetPanelModelInclude = new ActionParamsClass_GetPanelModelInclude();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPanelModelInclude GetPanelModelIncludeParams { get { return s_params_GetPanelModelInclude; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPanelModelInclude
        {
            public readonly string data = "data";
            public readonly string panelModel = "panelModel";
        }
        static readonly ActionParamsClass_LoadOnDemandPanel s_params_LoadOnDemandPanel = new ActionParamsClass_LoadOnDemandPanel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LoadOnDemandPanel LoadOnDemandPanelParams { get { return s_params_LoadOnDemandPanel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LoadOnDemandPanel
        {
            public readonly string data = "data";
            public readonly string dataModel = "dataModel";
        }
        static readonly ActionParamsClass_BeforeClosingSearchDialog s_params_BeforeClosingSearchDialog = new ActionParamsClass_BeforeClosingSearchDialog();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BeforeClosingSearchDialog BeforeClosingSearchDialogParams { get { return s_params_BeforeClosingSearchDialog; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BeforeClosingSearchDialog
        {
            public readonly string data = "data";
            public readonly string identifiableStrings = "identifiableStrings";
        }
        static readonly ActionParamsClass_GetOpenDialogSettings s_params_GetOpenDialogSettings = new ActionParamsClass_GetOpenDialogSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOpenDialogSettings GetOpenDialogSettingsParams { get { return s_params_GetOpenDialogSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOpenDialogSettings
        {
            public readonly string originalActionName = "originalActionName";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AssessmentRecentSearchPanelController : Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.AssessmentRecentSearchPanelController
    {
        public T4MVC_AssessmentRecentSearchPanelController() : base(Dummy.Instance) { }

        [NonAction]
        partial void GetItemsListOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Helpers.jqGrid.GridSettings clientGridRequest, string navigationNodeId, bool isDialog, string nodeId);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetItemsList(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Helpers.jqGrid.GridSettings clientGridRequest, string navigationNodeId, bool isDialog, string nodeId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetItemsList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "clientGridRequest", clientGridRequest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "navigationNodeId", navigationNodeId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isDialog", isDialog);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nodeId", nodeId);
            GetItemsListOverride(callInfo, data, clientGridRequest, navigationNodeId, isDialog, nodeId);
            return callInfo;
        }

        [NonAction]
        partial void GetPanelDirectOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string tab, string id, bool isDialog, string filters);

        [NonAction]
        public override System.Web.Mvc.ViewResult GetPanelDirect(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string tab, string id, bool isDialog, string filters)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetPanelDirect);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tab", tab);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isDialog", isDialog);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filters", filters);
            GetPanelDirectOverride(callInfo, data, tab, id, isDialog, filters);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.ISearchController searchController, string nodeId);

        [NonAction]
        public override System.Web.Mvc.ViewResult Index(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.ISearchController searchController, string nodeId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchController", searchController);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nodeId", nodeId);
            IndexOverride(callInfo, data, searchController, nodeId);
            return callInfo;
        }

        [NonAction]
        partial void GetPanelOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.ISearchController searchController, string nodeId);

        [NonAction]
        public override System.Web.Mvc.ViewResult GetPanel(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.ISearchController searchController, string nodeId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetPanel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchController", searchController);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nodeId", nodeId);
            GetPanelOverride(callInfo, data, searchController, nodeId);
            return callInfo;
        }

        [NonAction]
        partial void GetPanelModelIncludeOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.DevExSearchPanelIndexModel panelModel);

        [NonAction]
        public override System.Web.Mvc.ViewResult GetPanelModelInclude(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.DevExSearchPanelIndexModel panelModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetPanelModelInclude);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "panelModel", panelModel);
            GetPanelModelIncludeOverride(callInfo, data, panelModel);
            return callInfo;
        }

        [NonAction]
        partial void LoadOnDemandPanelOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchLoadOnDemandDataModel dataModel);

        [NonAction]
        public override System.Web.Mvc.ViewResult LoadOnDemandPanel(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchLoadOnDemandDataModel dataModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.LoadOnDemandPanel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dataModel", dataModel);
            LoadOnDemandPanelOverride(callInfo, data, dataModel);
            return callInfo;
        }

        [NonAction]
        partial void BeforeClosingSearchDialogOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string[] identifiableStrings);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult BeforeClosingSearchDialog(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string[] identifiableStrings)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.BeforeClosingSearchDialog);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableStrings", identifiableStrings);
            BeforeClosingSearchDialogOverride(callInfo, data, identifiableStrings);
            return callInfo;
        }

        [NonAction]
        partial void GetOpenDialogSettingsOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data callInfo, string originalActionName);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult<Selerant.DevEx.WebPages.OpenDialogSettings.Data> GetOpenDialogSettings(string originalActionName)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data(Area, Name, ActionNames.GetOpenDialogSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "originalActionName", originalActionName);
            GetOpenDialogSettingsOverride(callInfo, originalActionName);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
