// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using Autofac;
using Selerant.DevEx.Infrastructure;
using Selerant.Infrastructure.DependencyContainer;
using T4MVC_DIR;
using Selerant.DevEx.Modules.DIRModule.ModuleBlocks._ThisProject;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd._ThisProject;
using Selerant.DevEx.Infrastructure.Modules;
namespace Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers
{
    public partial class CreateAssessmentDialogController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CreateAssessmentDialogController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected CreateAssessmentDialogController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult NewAssessmentDialogIndex()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewAssessmentDialogIndex);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult BusinessDataDialogIndex()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BusinessDataDialogIndex);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MergeInputsDialogIndex()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MergeInputsDialogIndex);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult CarryMergedProductOverToTheNextStage()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.CarryMergedProductOverToTheNextStage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult HasProductsToCarryOver()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.HasProductsToCarryOver);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult CarryProductOverToTheNextStage()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.CarryProductOverToTheNextStage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult ClearNextLcStageSource()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.ClearNextLcStageSource);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult CreateMaterial()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.CreateMaterial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult CreateNewAssessment()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.CreateNewAssessment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult CreateNewAssessmentAndCloseDialog()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.CreateNewAssessmentAndCloseDialog);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult ChangeStatusAndCloseDialog()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.ChangeStatusAndCloseDialog);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteAssessment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAssessment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult ManageAssessmentRaiseDialog()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.ManageAssessmentRaiseDialog);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LCStageStepsPartial()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LCStageStepsPartial);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult<Selerant.DevEx.WebPages.OpenDialogSettings.Data> GetOpenDialogSettings()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data(Area, Name, ActionNames.GetOpenDialogSettings);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CreateAssessmentDialogController Actions { get { return MVC_DIR.AssessmentNavigator.CreateAssessmentDialog; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "AssessmentNavigator";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "CreateAssessmentDialog";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "CreateAssessmentDialog";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string NewAssessmentDialogIndex = "NewAssessmentDialogIndex";
            public readonly string BusinessDataDialogIndex = "BusinessDataDialogIndex";
            public readonly string MergeInputsDialogIndex = "MergeInputsDialogIndex";
            public readonly string CarryMergedProductOverToTheNextStage = "CarryMergedProductOverToTheNextStage";
            public readonly string HasProductsToCarryOver = "HasProductsToCarryOver";
            public readonly string CarryProductOverToTheNextStage = "CarryProductOverToTheNextStage";
            public readonly string ClearNextLcStageSource = "ClearNextLcStageSource";
            public readonly string CreateMaterial = "CreateMaterial";
            public readonly string CreateNewAssessment = "CreateNewAssessment";
            public readonly string CreateNewAssessmentAndCloseDialog = "CreateNewAssessmentAndCloseDialog";
            public readonly string ChangeStatusAndCloseDialog = "ChangeStatusAndCloseDialog";
            public readonly string DeleteAssessment = "DeleteAssessment";
            public readonly string ManageAssessmentRaiseDialog = "ManageAssessmentRaiseDialog";
            public readonly string LCStageStepsPartial = "LCStageStepsPartial";
            public readonly string GetOpenDialogSettings = "GetOpenDialogSettings";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string NewAssessmentDialogIndex = "NewAssessmentDialogIndex";
            public const string BusinessDataDialogIndex = "BusinessDataDialogIndex";
            public const string MergeInputsDialogIndex = "MergeInputsDialogIndex";
            public const string CarryMergedProductOverToTheNextStage = "CarryMergedProductOverToTheNextStage";
            public const string HasProductsToCarryOver = "HasProductsToCarryOver";
            public const string CarryProductOverToTheNextStage = "CarryProductOverToTheNextStage";
            public const string ClearNextLcStageSource = "ClearNextLcStageSource";
            public const string CreateMaterial = "CreateMaterial";
            public const string CreateNewAssessment = "CreateNewAssessment";
            public const string CreateNewAssessmentAndCloseDialog = "CreateNewAssessmentAndCloseDialog";
            public const string ChangeStatusAndCloseDialog = "ChangeStatusAndCloseDialog";
            public const string DeleteAssessment = "DeleteAssessment";
            public const string ManageAssessmentRaiseDialog = "ManageAssessmentRaiseDialog";
            public const string LCStageStepsPartial = "LCStageStepsPartial";
            public const string GetOpenDialogSettings = "GetOpenDialogSettings";
        }


        static readonly ActionParamsClass_NewAssessmentDialogIndex s_params_NewAssessmentDialogIndex = new ActionParamsClass_NewAssessmentDialogIndex();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NewAssessmentDialogIndex NewAssessmentDialogIndexParams { get { return s_params_NewAssessmentDialogIndex; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NewAssessmentDialogIndex
        {
            public readonly string controllerData = "controllerData";
        }
        static readonly ActionParamsClass_BusinessDataDialogIndex s_params_BusinessDataDialogIndex = new ActionParamsClass_BusinessDataDialogIndex();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BusinessDataDialogIndex BusinessDataDialogIndexParams { get { return s_params_BusinessDataDialogIndex; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BusinessDataDialogIndex
        {
            public readonly string controllerData = "controllerData";
            public readonly string identifiableString = "identifiableString";
            public readonly string cancelOrCloseDeletes = "cancelOrCloseDeletes";
        }
        static readonly ActionParamsClass_MergeInputsDialogIndex s_params_MergeInputsDialogIndex = new ActionParamsClass_MergeInputsDialogIndex();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MergeInputsDialogIndex MergeInputsDialogIndexParams { get { return s_params_MergeInputsDialogIndex; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MergeInputsDialogIndex
        {
            public readonly string controllerData = "controllerData";
            public readonly string identifiableString = "identifiableString";
            public readonly string lcStageId = "lcStageId";
            public readonly string nextLcStageId = "nextLcStageId";
        }
        static readonly ActionParamsClass_CarryMergedProductOverToTheNextStage s_params_CarryMergedProductOverToTheNextStage = new ActionParamsClass_CarryMergedProductOverToTheNextStage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CarryMergedProductOverToTheNextStage CarryMergedProductOverToTheNextStageParams { get { return s_params_CarryMergedProductOverToTheNextStage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CarryMergedProductOverToTheNextStage
        {
            public readonly string controllerData = "controllerData";
            public readonly string identifiableString = "identifiableString";
            public readonly string lcStageId = "lcStageId";
            public readonly string nextLcStageId = "nextLcStageId";
            public readonly string gridParam = "gridParam";
        }
        static readonly ActionParamsClass_HasProductsToCarryOver s_params_HasProductsToCarryOver = new ActionParamsClass_HasProductsToCarryOver();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_HasProductsToCarryOver HasProductsToCarryOverParams { get { return s_params_HasProductsToCarryOver; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_HasProductsToCarryOver
        {
            public readonly string controllerData = "controllerData";
            public readonly string identifiableString = "identifiableString";
            public readonly string lcStageId = "lcStageId";
            public readonly string nextLcStageId = "nextLcStageId";
        }
        static readonly ActionParamsClass_CarryProductOverToTheNextStage s_params_CarryProductOverToTheNextStage = new ActionParamsClass_CarryProductOverToTheNextStage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CarryProductOverToTheNextStage CarryProductOverToTheNextStageParams { get { return s_params_CarryProductOverToTheNextStage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CarryProductOverToTheNextStage
        {
            public readonly string controllerData = "controllerData";
            public readonly string identifiableString = "identifiableString";
            public readonly string lcStageId = "lcStageId";
            public readonly string nextLcStageId = "nextLcStageId";
            public readonly string mergeInputs = "mergeInputs";
        }
        static readonly ActionParamsClass_ClearNextLcStageSource s_params_ClearNextLcStageSource = new ActionParamsClass_ClearNextLcStageSource();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ClearNextLcStageSource ClearNextLcStageSourceParams { get { return s_params_ClearNextLcStageSource; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ClearNextLcStageSource
        {
            public readonly string controllerData = "controllerData";
            public readonly string nextLcStageId = "nextLcStageId";
        }
        static readonly ActionParamsClass_CreateMaterial s_params_CreateMaterial = new ActionParamsClass_CreateMaterial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateMaterial CreateMaterialParams { get { return s_params_CreateMaterial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateMaterial
        {
            public readonly string controllerData = "controllerData";
            public readonly string description = "description";
            public readonly string categoryType = "categoryType";
        }
        static readonly ActionParamsClass_CreateNewAssessment s_params_CreateNewAssessment = new ActionParamsClass_CreateNewAssessment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateNewAssessment CreateNewAssessmentParams { get { return s_params_CreateNewAssessment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateNewAssessment
        {
            public readonly string controllerData = "controllerData";
            public readonly string formData = "formData";
        }
        static readonly ActionParamsClass_CreateNewAssessmentAndCloseDialog s_params_CreateNewAssessmentAndCloseDialog = new ActionParamsClass_CreateNewAssessmentAndCloseDialog();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateNewAssessmentAndCloseDialog CreateNewAssessmentAndCloseDialogParams { get { return s_params_CreateNewAssessmentAndCloseDialog; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateNewAssessmentAndCloseDialog
        {
            public readonly string controllerData = "controllerData";
            public readonly string formData = "formData";
        }
        static readonly ActionParamsClass_ChangeStatusAndCloseDialog s_params_ChangeStatusAndCloseDialog = new ActionParamsClass_ChangeStatusAndCloseDialog();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangeStatusAndCloseDialog ChangeStatusAndCloseDialogParams { get { return s_params_ChangeStatusAndCloseDialog; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangeStatusAndCloseDialog
        {
            public readonly string controllerData = "controllerData";
            public readonly string identifiableString = "identifiableString";
        }
        static readonly ActionParamsClass_DeleteAssessment s_params_DeleteAssessment = new ActionParamsClass_DeleteAssessment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteAssessment DeleteAssessmentParams { get { return s_params_DeleteAssessment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteAssessment
        {
            public readonly string controllerData = "controllerData";
            public readonly string identifiableString = "identifiableString";
        }
        static readonly ActionParamsClass_ManageAssessmentRaiseDialog s_params_ManageAssessmentRaiseDialog = new ActionParamsClass_ManageAssessmentRaiseDialog();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ManageAssessmentRaiseDialog ManageAssessmentRaiseDialogParams { get { return s_params_ManageAssessmentRaiseDialog; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ManageAssessmentRaiseDialog
        {
            public readonly string controllerData = "controllerData";
            public readonly string identifiableString = "identifiableString";
            public readonly string entityType = "entityType";
        }
        static readonly ActionParamsClass_LCStageStepsPartial s_params_LCStageStepsPartial = new ActionParamsClass_LCStageStepsPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LCStageStepsPartial LCStageStepsPartialParams { get { return s_params_LCStageStepsPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LCStageStepsPartial
        {
            public readonly string controllerData = "controllerData";
            public readonly string assessmentIdent = "assessmentIdent";
        }
        static readonly ActionParamsClass_GetOpenDialogSettings s_params_GetOpenDialogSettings = new ActionParamsClass_GetOpenDialogSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOpenDialogSettings GetOpenDialogSettingsParams { get { return s_params_GetOpenDialogSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOpenDialogSettings
        {
            public readonly string originalActionName = "originalActionName";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string BusinessDataDialog = "BusinessDataDialog";
                public readonly string BusinessDataDialog_ts = "BusinessDataDialog_ts";
                public readonly string CreateAssessmentDialog = "CreateAssessmentDialog";
                public readonly string FirstCreateAssessmentDialog = "FirstCreateAssessmentDialog";
                public readonly string Index = "Index";
                public readonly string SecondCreateAssessmentDialog = "SecondCreateAssessmentDialog";
            }
            public readonly string BusinessDataDialog = "~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/BusinessDataDialog.cshtml";
            public readonly string BusinessDataDialog_ts = "~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/BusinessDataDialog.ts";
            public readonly string CreateAssessmentDialog = "~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/CreateAssessmentDialog.ts";
            public readonly string FirstCreateAssessmentDialog = "~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/FirstCreateAssessmentDialog.cshtml";
            public readonly string Index = "~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/Index.cshtml";
            public readonly string SecondCreateAssessmentDialog = "~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/SecondCreateAssessmentDialog.cshtml";
            static readonly _MergeInputsClass s_MergeInputs = new _MergeInputsClass();
            public _MergeInputsClass MergeInputs { get { return s_MergeInputs; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _MergeInputsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string MergeInputsDialog = "MergeInputsDialog";
                    public readonly string MergeInputsDialog_ts = "MergeInputsDialog_ts";
                }
                public readonly string MergeInputsDialog = "~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/MergeInputs/MergeInputsDialog.cshtml";
                public readonly string MergeInputsDialog_ts = "~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/MergeInputs/MergeInputsDialog.ts";
            }
            static readonly _SharedClass s_Shared = new _SharedClass();
            public _SharedClass Shared { get { return s_Shared; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _SharedClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string LCStageSteps = "LCStageSteps";
                    public readonly string LCStageSteps_ts = "LCStageSteps_ts";
                }
                public readonly string LCStageSteps = "~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/Shared/LCStageSteps.cshtml";
                public readonly string LCStageSteps_ts = "~/Areas/AssessmentNavigator/Views/CreateAssessmentDialog/Shared/LCStageSteps.ts";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_CreateAssessmentDialogController : Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Controllers.CreateAssessmentDialogController
    {
        public T4MVC_CreateAssessmentDialogController() : base(Dummy.Instance) { }

        [NonAction]
        partial void NewAssessmentDialogIndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Selerant.DevEx.Web.ViewControlControllerData controllerData);

        [NonAction]
        public override System.Web.Mvc.ActionResult NewAssessmentDialogIndex(Selerant.DevEx.Web.ViewControlControllerData controllerData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewAssessmentDialogIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            NewAssessmentDialogIndexOverride(callInfo, controllerData);
            return callInfo;
        }

        [NonAction]
        partial void BusinessDataDialogIndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Selerant.DevEx.Web.ViewControlControllerData controllerData, string identifiableString, bool cancelOrCloseDeletes);

        [NonAction]
        public override System.Web.Mvc.ActionResult BusinessDataDialogIndex(Selerant.DevEx.Web.ViewControlControllerData controllerData, string identifiableString, bool cancelOrCloseDeletes)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BusinessDataDialogIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "cancelOrCloseDeletes", cancelOrCloseDeletes);
            BusinessDataDialogIndexOverride(callInfo, controllerData, identifiableString, cancelOrCloseDeletes);
            return callInfo;
        }

        [NonAction]
        partial void MergeInputsDialogIndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Selerant.DevEx.Web.ViewControlControllerData controllerData, string identifiableString, decimal lcStageId, decimal nextLcStageId);

        [NonAction]
        public override System.Web.Mvc.ActionResult MergeInputsDialogIndex(Selerant.DevEx.Web.ViewControlControllerData controllerData, string identifiableString, decimal lcStageId, decimal nextLcStageId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MergeInputsDialogIndex);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lcStageId", lcStageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nextLcStageId", nextLcStageId);
            MergeInputsDialogIndexOverride(callInfo, controllerData, identifiableString, lcStageId, nextLcStageId);
            return callInfo;
        }

        [NonAction]
        partial void CarryMergedProductOverToTheNextStageOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.Web.ViewControlControllerData controllerData, string identifiableString, decimal lcStageId, decimal nextLcStageId, Selerant.DevEx.WebMvcModules.Infrastructure.Controls.SpreadsheetControl.Spreadsheet.ChangesAjaxParameter gridParam);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult CarryMergedProductOverToTheNextStage(Selerant.DevEx.Web.ViewControlControllerData controllerData, string identifiableString, decimal lcStageId, decimal nextLcStageId, Selerant.DevEx.WebMvcModules.Infrastructure.Controls.SpreadsheetControl.Spreadsheet.ChangesAjaxParameter gridParam)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.CarryMergedProductOverToTheNextStage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lcStageId", lcStageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nextLcStageId", nextLcStageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gridParam", gridParam);
            CarryMergedProductOverToTheNextStageOverride(callInfo, controllerData, identifiableString, lcStageId, nextLcStageId, gridParam);
            return callInfo;
        }

        [NonAction]
        partial void HasProductsToCarryOverOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.Web.ViewControlControllerData controllerData, string identifiableString, decimal lcStageId, decimal nextLcStageId);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult HasProductsToCarryOver(Selerant.DevEx.Web.ViewControlControllerData controllerData, string identifiableString, decimal lcStageId, decimal nextLcStageId)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.HasProductsToCarryOver);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lcStageId", lcStageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nextLcStageId", nextLcStageId);
            HasProductsToCarryOverOverride(callInfo, controllerData, identifiableString, lcStageId, nextLcStageId);
            return callInfo;
        }

        [NonAction]
        partial void CarryProductOverToTheNextStageOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.Web.ViewControlControllerData controllerData, string identifiableString, decimal lcStageId, decimal nextLcStageId, bool mergeInputs);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult CarryProductOverToTheNextStage(Selerant.DevEx.Web.ViewControlControllerData controllerData, string identifiableString, decimal lcStageId, decimal nextLcStageId, bool mergeInputs)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.CarryProductOverToTheNextStage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lcStageId", lcStageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nextLcStageId", nextLcStageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mergeInputs", mergeInputs);
            CarryProductOverToTheNextStageOverride(callInfo, controllerData, identifiableString, lcStageId, nextLcStageId, mergeInputs);
            return callInfo;
        }

        [NonAction]
        partial void ClearNextLcStageSourceOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.Web.ViewControlControllerData controllerData, decimal nextLcStageId);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult ClearNextLcStageSource(Selerant.DevEx.Web.ViewControlControllerData controllerData, decimal nextLcStageId)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.ClearNextLcStageSource);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nextLcStageId", nextLcStageId);
            ClearNextLcStageSourceOverride(callInfo, controllerData, nextLcStageId);
            return callInfo;
        }

        [NonAction]
        partial void CreateMaterialOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.Web.ViewControlControllerData controllerData, string description, string categoryType);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult CreateMaterial(Selerant.DevEx.Web.ViewControlControllerData controllerData, string description, string categoryType)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.CreateMaterial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "description", description);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "categoryType", categoryType);
            CreateMaterialOverride(callInfo, controllerData, description, categoryType);
            return callInfo;
        }

        [NonAction]
        partial void CreateNewAssessmentOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.Web.ViewControlControllerData controllerData, Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Models.ObjectCreation.IndexModel.CreateNewAssessmentDialogFormData formData);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult CreateNewAssessment(Selerant.DevEx.Web.ViewControlControllerData controllerData, Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Models.ObjectCreation.IndexModel.CreateNewAssessmentDialogFormData formData)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.CreateNewAssessment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formData", formData);
            CreateNewAssessmentOverride(callInfo, controllerData, formData);
            return callInfo;
        }

        [NonAction]
        partial void CreateNewAssessmentAndCloseDialogOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.Web.ViewControlControllerData controllerData, Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Models.ObjectCreation.IndexModel.CreateNewAssessmentDialogFormData formData);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult CreateNewAssessmentAndCloseDialog(Selerant.DevEx.Web.ViewControlControllerData controllerData, Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Models.ObjectCreation.IndexModel.CreateNewAssessmentDialogFormData formData)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.CreateNewAssessmentAndCloseDialog);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "formData", formData);
            CreateNewAssessmentAndCloseDialogOverride(callInfo, controllerData, formData);
            return callInfo;
        }

        [NonAction]
        partial void ChangeStatusAndCloseDialogOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.Web.ViewControlControllerData controllerData, string identifiableString);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult ChangeStatusAndCloseDialog(Selerant.DevEx.Web.ViewControlControllerData controllerData, string identifiableString)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.ChangeStatusAndCloseDialog);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            ChangeStatusAndCloseDialogOverride(callInfo, controllerData, identifiableString);
            return callInfo;
        }

        [NonAction]
        partial void DeleteAssessmentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Selerant.DevEx.Web.ViewControlControllerData controllerData, string identifiableString);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteAssessment(Selerant.DevEx.Web.ViewControlControllerData controllerData, string identifiableString)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAssessment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            DeleteAssessmentOverride(callInfo, controllerData, identifiableString);
            return callInfo;
        }

        [NonAction]
        partial void ManageAssessmentRaiseDialogOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.Web.ViewControlControllerData controllerData, string identifiableString, Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Models.Dialogs.ManageAssessment.EntityType entityType);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult ManageAssessmentRaiseDialog(Selerant.DevEx.Web.ViewControlControllerData controllerData, string identifiableString, Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentNavigator.Models.Dialogs.ManageAssessment.EntityType entityType)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.ManageAssessmentRaiseDialog);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "entityType", entityType);
            ManageAssessmentRaiseDialogOverride(callInfo, controllerData, identifiableString, entityType);
            return callInfo;
        }

        [NonAction]
        partial void LCStageStepsPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Selerant.DevEx.Web.ViewControlControllerData controllerData, string assessmentIdent);

        [NonAction]
        public override System.Web.Mvc.ActionResult LCStageStepsPartial(Selerant.DevEx.Web.ViewControlControllerData controllerData, string assessmentIdent)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LCStageStepsPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "controllerData", controllerData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "assessmentIdent", assessmentIdent);
            LCStageStepsPartialOverride(callInfo, controllerData, assessmentIdent);
            return callInfo;
        }

        [NonAction]
        partial void GetOpenDialogSettingsOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data callInfo, string originalActionName);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult<Selerant.DevEx.WebPages.OpenDialogSettings.Data> GetOpenDialogSettings(string originalActionName)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data(Area, Name, ActionNames.GetOpenDialogSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "originalActionName", originalActionName);
            GetOpenDialogSettingsOverride(callInfo, originalActionName);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
