// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using Autofac;
using Selerant.DevEx.Infrastructure;
using Selerant.Infrastructure.DependencyContainer;
using T4MVC_DIR;
using Selerant.DevEx.Modules.DIRModule.ModuleBlocks._ThisProject;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd._ThisProject;
using Selerant.DevEx.Infrastructure.Modules;
namespace Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers
{
    public partial class AssessmentCustomQueryPanelController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AssessmentCustomQueryPanelController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AssessmentCustomQueryPanelController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult DeleteQuery()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteQuery);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult GetCustomQueryBrowserPanelInDialogDirect()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetCustomQueryBrowserPanelInDialogDirect);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetList()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult FormODataLink()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.FormODataLink);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult GetPanelDirect()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetPanelDirect);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult Index()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult GetPanel()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetPanel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult GetPanelModelInclude()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetPanelModelInclude);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult LoadOnDemandPanel()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.LoadOnDemandPanel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult BeforeClosingSearchDialog()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.BeforeClosingSearchDialog);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult<Selerant.DevEx.WebPages.OpenDialogSettings.Data> GetOpenDialogSettings()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data(Area, Name, ActionNames.GetOpenDialogSettings);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AssessmentCustomQueryPanelController Actions { get { return MVC_DIR.AssessmentSearch.AssessmentCustomQueryPanel; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "AssessmentSearch";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "AssessmentCustomQueryPanel";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "AssessmentCustomQueryPanel";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string DeleteQuery = "DeleteQuery";
            public readonly string GetCustomQueryBrowserPanelInDialogDirect = "GetCustomQueryBrowserPanelInDialogDirect";
            public readonly string GetList = "GetList";
            public readonly string FormODataLink = "FormODataLink";
            public readonly string GetPanelDirect = "GetPanelDirect";
            public readonly string Index = "Index";
            public readonly string GetPanel = "GetPanel";
            public readonly string GetPanelModelInclude = "GetPanelModelInclude";
            public readonly string LoadOnDemandPanel = "LoadOnDemandPanel";
            public readonly string BeforeClosingSearchDialog = "BeforeClosingSearchDialog";
            public readonly string GetOpenDialogSettings = "GetOpenDialogSettings";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string DeleteQuery = "DeleteQuery";
            public const string GetCustomQueryBrowserPanelInDialogDirect = "GetCustomQueryBrowserPanelInDialogDirect";
            public const string GetList = "GetList";
            public const string FormODataLink = "FormODataLink";
            public const string GetPanelDirect = "GetPanelDirect";
            public const string Index = "Index";
            public const string GetPanel = "GetPanel";
            public const string GetPanelModelInclude = "GetPanelModelInclude";
            public const string LoadOnDemandPanel = "LoadOnDemandPanel";
            public const string BeforeClosingSearchDialog = "BeforeClosingSearchDialog";
            public const string GetOpenDialogSettings = "GetOpenDialogSettings";
        }


        static readonly ActionParamsClass_DeleteQuery s_params_DeleteQuery = new ActionParamsClass_DeleteQuery();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteQuery DeleteQueryParams { get { return s_params_DeleteQuery; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteQuery
        {
            public readonly string data = "data";
            public readonly string queryId = "queryId";
        }
        static readonly ActionParamsClass_GetCustomQueryBrowserPanelInDialogDirect s_params_GetCustomQueryBrowserPanelInDialogDirect = new ActionParamsClass_GetCustomQueryBrowserPanelInDialogDirect();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCustomQueryBrowserPanelInDialogDirect GetCustomQueryBrowserPanelInDialogDirectParams { get { return s_params_GetCustomQueryBrowserPanelInDialogDirect; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCustomQueryBrowserPanelInDialogDirect
        {
            public readonly string data = "data";
        }
        static readonly ActionParamsClass_GetList s_params_GetList = new ActionParamsClass_GetList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetList GetListParams { get { return s_params_GetList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetList
        {
            public readonly string data = "data";
            public readonly string gridId = "gridId";
            public readonly string queryType = "queryType";
            public readonly string targetObjectIdentifiableString = "targetObjectIdentifiableString";
        }
        static readonly ActionParamsClass_FormODataLink s_params_FormODataLink = new ActionParamsClass_FormODataLink();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_FormODataLink FormODataLinkParams { get { return s_params_FormODataLink; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_FormODataLink
        {
            public readonly string data = "data";
            public readonly string queryId = "queryId";
        }
        static readonly ActionParamsClass_GetPanelDirect s_params_GetPanelDirect = new ActionParamsClass_GetPanelDirect();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPanelDirect GetPanelDirectParams { get { return s_params_GetPanelDirect; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPanelDirect
        {
            public readonly string data = "data";
            public readonly string tab = "tab";
            public readonly string id = "id";
            public readonly string isDialog = "isDialog";
            public readonly string filters = "filters";
        }
        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string data = "data";
            public readonly string searchController = "searchController";
            public readonly string nodeId = "nodeId";
        }
        static readonly ActionParamsClass_GetPanel s_params_GetPanel = new ActionParamsClass_GetPanel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPanel GetPanelParams { get { return s_params_GetPanel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPanel
        {
            public readonly string data = "data";
            public readonly string searchController = "searchController";
            public readonly string nodeId = "nodeId";
        }
        static readonly ActionParamsClass_GetPanelModelInclude s_params_GetPanelModelInclude = new ActionParamsClass_GetPanelModelInclude();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPanelModelInclude GetPanelModelIncludeParams { get { return s_params_GetPanelModelInclude; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPanelModelInclude
        {
            public readonly string data = "data";
            public readonly string panelModel = "panelModel";
        }
        static readonly ActionParamsClass_LoadOnDemandPanel s_params_LoadOnDemandPanel = new ActionParamsClass_LoadOnDemandPanel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LoadOnDemandPanel LoadOnDemandPanelParams { get { return s_params_LoadOnDemandPanel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LoadOnDemandPanel
        {
            public readonly string data = "data";
            public readonly string dataModel = "dataModel";
        }
        static readonly ActionParamsClass_BeforeClosingSearchDialog s_params_BeforeClosingSearchDialog = new ActionParamsClass_BeforeClosingSearchDialog();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BeforeClosingSearchDialog BeforeClosingSearchDialogParams { get { return s_params_BeforeClosingSearchDialog; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BeforeClosingSearchDialog
        {
            public readonly string data = "data";
            public readonly string identifiableStrings = "identifiableStrings";
        }
        static readonly ActionParamsClass_GetOpenDialogSettings s_params_GetOpenDialogSettings = new ActionParamsClass_GetOpenDialogSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOpenDialogSettings GetOpenDialogSettingsParams { get { return s_params_GetOpenDialogSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOpenDialogSettings
        {
            public readonly string originalActionName = "originalActionName";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AssessmentCustomQueryPanelController : Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.AssessmentCustomQueryPanelController
    {
        public T4MVC_AssessmentCustomQueryPanelController() : base(Dummy.Instance) { }

        [NonAction]
        partial void DeleteQueryOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string queryId);

        [NonAction]
        public override System.Web.Mvc.JsonResult DeleteQuery(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string queryId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteQuery);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "queryId", queryId);
            DeleteQueryOverride(callInfo, data, queryId);
            return callInfo;
        }

        [NonAction]
        partial void GetCustomQueryBrowserPanelInDialogDirectOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data);

        [NonAction]
        public override System.Web.Mvc.ViewResult GetCustomQueryBrowserPanelInDialogDirect(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetCustomQueryBrowserPanelInDialogDirect);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            GetCustomQueryBrowserPanelInDialogDirectOverride(callInfo, data);
            return callInfo;
        }

        [NonAction]
        partial void GetListOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string gridId, string queryType, string targetObjectIdentifiableString);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetList(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string gridId, string queryType, string targetObjectIdentifiableString)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "gridId", gridId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "queryType", queryType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "targetObjectIdentifiableString", targetObjectIdentifiableString);
            GetListOverride(callInfo, data, gridId, queryType, targetObjectIdentifiableString);
            return callInfo;
        }

        [NonAction]
        partial void FormODataLinkOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string queryId);

        [NonAction]
        public override System.Web.Mvc.JsonResult FormODataLink(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string queryId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.FormODataLink);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "queryId", queryId);
            FormODataLinkOverride(callInfo, data, queryId);
            return callInfo;
        }

        [NonAction]
        partial void GetPanelDirectOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string tab, string id, bool isDialog, string filters);

        [NonAction]
        public override System.Web.Mvc.ViewResult GetPanelDirect(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string tab, string id, bool isDialog, string filters)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetPanelDirect);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tab", tab);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isDialog", isDialog);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filters", filters);
            GetPanelDirectOverride(callInfo, data, tab, id, isDialog, filters);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.ISearchController searchController, string nodeId);

        [NonAction]
        public override System.Web.Mvc.ViewResult Index(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.ISearchController searchController, string nodeId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchController", searchController);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nodeId", nodeId);
            IndexOverride(callInfo, data, searchController, nodeId);
            return callInfo;
        }

        [NonAction]
        partial void GetPanelOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.ISearchController searchController, string nodeId);

        [NonAction]
        public override System.Web.Mvc.ViewResult GetPanel(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.ISearchController searchController, string nodeId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetPanel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchController", searchController);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nodeId", nodeId);
            GetPanelOverride(callInfo, data, searchController, nodeId);
            return callInfo;
        }

        [NonAction]
        partial void GetPanelModelIncludeOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.DevExSearchPanelIndexModel panelModel);

        [NonAction]
        public override System.Web.Mvc.ViewResult GetPanelModelInclude(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.DevExSearchPanelIndexModel panelModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetPanelModelInclude);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "panelModel", panelModel);
            GetPanelModelIncludeOverride(callInfo, data, panelModel);
            return callInfo;
        }

        [NonAction]
        partial void LoadOnDemandPanelOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchLoadOnDemandDataModel dataModel);

        [NonAction]
        public override System.Web.Mvc.ViewResult LoadOnDemandPanel(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchLoadOnDemandDataModel dataModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.LoadOnDemandPanel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dataModel", dataModel);
            LoadOnDemandPanelOverride(callInfo, data, dataModel);
            return callInfo;
        }

        [NonAction]
        partial void BeforeClosingSearchDialogOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string[] identifiableStrings);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult BeforeClosingSearchDialog(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string[] identifiableStrings)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.BeforeClosingSearchDialog);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableStrings", identifiableStrings);
            BeforeClosingSearchDialogOverride(callInfo, data, identifiableStrings);
            return callInfo;
        }

        [NonAction]
        partial void GetOpenDialogSettingsOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data callInfo, string originalActionName);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult<Selerant.DevEx.WebPages.OpenDialogSettings.Data> GetOpenDialogSettings(string originalActionName)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data(Area, Name, ActionNames.GetOpenDialogSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "originalActionName", originalActionName);
            GetOpenDialogSettingsOverride(callInfo, originalActionName);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
