// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using Autofac;
using Selerant.DevEx.Infrastructure;
using Selerant.Infrastructure.DependencyContainer;
using T4MVC_DIR;
using Selerant.DevEx.Modules.DIRModule.ModuleBlocks._ThisProject;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd;
using Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd._ThisProject;
using Selerant.DevEx.Infrastructure.Modules;
namespace Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult ConfigureSearchOptions()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.ConfigureSearchOptions);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult GetActiveSearchOptionsView()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetActiveSearchOptionsView);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult GetHiddenSearchOptionsView()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetHiddenSearchOptionsView);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult RestoreDefault()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RestoreDefault);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SaveSearchOptionConfiguration()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SaveSearchOptionConfiguration);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult DoAutoSearch()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DoAutoSearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult DoSearch()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DoSearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetIdentitiesOfAllSearchResults()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetIdentitiesOfAllSearchResults);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GetParentSelectedItem()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetParentSelectedItem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult WhereUsedSearch()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.WhereUsedSearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult CustomQuerySearch()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CustomQuerySearch);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LabelRefinement()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LabelRefinement);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RefineHistoryCurrentStep()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RefineHistoryCurrentStep);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.AjaxResult ChangePanelIsOpenSettings()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult(Area, Name, ActionNames.ChangePanelIsOpenSettings);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.AjaxResult ChangeSearchOptionIsFocusedSettings()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult(Area, Name, ActionNames.ChangeSearchOptionIsFocusedSettings);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SetCurrentStep()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetCurrentStep);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult AddToRecent()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AddToRecent);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult LoadOnDemandPanel()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.LoadOnDemandPanel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult BeforeClosingSearchDialog()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.BeforeClosingSearchDialog);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult<Selerant.DevEx.WebPages.OpenDialogSettings.Data> GetOpenDialogSettings()
        {
            return new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data(Area, Name, ActionNames.GetOpenDialogSettings);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC_DIR.AssessmentSearch.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "AssessmentSearch";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string IndexDialog = "IndexDialog";
            public readonly string ConfigureSearchOptions = "ConfigureSearchOptions";
            public readonly string GetActiveSearchOptionsView = "GetActiveSearchOptionsView";
            public readonly string GetHiddenSearchOptionsView = "GetHiddenSearchOptionsView";
            public readonly string RestoreDefault = "RestoreDefault";
            public readonly string SaveSearchOptionConfiguration = "SaveSearchOptionConfiguration";
            public readonly string DoAutoSearch = "DoAutoSearch";
            public readonly string DoSearch = "DoSearch";
            public readonly string GetIdentitiesOfAllSearchResults = "GetIdentitiesOfAllSearchResults";
            public readonly string GetParentSelectedItem = "GetParentSelectedItem";
            public readonly string WhereUsedSearch = "WhereUsedSearch";
            public readonly string CustomQuerySearch = "CustomQuerySearch";
            public readonly string LabelRefinement = "LabelRefinement";
            public readonly string RefineHistoryCurrentStep = "RefineHistoryCurrentStep";
            public readonly string ChangePanelIsOpenSettings = "ChangePanelIsOpenSettings";
            public readonly string ChangeSearchOptionIsFocusedSettings = "ChangeSearchOptionIsFocusedSettings";
            public readonly string SetCurrentStep = "SetCurrentStep";
            public readonly string AddToRecent = "AddToRecent";
            public readonly string LoadOnDemandPanel = "LoadOnDemandPanel";
            public readonly string BeforeClosingSearchDialog = "BeforeClosingSearchDialog";
            public readonly string GetOpenDialogSettings = "GetOpenDialogSettings";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string IndexDialog = "IndexDialog";
            public const string ConfigureSearchOptions = "ConfigureSearchOptions";
            public const string GetActiveSearchOptionsView = "GetActiveSearchOptionsView";
            public const string GetHiddenSearchOptionsView = "GetHiddenSearchOptionsView";
            public const string RestoreDefault = "RestoreDefault";
            public const string SaveSearchOptionConfiguration = "SaveSearchOptionConfiguration";
            public const string DoAutoSearch = "DoAutoSearch";
            public const string DoSearch = "DoSearch";
            public const string GetIdentitiesOfAllSearchResults = "GetIdentitiesOfAllSearchResults";
            public const string GetParentSelectedItem = "GetParentSelectedItem";
            public const string WhereUsedSearch = "WhereUsedSearch";
            public const string CustomQuerySearch = "CustomQuerySearch";
            public const string LabelRefinement = "LabelRefinement";
            public const string RefineHistoryCurrentStep = "RefineHistoryCurrentStep";
            public const string ChangePanelIsOpenSettings = "ChangePanelIsOpenSettings";
            public const string ChangeSearchOptionIsFocusedSettings = "ChangeSearchOptionIsFocusedSettings";
            public const string SetCurrentStep = "SetCurrentStep";
            public const string AddToRecent = "AddToRecent";
            public const string LoadOnDemandPanel = "LoadOnDemandPanel";
            public const string BeforeClosingSearchDialog = "BeforeClosingSearchDialog";
            public const string GetOpenDialogSettings = "GetOpenDialogSettings";
        }


        static readonly ActionParamsClass_IndexDialog s_params_IndexDialog = new ActionParamsClass_IndexDialog();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IndexDialog IndexDialogParams { get { return s_params_IndexDialog; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IndexDialog
        {
            public readonly string clearSearchCache = "clearSearchCache";
        }
        static readonly ActionParamsClass_ConfigureSearchOptions s_params_ConfigureSearchOptions = new ActionParamsClass_ConfigureSearchOptions();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ConfigureSearchOptions ConfigureSearchOptionsParams { get { return s_params_ConfigureSearchOptions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ConfigureSearchOptions
        {
            public readonly string data = "data";
        }
        static readonly ActionParamsClass_GetActiveSearchOptionsView s_params_GetActiveSearchOptionsView = new ActionParamsClass_GetActiveSearchOptionsView();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetActiveSearchOptionsView GetActiveSearchOptionsViewParams { get { return s_params_GetActiveSearchOptionsView; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetActiveSearchOptionsView
        {
            public readonly string data = "data";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GetHiddenSearchOptionsView s_params_GetHiddenSearchOptionsView = new ActionParamsClass_GetHiddenSearchOptionsView();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetHiddenSearchOptionsView GetHiddenSearchOptionsViewParams { get { return s_params_GetHiddenSearchOptionsView; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetHiddenSearchOptionsView
        {
            public readonly string data = "data";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_RestoreDefault s_params_RestoreDefault = new ActionParamsClass_RestoreDefault();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RestoreDefault RestoreDefaultParams { get { return s_params_RestoreDefault; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RestoreDefault
        {
            public readonly string data = "data";
        }
        static readonly ActionParamsClass_SaveSearchOptionConfiguration s_params_SaveSearchOptionConfiguration = new ActionParamsClass_SaveSearchOptionConfiguration();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveSearchOptionConfiguration SaveSearchOptionConfigurationParams { get { return s_params_SaveSearchOptionConfiguration; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveSearchOptionConfiguration
        {
            public readonly string data = "data";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DoAutoSearch s_params_DoAutoSearch = new ActionParamsClass_DoAutoSearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DoAutoSearch DoAutoSearchParams { get { return s_params_DoAutoSearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DoAutoSearch
        {
            public readonly string data = "data";
            public readonly string selectedTab = "selectedTab";
            public readonly string filters = "filters";
        }
        static readonly ActionParamsClass_DoSearch s_params_DoSearch = new ActionParamsClass_DoSearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DoSearch DoSearchParams { get { return s_params_DoSearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DoSearch
        {
            public readonly string data = "data";
            public readonly string searchData = "searchData";
            public readonly string searchOptionId = "searchOptionId";
            public readonly string refinementOperator = "refinementOperator";
            public readonly string filters = "filters";
        }
        static readonly ActionParamsClass_GetIdentitiesOfAllSearchResults s_params_GetIdentitiesOfAllSearchResults = new ActionParamsClass_GetIdentitiesOfAllSearchResults();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetIdentitiesOfAllSearchResults GetIdentitiesOfAllSearchResultsParams { get { return s_params_GetIdentitiesOfAllSearchResults; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetIdentitiesOfAllSearchResults
        {
            public readonly string data = "data";
        }
        static readonly ActionParamsClass_GetParentSelectedItem s_params_GetParentSelectedItem = new ActionParamsClass_GetParentSelectedItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetParentSelectedItem GetParentSelectedItemParams { get { return s_params_GetParentSelectedItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetParentSelectedItem
        {
            public readonly string data = "data";
            public readonly string parentFilterScope = "parentFilterScope";
            public readonly string parentFilterIDKey = "parentFilterIDKey";
            public readonly string selectedIdentifiableString = "selectedIdentifiableString";
        }
        static readonly ActionParamsClass_WhereUsedSearch s_params_WhereUsedSearch = new ActionParamsClass_WhereUsedSearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_WhereUsedSearch WhereUsedSearchParams { get { return s_params_WhereUsedSearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_WhereUsedSearch
        {
            public readonly string data = "data";
            public readonly string ingredients = "ingredients";
            public readonly string maximumDepth = "maximumDepth";
            public readonly string displayResultOption = "displayResultOption";
            public readonly string joinMode = "joinMode";
            public readonly string filterQueryName = "filterQueryName";
            public readonly string refinementOperator = "refinementOperator";
            public readonly string filters = "filters";
        }
        static readonly ActionParamsClass_CustomQuerySearch s_params_CustomQuerySearch = new ActionParamsClass_CustomQuerySearch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CustomQuerySearch CustomQuerySearchParams { get { return s_params_CustomQuerySearch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CustomQuerySearch
        {
            public readonly string data = "data";
            public readonly string queryId = "queryId";
            public readonly string customQueryRows = "customQueryRows";
            public readonly string refinementOperator = "refinementOperator";
            public readonly string filters = "filters";
        }
        static readonly ActionParamsClass_LabelRefinement s_params_LabelRefinement = new ActionParamsClass_LabelRefinement();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LabelRefinement LabelRefinementParams { get { return s_params_LabelRefinement; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LabelRefinement
        {
            public readonly string data = "data";
        }
        static readonly ActionParamsClass_RefineHistoryCurrentStep s_params_RefineHistoryCurrentStep = new ActionParamsClass_RefineHistoryCurrentStep();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RefineHistoryCurrentStep RefineHistoryCurrentStepParams { get { return s_params_RefineHistoryCurrentStep; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RefineHistoryCurrentStep
        {
            public readonly string data = "data";
            public readonly string currentStep = "currentStep";
        }
        static readonly ActionParamsClass_ChangePanelIsOpenSettings s_params_ChangePanelIsOpenSettings = new ActionParamsClass_ChangePanelIsOpenSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangePanelIsOpenSettings ChangePanelIsOpenSettingsParams { get { return s_params_ChangePanelIsOpenSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangePanelIsOpenSettings
        {
            public readonly string data = "data";
            public readonly string nodeId = "nodeId";
            public readonly string searchOptionId = "searchOptionId";
            public readonly string isOpen = "isOpen";
        }
        static readonly ActionParamsClass_ChangeSearchOptionIsFocusedSettings s_params_ChangeSearchOptionIsFocusedSettings = new ActionParamsClass_ChangeSearchOptionIsFocusedSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangeSearchOptionIsFocusedSettings ChangeSearchOptionIsFocusedSettingsParams { get { return s_params_ChangeSearchOptionIsFocusedSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangeSearchOptionIsFocusedSettings
        {
            public readonly string data = "data";
            public readonly string searchOptionId = "searchOptionId";
            public readonly string isFocused = "isFocused";
        }
        static readonly ActionParamsClass_SetCurrentStep s_params_SetCurrentStep = new ActionParamsClass_SetCurrentStep();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetCurrentStep SetCurrentStepParams { get { return s_params_SetCurrentStep; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetCurrentStep
        {
            public readonly string data = "data";
        }
        static readonly ActionParamsClass_AddToRecent s_params_AddToRecent = new ActionParamsClass_AddToRecent();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddToRecent AddToRecentParams { get { return s_params_AddToRecent; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddToRecent
        {
            public readonly string data = "data";
            public readonly string identifiableString = "identifiableString";
        }
        static readonly ActionParamsClass_LoadOnDemandPanel s_params_LoadOnDemandPanel = new ActionParamsClass_LoadOnDemandPanel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LoadOnDemandPanel LoadOnDemandPanelParams { get { return s_params_LoadOnDemandPanel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LoadOnDemandPanel
        {
            public readonly string data = "data";
            public readonly string dataModel = "dataModel";
        }
        static readonly ActionParamsClass_BeforeClosingSearchDialog s_params_BeforeClosingSearchDialog = new ActionParamsClass_BeforeClosingSearchDialog();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_BeforeClosingSearchDialog BeforeClosingSearchDialogParams { get { return s_params_BeforeClosingSearchDialog; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_BeforeClosingSearchDialog
        {
            public readonly string data = "data";
            public readonly string identifiableStrings = "identifiableStrings";
        }
        static readonly ActionParamsClass_GetOpenDialogSettings s_params_GetOpenDialogSettings = new ActionParamsClass_GetOpenDialogSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOpenDialogSettings GetOpenDialogSettingsParams { get { return s_params_GetOpenDialogSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOpenDialogSettings
        {
            public readonly string originalActionName = "originalActionName";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AssessmentIndexModel = "AssessmentIndexModel";
            }
            public readonly string AssessmentIndexModel = "~/Areas/AssessmentSearch/Views/Home/AssessmentIndexModel.ts";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HomeController : Selerant.DevEx.Modules.DIRModule.WebMvcFrontEnd.Areas.AssessmentSearch.Controllers.HomeController
    {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ViewResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void IndexDialogOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, bool clearSearchCache);

        [NonAction]
        public override System.Web.Mvc.ViewResult IndexDialog(bool clearSearchCache)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.IndexDialog);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "clearSearchCache", clearSearchCache);
            IndexDialogOverride(callInfo, clearSearchCache);
            return callInfo;
        }

        [NonAction]
        partial void ConfigureSearchOptionsOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data);

        [NonAction]
        public override System.Web.Mvc.ViewResult ConfigureSearchOptions(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.ConfigureSearchOptions);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ConfigureSearchOptionsOverride(callInfo, data);
            return callInfo;
        }

        [NonAction]
        partial void GetActiveSearchOptionsViewOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Models.GridColumnsModel model);

        [NonAction]
        public override System.Web.Mvc.ViewResult GetActiveSearchOptionsView(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Models.GridColumnsModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetActiveSearchOptionsView);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            GetActiveSearchOptionsViewOverride(callInfo, data, model);
            return callInfo;
        }

        [NonAction]
        partial void GetHiddenSearchOptionsViewOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Models.GridColumnsModel model);

        [NonAction]
        public override System.Web.Mvc.ViewResult GetHiddenSearchOptionsView(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Models.GridColumnsModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.GetHiddenSearchOptionsView);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            GetHiddenSearchOptionsViewOverride(callInfo, data, model);
            return callInfo;
        }

        [NonAction]
        partial void RestoreDefaultOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data);

        [NonAction]
        public override System.Web.Mvc.JsonResult RestoreDefault(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RestoreDefault);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            RestoreDefaultOverride(callInfo, data);
            return callInfo;
        }

        [NonAction]
        partial void SaveSearchOptionConfigurationOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Models.GridColumnsModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult SaveSearchOptionConfiguration(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Models.GridColumnsModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SaveSearchOptionConfiguration);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SaveSearchOptionConfigurationOverride(callInfo, data, model);
            return callInfo;
        }

        [NonAction]
        partial void DoAutoSearchOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string selectedTab, string filters);

        [NonAction]
        public override System.Web.Mvc.JsonResult DoAutoSearch(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string selectedTab, string filters)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DoAutoSearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "selectedTab", selectedTab);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filters", filters);
            DoAutoSearchOverride(callInfo, data, selectedTab, filters);
            return callInfo;
        }

        [NonAction]
        partial void DoSearchOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, System.Collections.Generic.Dictionary<string, string> searchData, string searchOptionId, string refinementOperator, string filters);

        [NonAction]
        public override System.Web.Mvc.JsonResult DoSearch(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, System.Collections.Generic.Dictionary<string, string> searchData, string searchOptionId, string refinementOperator, string filters)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DoSearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchData", searchData);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchOptionId", searchOptionId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "refinementOperator", refinementOperator);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filters", filters);
            DoSearchOverride(callInfo, data, searchData, searchOptionId, refinementOperator, filters);
            return callInfo;
        }

        [NonAction]
        partial void GetIdentitiesOfAllSearchResultsOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetIdentitiesOfAllSearchResults(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetIdentitiesOfAllSearchResults);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            GetIdentitiesOfAllSearchResultsOverride(callInfo, data);
            return callInfo;
        }

        [NonAction]
        partial void GetParentSelectedItemOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string parentFilterScope, string parentFilterIDKey, string selectedIdentifiableString);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetParentSelectedItem(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string parentFilterScope, string parentFilterIDKey, string selectedIdentifiableString)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetParentSelectedItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parentFilterScope", parentFilterScope);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parentFilterIDKey", parentFilterIDKey);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "selectedIdentifiableString", selectedIdentifiableString);
            GetParentSelectedItemOverride(callInfo, data, parentFilterScope, parentFilterIDKey, selectedIdentifiableString);
            return callInfo;
        }

        [NonAction]
        partial void WhereUsedSearchOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, System.Collections.Generic.List<Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.Ingredient> ingredients, string maximumDepth, string displayResultOption, string joinMode, string filterQueryName, string refinementOperator, string filters);

        [NonAction]
        public override System.Web.Mvc.JsonResult WhereUsedSearch(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, System.Collections.Generic.List<Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.Ingredient> ingredients, string maximumDepth, string displayResultOption, string joinMode, string filterQueryName, string refinementOperator, string filters)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.WhereUsedSearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ingredients", ingredients);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "maximumDepth", maximumDepth);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "displayResultOption", displayResultOption);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "joinMode", joinMode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filterQueryName", filterQueryName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "refinementOperator", refinementOperator);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filters", filters);
            WhereUsedSearchOverride(callInfo, data, ingredients, maximumDepth, displayResultOption, joinMode, filterQueryName, refinementOperator, filters);
            return callInfo;
        }

        [NonAction]
        partial void CustomQuerySearchOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string queryId, System.Collections.Generic.List<Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Controllers.CustomQueryJsonRow> customQueryRows, string refinementOperator, string filters);

        [NonAction]
        public override System.Web.Mvc.JsonResult CustomQuerySearch(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string queryId, System.Collections.Generic.List<Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Controllers.CustomQueryJsonRow> customQueryRows, string refinementOperator, string filters)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CustomQuerySearch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "queryId", queryId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "customQueryRows", customQueryRows);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "refinementOperator", refinementOperator);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filters", filters);
            CustomQuerySearchOverride(callInfo, data, queryId, customQueryRows, refinementOperator, filters);
            return callInfo;
        }

        [NonAction]
        partial void LabelRefinementOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data);

        [NonAction]
        public override System.Web.Mvc.ActionResult LabelRefinement(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LabelRefinement);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            LabelRefinementOverride(callInfo, data);
            return callInfo;
        }

        [NonAction]
        partial void RefineHistoryCurrentStepOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string[] currentStep);

        [NonAction]
        public override System.Web.Mvc.ActionResult RefineHistoryCurrentStep(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string[] currentStep)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RefineHistoryCurrentStep);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "currentStep", currentStep);
            RefineHistoryCurrentStepOverride(callInfo, data, currentStep);
            return callInfo;
        }

        [NonAction]
        partial void ChangePanelIsOpenSettingsOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string nodeId, string searchOptionId, bool isOpen);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.AjaxResult ChangePanelIsOpenSettings(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string nodeId, string searchOptionId, bool isOpen)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult(Area, Name, ActionNames.ChangePanelIsOpenSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nodeId", nodeId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchOptionId", searchOptionId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isOpen", isOpen);
            ChangePanelIsOpenSettingsOverride(callInfo, data, nodeId, searchOptionId, isOpen);
            return callInfo;
        }

        [NonAction]
        partial void ChangeSearchOptionIsFocusedSettingsOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string searchOptionId, bool isFocused);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.AjaxResult ChangeSearchOptionIsFocusedSettings(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string searchOptionId, bool isFocused)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_AjaxResult(Area, Name, ActionNames.ChangeSearchOptionIsFocusedSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "searchOptionId", searchOptionId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isFocused", isFocused);
            ChangeSearchOptionIsFocusedSettingsOverride(callInfo, data, searchOptionId, isFocused);
            return callInfo;
        }

        [NonAction]
        partial void SetCurrentStepOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data);

        [NonAction]
        public override System.Web.Mvc.ActionResult SetCurrentStep(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetCurrentStep);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            SetCurrentStepOverride(callInfo, data);
            return callInfo;
        }

        [NonAction]
        partial void AddToRecentOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string identifiableString);

        [NonAction]
        public override System.Web.Mvc.JsonResult AddToRecent(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string identifiableString)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AddToRecent);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableString", identifiableString);
            AddToRecentOverride(callInfo, data, identifiableString);
            return callInfo;
        }

        [NonAction]
        partial void LoadOnDemandPanelOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchLoadOnDemandDataModel dataModel);

        [NonAction]
        public override System.Web.Mvc.ViewResult LoadOnDemandPanel(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchLoadOnDemandDataModel dataModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.LoadOnDemandPanel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dataModel", dataModel);
            LoadOnDemandPanelOverride(callInfo, data, dataModel);
            return callInfo;
        }

        [NonAction]
        partial void BeforeClosingSearchDialogOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult callInfo, Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string[] identifiableStrings);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult BeforeClosingSearchDialog(Selerant.DevEx.WebMvcModules.Infrastructure.Searches.Models.SearchControllerData data, string[] identifiableStrings)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult(Area, Name, ActionNames.BeforeClosingSearchDialog);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "data", data);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "identifiableStrings", identifiableStrings);
            BeforeClosingSearchDialogOverride(callInfo, data, identifiableStrings);
            return callInfo;
        }

        [NonAction]
        partial void GetOpenDialogSettingsOverride(T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data callInfo, string originalActionName);

        [NonAction]
        public override Selerant.DevEx.WebMvcModules.Infrastructure.Base.DataAjaxResult<Selerant.DevEx.WebPages.OpenDialogSettings.Data> GetOpenDialogSettings(string originalActionName)
        {
            var callInfo = new T4MVC_Selerant_DevEx_WebMvcModules_Infrastructure_Base_DataAjaxResult_Selerant_DevEx_WebPages_OpenDialogSettings_Data(Area, Name, ActionNames.GetOpenDialogSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "originalActionName", originalActionName);
            GetOpenDialogSettingsOverride(callInfo, originalActionName);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
