IF EXISTS ( SELECT *
			FROM sys.objects so
			JOIN sys.schemas sc ON so.schema_id = sc.schema_id
			WHERE so.NAME = N'DXDIR_PK_INPUT$HasInputsToCarryOverCount'
			  AND so.type IN (N'P') AND sc.NAME = N'dbo' )
	DROP PROCEDURE [dbo].[DXDIR_PK_INPUT$HasInputsToCarryOverCount]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DXDIR_PK_INPUT$HasInputsToCarryOverCount]
	@sASSESSMENT_CODE VARCHAR(32),
	@dcASSESSMENT_LC_STAGE_ID_CUR BIGINT,
	@dcASSESSMENT_LC_STAGE_ID_NEXT VARCHAR(32),
	@dcRESULT_CURRENT BIGINT OUTPUT,
	@dcRESULT_NEXT BIGINT OUTPUT
AS
BEGIN
	SELECT 
	 	@dcRESULT_CURRENT = COUNT(*) 
	FROM DXDIR_INPUT I
	JOIN DXDIR_INPUT_DESTINATION D
	ON I.ID = D.INPUT_ID
	WHERE I.ASSESSMENT_CODE			 = @sASSESSMENT_CODE				AND 
          I.ASSESSMENT_LC_STAGE_ID	 = @dcASSESSMENT_LC_STAGE_ID_CUR	AND 
          D.DESTINATION_CODE LIKE 'PRODUCT%'							AND
          D.PERCENTAGE > 0;
    
	SELECT 
		@dcRESULT_NEXT = COUNT(*) 
	FROM DXDIR_INPUT 
	WHERE ASSESSMENT_CODE		 = @sASSESSMENT_CODE AND
		  ASSESSMENT_LC_STAGE_ID = @dcASSESSMENT_LC_STAGE_ID_NEXT;
END
GO